### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'falcon-kit' distribution was not found

### ISSUE THREAD

**Issue by mictadlo** [PacificBiosciences/FALCON-integrate#101]
Hi,
I followed the Falcon wiki to install version 1.8.0.
```
../FALCON-examples/run/ecoli> fc_run fc_run.cfg 
Traceback (most recent call last):
  File "/QRISdata/Q0231/software/FALCON-integrate/fc_env/bin/fc_run", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/QRISdata/Q0231/apps/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2985, in <module>
  File "/QRISdata/Q0231/apps/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2971, in _call_aside
  File "/QRISdata/Q0231/apps/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2998, in _initialize_master_working_set
  File "/QRISdata/Q0231/apps/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 660, in _build_master
  File "/QRISdata/Q0231/apps/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 968, in require
  File "/QRISdata/Q0231/apps/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 854, in resolve
pkg_resources.DistributionNotFound: The 'falcon-kit' distribution was not found and is required by the application.
```

What did I do miss?

Thank you in advance.

Mic

**Comment by pb-cdunn** [comment]
Is `PYTYHONUSERBASE` in your shell environment? (See `env.sh` during installation.)

**Comment by mictadlo** [comment]
Thank you. It works now

**Comment by yangjie4546** [comment]
Hi, mictadlo. I meet the same question as yours. Could you please put the details of your ways? THANK YOU!

**Comment by yangjie4546** [comment]
I think I have solved the question, just unset PYTHONPATH; then source env.sh. Hope it is helpful.
