### ISSUE TITLE
installation fails with permission problem

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON-integrate#105]
Let me know if you have any suggestions of what else I could try.  I've done this many times with small changes, but each time is unsuccessful (e.g., I tried "master" instead of "1.8.2"):

Here is my install script:

```
git clone git://github.com/PacificBiosciences/FALCON-integrate.git
cd FALCON-integrate
git checkout 1.8.2  # or whatever version you want
make init
module unload anaconda
module load anaconda/2.3.0
source env.sh
make config-edit-user
module unload anaconda
module load anaconda/2.3.0
env | grep PYTHON
make -j all
```

and here is the results:

```Cloning into 'FALCON-integrate'...
Note: checking out '1.8.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 02867d3... bug-fix
git submodule update --init
Submodule 'DALIGNER' (git://github.com/PacificBiosciences/DALIGNER.git) registered for path 'DALIGNER'
Submodule 'DAMASKER' (git://github.com/PacificBiosciences/DAMASKER) registered for path 'DAMASKER'
Submodule 'DAZZ_DB' (git://github.com/PacificBiosciences/DAZZ_DB.git) registered for path 'DAZZ_DB'
Submodule 'DEXTRACTOR' (git://github.com/PacificBiosciences/DEXTRACTOR) registered for path 'DEXTRACTOR'
Submodule 'FALCON' (git://github.com/PacificBiosciences/FALCON.git) registered for path 'FALCON'
Submodule 'FALCON-examples' (git://github.com/pb-cdunn/FALCON-examples.git) registered for path 'FALCON-examples'
Submodule 'FALCON-make' (git://github.com/pb-cdunn/FALCON-make.git) registered for path 'FALCON-make'
Submodule 'git-sym' (git://github.com/cdunn2001/git-sym.git) registered for path 'git-sym'
Submodule 'pypeFLOW' (git://github.com/PacificBiosciences/pypeFLOW.git) registered for path 'pypeFLOW'
Cloning into 'DALIGNER'...
Submodule path 'DALIGNER': checked out '4e1c1720b598ce2aaf6aa074cbb4317c4cd750de'
Cloning into 'DAMASKER'...
Submodule path 'DAMASKER': checked out '5726269b6e72d7388020b5f69748f0c34e384584'
Cloning into 'DAZZ_DB'...
Submodule path 'DAZZ_DB': checked out '1e084112361b8d017562a00edcbd845b69bd814d'
Cloning into 'DEXTRACTOR'...
Submodule path 'DEXTRACTOR': checked out '89726800346d0bed15d98dcc577f4c7733aab4b1'
Cloning into 'FALCON'...Submodule path 'FALCON': checked out '6c147688e9505020f304924c9550a0dec605d8bc'
Cloning into 'FALCON-examples'...
Submodule path 'FALCON-examples': checked out '98d21191b761d944b5112b7aae5686ca4056e61c'
Cloning into 'FALCON-make'...
Submodule path 'FALCON-make': checked out '4d2242acf86d8e1b54b66796c66b33ee5b0e13d7'
Cloning into 'git-sym'...
Submodule path 'git-sym': checked out '483836854e1bafb6e40cf17f3a9382efe351daad'
Cloning into 'pypeFLOW'...
Submodule path 'pypeFLOW': checked out 'bdedaf2a6ae9a5b88b4aa93c808ea3d9c34cc719'
cp -f default-env.sh env.sh
bash ./FALCON-make/config-edit-user.sh
PYTHONUSERBASE=/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/fc_env
make -C ./FALCON-make/ all
make[1]: Entering directory `/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/FALCON-make'
make show
make[2]: Entering directory `/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/FALCON-make'
mkdir -p /net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/fc_env/bin
which python
/net/eichler/vol6/software/modules-sw/anaconda/2.3.0/Linux/RHEL6/x86_64/envs/python2/bin/python
echo "PYTHONUSERBASE=/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/fc_env"
PYTHONUSERBASE=/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/fc_env
python -c 'import site; print site.USER_BASE'
/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/fc_env
echo "FALCON_PIP_EDIT=--edit"
FALCON_PIP_EDIT=--edit
echo "FALCON_PIP_USER=--user"
FALCON_PIP_USER=--user
make[2]: Leaving directory `/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/FALCON-make'
make install-pip
make[2]: Entering directory `/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/FALCON-make'
python -c 'import pip; print pip' || python get-pip.py --user
<module 'pip' from '/net/eichler/vol6/software/modules-sw/anaconda/2.3.0/Linux/RHEL6/x86_64/envs/python2/lib/python2.7/site-packages/pip/__init__.pyc'>
pip install --user --upgrade pip
Collecting pip
  Using cached pip-9.0.1-py2.py3-none-any.whl
Installing collected packages: pipSuccessfully installed pip-8.1.2
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
pip install --user --upgrade setuptools # needed when --edit is used
Traceback (most recent call last):
  File "/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/fc_env/bin/pip", line 7, in <module>
    from pip import main
  File "/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/fc_env/lib/python2.7/site-packages/pip/__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/fc_env/lib/python2.7/site-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/fc_env/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
    @_call_aside
  File "/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/fc_env/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/fc_env/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3031, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/fc_env/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 651, in _build_master
    ws = cls()
  File "/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/fc_env/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/fc_env/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/fc_env/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2017, in find_on_path
    if len(os.listdir(fullpath)) == 0:
OSError: [Errno 13] Permission denied: '/net/eichler/vol6/software/modules-sw/anaconda/2.3.0/Linux/RHEL6/x86_64/envs/python2/lib/python2.7/site-packages/SQLAlchemy-1.0.15.dist-info'make[2]: *** [install-pip] Error 1
make[2]: Leaving directory `/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/FALCON-make'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/net/gs/vol1/home/dgordon/falcon/161115/FALCON-integrate/FALCON-make'
make: *** [all] Error 2
````

**Comment by pb-cdunn** [comment]
> OSError: [Errno 13] Permission denied: '/net/eichler/vol6/software/modules-sw/anaconda/2.3.0/Linux/RHEL6/x86_64/envs/python2/lib/python2.7/site-packages/SQLAlchemy-1.0.15.dist-info'make[2]: **\* [install-pip] Error 1

Ask your sysadmin to add read permission for everything under `/net/eichler/vol6/software/modules-sw/anaconda/2.3.0/Linux/RHEL6/x86_64/envs/python2/lib/python2.7/site-packages`

**Comment by dgordon562** [comment]
Wow, Chris, that was fast!  Thanks!  Will do!

**Comment by dgordon562** [comment]
Worked!!!!    Thanks!!!!
