### ISSUE TITLE
Install error 

### ISSUE THREAD

**Issue by gucascau** [PacificBiosciences/FALCON-integrate#117]
Cleaning up...
  Removing temporary dir /tmp/pip_build_xinw...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1146, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 331, in run_egg_info
    "%(Name)s==%(Version)s" % self.pkg_info())
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2583, in scan_list
    "Expected ',' or end-of-list in",line,"at",line[p:]
ValueError: ("Expected ',' or end-of-list in", u'falcon-kit==0.7+git.7a6ac0d8e8492c64733a997d72a9359e1275bb57', 'at', u'+git.7a6ac0d8e8492c64733a997d72a9359e1275bb57')

I tried to install the new version of FALCON-integrate following the easy way, but faced with the above problem. Any suggestion? Thanks

**Comment by gucascau** [comment]
Sorry, I found the answer.
$ sudo python -m pip install --upgrade --force setuptools
$ sudo python -m pip install --upgrade --force pip

**Comment by pb-cdunn** [comment]
Thank you. I've copied that suggestion into the wiki.
