### ISSUE TITLE
Install problem: Can not perform a '--user' install and No module named __future__

### ISSUE THREAD

**Issue by lamz138138** [PacificBiosciences/FALCON-integrate#121]
Hi, I tried to install the latest Falcon according to https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation as follow:
```
mkdir myVirtualenv
python virtualenv/virtualenv.py -p python2.7 myVirtualenv
unset PYTHONPATH
source myVirtualenv/bin/activate
export GIT_SYM_CACHE_DIR=~/.git-sym-cache
git clone git://github.com/PacificBiosciences/FALCON-integrate.git
cd FALCON-integrate
git checkout master
make init
source env.sh
#make config-edit-user
make -j all
make test
```

1. The line "make config-edit-user" was commented, as it would result in follow error. After commenting, it seemed Falcon was setup successfully as “shifted by 3269 (rc)” could be found and I found "p_ctg.fa" in "FALCON-examples/run/synth0/2-asm-falcon". Is there any problem in commenting this line?
```
python -c 'import pip; print pip' || python get-pip.py --user
<module 'pip' from '/data7/Falcon/myVirtualenv/lib/python2.7/site-packages/pip/__init__.pyc'>
pip install --user --upgrade pip
Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
makefile:47: recipe for target 'install-pip' failed
make[2]: *** [install-pip] Error 1
make[2]: Leaving directory '/data7/Falcon/FALCON-integrate/FALCON-make'
makefile:16: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/data7/Falcon/FALCON-integrate/FALCON-make'
makefile:19: recipe for target 'all' failed
make: *** [all] Error 2
```

2. The cluster have there calculation nodes and one console node, and SGE was used, and all files were store in one machine (/data7). After running "fc_run.py fc_run.cfg" in console node, it output follow error (I got the same error when running in local model).
```
source /data7/Falcon/myVirtualenv/bin/activate
fc_run.py fc_run.cfg

[INFO]starting job Job(jobid='P6ebae6824bed2c', cmd='/bin/bash run.sh', rundir='/data7/PacBio/falcon/demo3/0-rawreads', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q smp.q', 'job_type': 'local'})
[INFO]Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='P6ebae6824bed2c', cmd='/bin/bash run.sh', rundir='/data7/PacBio/falcon/demo3/0-rawreads', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q smp.q', 'job_type': 'local'}), lang_exe='/bin/bash'))
[INFO]sleep 0.1s
[INFO]sleep 0.2s
[ERROR]Task Node(0-rawreads) failed with exit-code=256
[INFO]recently_satisfied: set([])
[INFO]Num satisfied in this iteration: 0
[INFO]Num still unsatisfied: 1
[ERROR]Some tasks are recently_done but not satisfied: set([Node(0-rawreads)])
[ERROR]ready: set([])
submitted: set([])
Traceback (most recent call last):
  File "/data7/Falcon/myVirtualenv/bin/fc_run.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/data7/Falcon/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/data7/Falcon/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 461, in main
    main1(argv[0], args.config, args.logger)
  File "/data7/Falcon/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 136, in main1
    input_fofn_plf=input_fofn_plf,
  File "/data7/Falcon/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 195, in run
    wf.refreshTargets([rdb_build_done])
  File "/data7/Falcon/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 226, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/data7/Falcon/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 292, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads)])
```

As falcon was set up in console node, I think this problem was caused by lacking library in calculation node, so I log in one node, trying to run in local model, then it output following error. Previously, I set up  falcon 0.4.0 by adding all lack library path to PYTHONPATH in .bashrc file, I think there would be another solutions.
```
ssh smp01
source /data7/Falcon/myVirtualenv/bin/activate
fc_run.py fc_run.cfg
Traceback (most recent call last):
  File "/data7/Falcon/myVirtualenv/bin/fc_run.py", line 4, in <module>
    __import__('pkg_resources').require('falcon-kit==0.7+git.7a6ac0d8e8492c64733a997d72a9359e1275bb57')
  File "/data7/Falcon/myVirtualenv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 18, in <module>
    from __future__ import absolute_import
ImportError: No module named __future__
```

When running "pip install future" in smp01 node, it output:
```
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Traceback (most recent call last):
  File "/data7/Falcon/myVirtualenv/bin/pip", line 7, in <module>
    from pip import main
  File "/data7/Falcon/myVirtualenv/lib/python2.7/site-packages/pip/__init__.py", line 2, in <module>
    from __future__ import absolute_import
ImportError: No module named __future__

```
Any suggestion would be grateful!
Best wishes!

**Comment by lamz138138** [comment]
It seemed the setup isn't successful as I thought previously, and according to https://github.com/PacificBiosciences/FALCON-integrate/issues/60, I may solve the SGE problem by adding "-V".

**Comment by lamz138138** [comment]
I think I have the same problem as https://github.com/PacificBiosciences/FALCON/issues/504, so I close this issue.

**Comment by pb-cdunn** [comment]
If you use virtualenv, then a user-install might not work. `make config-edit` instead of `make config-edit-user`

**Comment by lamz138138** [comment]
Thanks for your reply, the software was installed successfully with your suggestion.
