### ISSUE TITLE
synth0 test failure: Timed out waiting for u'preads.1.las'

### ISSUE THREAD

**Issue by 0xaf1f** [PacificBiosciences/FALCON-integrate#122]
While updating the Debian package from 1.8.4 to 1.8.5, I noticed that the test started failing for this reason. After 1.8.6 was released, I tried again and I still get this failure.

While the Debian package has files [organized differently](https://packages.debian.org/sid/amd64/falcon/filelist), `PATH` and `PYTHONPATH` are set appropriately. The unit tests pass just fine as they did before.

Here is the stderr of the failing step:

```
+ python2.7 -m pwatcher.mains.fs_heartbeat --directory=/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001 --heartbeat-file=/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/mypwatcher/heartbeats/heartbeat-P1a5bc2afb08a38 --exit-file=/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/mypwatcher/exits/exit-P1a5bc2afb08a38 --rate=10.0 /bin/bash run.sh
Namespace(command=['/bin/bash', 'run.sh'], directory='/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001', exit_file='/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/mypwatcher/exits/exit-P1a5bc2afb08a38', heartbeat_file='/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/mypwatcher/heartbeats/heartbeat-P1a5bc2afb08a38', rate=10.0)

cwd:'/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001'
hostname=workstation
heartbeat_fn='/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/mypwatcher/heartbeats/heartbeat-P1a5bc2afb08a38'
exit_fn='/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/mypwatcher/exits/exit-P1a5bc2afb08a38'
sleep_s=10.0
before setpgid: pid=11252 pgid=10343
 after setpgid: pid=11252 pgid=11252
In cwd: /tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001, Blocking call: '/bin/bash run.sh'
cd /tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001
+ cd /tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001
bash task.sh
+ bash task.sh
2017-01-22 21:30:14,593 - root - DEBUG - Running "/usr/lib/falcon/pylib/pypeflow-1.0.0-py2.7.egg/pypeflow/do_task.py --tmpdir /tmp /tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001/task.json"
2017-01-22 21:30:14,595 - root - DEBUG - Checking existence of '/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001/task.json' with timeout=60
2017-01-22 21:30:14,595 - root - DEBUG - Loading JSON from '/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001/task.json'
2017-01-22 21:30:14,597 - root - DEBUG - {u'inputs': {u'gathered_las': u'/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/gathered-las/gathered-las.txt',
             u'scatter_fn': u'/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/merge-scatter/scattered.json'},
 u'outputs': {u'job_done': u'm_00001_done', u'merged_las': u'preads.1.las'},
 u'parameters': {u'config': {u'avoid_text_file_busy': True,
                             u'cns_concurrent_jobs': 32,
                             u'dazcon': False,
                             u'dust': False,
                             u'falcon_sense_greedy': False,
                             u'falcon_sense_option': u'--output_multi --min_idt 0.70 --min_cov 1 --max_n_read 20000 --n_core 0',
                             u'falcon_sense_skip_contained': False,
                             u'fc_ovlp_to_graph_option': u' --min_len 1',
                             u'genome_size': 5000,
                             u'input_fofn': u'input.fofn',
                             u'input_type': u'raw',
                             u'install_prefix': u'/usr',
                             u'job_queue': u'production',
                             u'job_type': u'local',
                             u'length_cutoff': -1,
                             u'length_cutoff_pr': 1,
                             u'overlap_filtering_setting': u'--max_diff 10000 --max_cov 100000 --min_cov 1 --min_len 1 --bestn 1000 --n_core 0',
                             u'ovlp_DBsplit_option': u'-a -x5 -s50',
                             u'ovlp_HPCdaligner_option': u'-v -B4 -t50 -h1 -e.99 -l1 -s1000',
                             u'ovlp_concurrent_jobs': 32,
                             u'pa_DBdust_option': u'-w128 -t2.5 -m20',
                             u'pa_DBsplit_option': u'-a -x5 -s.065536',
                             u'pa_HPCdaligner_option': u'-v -B4 -t50 -h1 -e.99 -w1 -l1 -s1000',
                             u'pa_concurrent_jobs': 32,
                             u'pa_dazcon_option': u'-j 4 -x -l 500',
                             u'pwatcher_directory': u'mypwatcher',
                             u'pwatcher_type': u'fs_based',
                             u'seed_coverage': 20.0,
                             u'sge_option': u'-pe smp 8 -q production',
                             u'sge_option_cns': u'-pe smp 8 -q production',
                             u'sge_option_da': u'-pe smp 8 -q production',
                             u'sge_option_fc': u'-pe smp 24 -q production',
                             u'sge_option_la': u'-pe smp 2 -q production',
                             u'sge_option_pda': u'-pe smp 8 -q production',
                             u'sge_option_pla': u'-pe smp 2 -q production',
                             u'skip_checks': False,
                             u'stop_all_jobs_on_failure': False,
                             u'target': u'assembly',
                             u'use_tmpdir': True},
                 u'job_id': 1,
                 u'merge_script': u'\n# Get the real path of a link, following all links (since \'readlink -f\' is not on OSX).\n# http://stackoverflow.com/questions/7665/how-to-resolve-symbolic-links-in-a-shell-script/697552\nrealpath() {\n    local r=$1; local t=$(readlink $r)\n    while [ $t ]; do\n        r=$(cd $(dirname $r) && cd $(dirname $t) && pwd -P)/$(basename $t)\n        t=$(readlink $r)\n    done\n    echo $r\n}\nrmfollow() {\n    local path=$(realpath $1)\n    rm -f "${path}"\n}\n',
                 u'sge_option': u'-pe smp 2 -q production'},
 u'python_function': u'falcon_kit.pype_tasks.task_run_las_merge'}
2017-01-22 21:30:14,597 - root - DEBUG - CD: '/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001' <- '/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001'
2017-01-22 21:30:14,597 - root - DEBUG - Checking existence of u'/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/gathered-las/gathered-las.txt' with timeout=60
2017-01-22 21:30:14,597 - root - DEBUG - Checking existence of u'/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/merge-scatter/scattered.json' with timeout=60
2017-01-22 21:30:14,617 - root - INFO - mkdir -p /tmp/root/pypetmp//tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001
2017-01-22 21:30:14,619 - root - DEBUG - CD: '/tmp/root/pypetmp//tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001' <- '/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001'
2017-01-22 21:30:14,620 - falcon_kit.pype_tasks - DEBUG - symlink '../../../../../../../../../autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/job_0000/preads.1.las' -> '/tmp/root/pypetmp/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001/preads.1.las'
2017-01-22 21:30:14,620 - pypeflow.do_support - INFO - !/bin/bash -vex /tmp/root/pypetmp/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001/rp_00001.sh
#!/bin/bash
set -vex
+ set -vex

# Get the real path of a link, following all links (since 'readlink -f' is not on OSX).
# http://stackoverflow.com/questions/7665/how-to-resolve-symbolic-links-in-a-shell-script/697552
realpath() {
    local r=$1; local t=$(readlink $r)
    while [ $t ]; do
        r=$(cd $(dirname $r) && cd $(dirname $t) && pwd -P)/$(basename $t)
        t=$(readlink $r)
    done
    echo $r
}
rmfollow() {
    local path=$(realpath $1)
    rm -f "${path}"
}

touch m_00001_done
+ touch m_00001_done
2017-01-22 21:30:14,624 - root - DEBUG - CD: '/tmp/root/pypetmp//tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001' -> '/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001'
2017-01-22 21:30:14,624 - root - INFO - rsync -av /tmp/root/pypetmp//tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001/ /tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001; rm -rf /tmp/root/pypetmp//tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001
2017-01-22 21:30:14,630 - root - DEBUG - Checking existence of u'm_00001_done' with timeout=60
2017-01-22 21:30:14,630 - root - DEBUG - Checking existence of u'preads.1.las' with timeout=60
2017-01-22 21:31:14,698 - root - DEBUG - CD: '/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001' -> '/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001'
2017-01-22 21:31:14,699 - root - CRITICAL - Error in /usr/lib/falcon/pylib/pypeflow-1.0.0-py2.7.egg/pypeflow/do_task.py with args="{'json_fn': '/tmp/autopkgtest.l2xlm9/autopkgtest_tmp/run/synth0/1-preads_ovl/m_00001/task.json',\n 'timeout': 60,\n 'tmpdir': '/tmp'}"
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/falcon/pylib/pypeflow-1.0.0-py2.7.egg/pypeflow/do_task.py", line 190, in <module>
    main()
  File "/usr/lib/falcon/pylib/pypeflow-1.0.0-py2.7.egg/pypeflow/do_task.py", line 182, in main
    run(**vars(parsed_args))
  File "/usr/lib/falcon/pylib/pypeflow-1.0.0-py2.7.egg/pypeflow/do_task.py", line 136, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/usr/lib/falcon/pylib/pypeflow-1.0.0-py2.7.egg/pypeflow/do_task.py", line 176, in run_cfg_in_tmpdir
    wait_for(fn)
  File "/usr/lib/falcon/pylib/pypeflow-1.0.0-py2.7.egg/pypeflow/do_task.py", line 92, in wait_for
    raise Exception('Timed out waiting for {!r}'.format(fn))
Exception: Timed out waiting for u'preads.1.las'

real    1m0.192s
user    0m0.108s
sys     0m0.008s
 returned: 256
```

Do you think this is a simple error where the unicode u'preads.1.las' doesn't match the plain string 'preads.1.las'? In my test chroot environment, I see

```
# find -name preads.1.las
./1-preads_ovl/m_00001/preads.1.las
./1-preads_ovl/job_0000/preads.1.las
```

**Comment by pb-cdunn** [comment]
It's (probably) not a unicode problem, but I don't have any theory yet.

Try this:
```sh
cd synth0/1-preads_ovl/m_00001
bash task.sh
```
That will re-run this step. Everything should work fine now. (In fact, it should work on a restart of fc_run anyway.)

If that works, then we have some sort of filesystem latency problem, I guess.

**Comment by pb-cdunn** [comment]
Try adding this in `main()` in `pypeflow/do_task.py`:

    locale.nl_langinfo(locale.CODESET)

If that helps, great. Please let me know. If not, then try setting `use_tmpdir = false`, since you are running in `/tmp` already. But really, I would like to know the proper solution to this problem. I have not seen it.

**Comment by 0xaf1f** [comment]
> Try this:
>
> cd synth0/1-preads_ovl/m_00001
> bash task.sh
>
> That will re-run this step. Everything should work fine now. (In fact, it should work on a restart of fc_run anyway.)
>
> If that works, then we have some sort of filesystem latency problem, I guess.

Doing this, I get the same error.

> Try adding this in main() in pypeflow/do_task.py:
>
> locale.nl_langinfo(locale.CODESET)
>
> If that helps, great. Please let me know.

No luck with this, either.

> If not, then try setting `use_tmpdir = false`, since you are running in `/tmp` already. But really, I would like to know the proper solution to this problem. I have not seen it.

It looks like this did the trick. Many thanks. The change that caused this must be something between 1.8.4 and 1.8.5.

**Comment by pb-cdunn** [comment]
bash task.sh

>> If that works, then we have some sort of filesystem latency problem, I guess.

> Doing this, I get the same error.

What? Wait a minute! Since you can reproduce at that level, this is definitely debuggable on your end. You indicated that the files exist, but that they are not being found. There *must* be a reason. If you would spend a few minutes debugging `pypeflow/do_task.py`, you could save someone else from hitting the same problem. Maybe there was a problem with the rsync, or maybe `wait_for()` was looking for the wrong filepath for some strange reason. I'd really appreciate if you manage to find the actual cause.

**Comment by 0xaf1f** [comment]
I don't know if you read my complete reply, but I said that your last suggestion had worked. So the problem seems to be about setting `use_tmpdir = true` while the job is being started from within `/tmp`.

I gave you the hint about when the problem started happening, but I've spent quite a bit of time on this problem already (it was what originally led me to report #111). I originally checked things like making sure the symlinks weren't broken, replacing the symlinks with the actual file and re-running.

I might be able to revisit it this weekend if you're still not able to reproduce the issue.

**Comment by pb-cdunn** [comment]
> I don't know if you read my complete reply, but I said that your last suggestion had worked.

I don't understand. I copied/pasted the part of your reply that said `task.sh` did *not* work. Only `use_tmpdir = false` worked, right? That's not enough info to debug it. If you have a repeatable failure at the level of `task.sh` (which uses `task.json`) locally, then you can you debug this pretty easily. The code in `do_task.py` is pretty simple. Note that you can alter `task.sh` to play with the `--tmpdir` flag directly.

```
$ python -m pypeflow.do_task -h
2017-01-24 05:29:03,730 - root - DEBUG - Running "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext/pi/pypeFLOW/pypeflow/do_task.py -h"
usage: do_task.py [-h] [--timeout TIMEOUT] [--tmpdir TMPDIR] json_fn

Given a JSON description, call a python-function.

positional arguments:
  json_fn            JSON file, as per epilog.

optional arguments:
  -h, --help         show this help message and exit
  --timeout TIMEOUT  How many seconds to wait for input files (and JSON) to
                     exist. (default: 60
  --tmpdir TMPDIR    Root directory to run in. (Sub-dir name will be based on
                     CWD.) (default: None)

$ cat 0-rawreads/task.sh
#!/bin/bash
hostname
env | sort
pwd
time python2.7 -m pypeflow.do_task --tmpdir /scratch /home/UNIXHOME/cdunn/repo/gh/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/task.json
```

> I might be able to revisit it this weekend if you're still not able to reproduce the issue.

I hope so. I cannot reproduce this.
