### ISSUE TITLE
make test fails on xenial with python 2.7.9

### ISSUE THREAD

**Issue by martinghunt** [PacificBiosciences/FALCON-integrate#126]
I'm trying to get this installed on xenial and make test is failing. Any ideas?

I ran the commands below from a new vagrant ubuntu/xenial box (`vagrant init ubuntu/xenial64 && vagrant up && vagrant ssh`):

```
sudo apt-get update
sudo apt-get install -y build-essential libssl-dev

# install python 2.7.9
wget https://www.python.org/ftp/python/2.7.9/Python-2.7.9.tgz
tar xf Python-2.7.9.tgz
cd Python-2.7.9/
./configure --prefix=/home/ubuntu/Python-2.7.9.install
make
make install
export PATH=/home/ubuntu/Python-2.7.9.install/bin/:$PATH
python -m ensurepip

# install falcon integrate
cd ~
git clone git://github.com/PacificBiosciences/FALCON-integrate.git
cd FALCON-integrate
git checkout master  # or whatever version you want
make init
source env.sh
make config-edit-user
make -j all
PYTHONUSERBASE=$(python -c 'import site; print site.USER_BASE')
export PATH=${PYTHONUSERBASE}/bin:$PATH
make test
```

make test fails. Here's the output:

```
ubuntu@ubuntu-xenial:~/FALCON-integrate$ make test
make -C ./FALCON-make/ test
make[1]: Entering directory '/home/ubuntu/FALCON-integrate/FALCON-make'
make -C /home/ubuntu/FALCON-integrate/FALCON-examples test
make[2]: Entering directory '/home/ubuntu/FALCON-integrate/FALCON-examples'
python -c 'import pypeflow.pwatcher_workflow; print pypeflow.pwatcher_workflow'
<module 'pypeflow.pwatcher_workflow' from '/home/ubuntu/FALCON-integrate/pypeFLOW/pypeflow/pwatcher_workflow.py'>
python -c 'import falcon_kit; print falcon_kit.falcon'
<CDLL '/home/ubuntu/FALCON-integrate/FALCON/ext_falcon.so', handle 2038300 at 7f169482d750>
make run-synth0
make[3]: Entering directory '/home/ubuntu/FALCON-integrate/FALCON-examples'
git-sym update run/synth0
mkdir -p /home/ubuntu/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/links
os.symlink('../.git/modules/FALCON-examples/git-sym-local/links', '/home/ubuntu/FALCON-integrate/FALCON-examples/.git-sym')
mkdir -p /home/ubuntu/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/cache
-> in dir 'run/synth0'
<- back to dir '/home/ubuntu/FALCON-integrate/FALCON-examples'
symlink: 'run/synth0/data/synth5k'
'run/synth0/data/synth5k' -> '../../../.git-sym/synth5k.2016-11-02' does not exist
-> in dir '/home/ubuntu/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/links'
-> in dir '/home/ubuntu/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/cache'
make -j  -f /home/ubuntu/FALCON-integrate/FALCON-examples/git-sym.makefile 'synth5k.2016-11-02'
make[4]: Entering directory '/home/ubuntu/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/cache'
curl -L https://downloads.pacbcloud.com/public/data/git-sym/synth5k.2016-11-02.tgz | tar xvfz -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0synth5k.2016-11-02/
synth5k.2016-11-02/subreads.dexta
synth5k.2016-11-02/synth5k.bam
100 41667  100 41667    0     0  25707      0  0:00:01  0:00:01 --:--:-- 25720
synth5k.2016-11-02/synth5k.bam.bai
synth5k.2016-11-02/synth5k.bam.pbi
synth5k.2016-11-02/ref.fasta
synth5k.2016-11-02/README
synth5k.2016-11-02/synth5k.xml
make[4]: Leaving directory '/home/ubuntu/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/cache'
<- back to dir '/home/ubuntu/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/links'
os.symlink('../cache/synth5k.2016-11-02', 'synth5k.2016-11-02')
<- back to dir '/home/ubuntu/FALCON-integrate/FALCON-examples'
git-sym show run/synth0
-> in dir 'run/synth0'
<- back to dir '/home/ubuntu/FALCON-integrate/FALCON-examples'
symlink: 'run/synth0/data/synth5k'
/ run/synth0/data/synth5k	.git-sym/synth5k.2016-11-02
git-sym check run/synth0
-> in dir 'run/synth0'
<- back to dir '/home/ubuntu/FALCON-integrate/FALCON-examples'
symlink: 'run/synth0/data/synth5k'
cd run/synth0; fc_run.py fc_run.cfg logging.ini
2017-02-13 15:14:35,454[INFO] Setup logging from file "logging.ini".
2017-02-13 15:14:35,454[INFO] fc_run started with configuration fc_run.cfg
2017-02-13 15:14:35,455[INFO]  No target specified, assuming "assembly" as target
2017-02-13 15:14:35,456[WARNING] In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/home/ubuntu/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
2017-02-13 15:14:35,457[INFO] In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/home/ubuntu/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
2017-02-13 15:14:35,459[INFO] job_type='local', job_queue='production', sge_option='-pe smp 8 -q production', use_tmpdir='/tmp', squash=True
2017-02-13 15:14:35,462[INFO] Num unsatisfied: 1, graph: 1
2017-02-13 15:14:35,462[INFO] About to submit: Node(0-rawreads/raw-fofn-abs)
2017-02-13 15:14:35,464[INFO] starting job Job(jobid='P11988417c7ecff', cmd='/bin/bash run.sh', rundir='/home/ubuntu/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs', options={'job_queue': 'production', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'})
2017-02-13 15:14:35,469[INFO] Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='P11988417c7ecff', cmd='/bin/bash run.sh', rundir='/home/ubuntu/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw-fofn-abs', options={'job_queue': 'production', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'}), lang_exe='/bin/bash'))
2017-02-13 15:14:35,471[INFO] sleep 0.1s
2017-02-13 15:14:35,572[INFO] sleep 0.2s
2017-02-13 15:14:35,774[INFO] recently_satisfied: set([Node(0-rawreads/raw-fofn-abs)])
2017-02-13 15:14:35,774[INFO] Num satisfied in this iteration: 1
2017-02-13 15:14:35,775[INFO] Num still unsatisfied: 0
2017-02-13 15:14:35,778[INFO] Num unsatisfied: 1, graph: 2
2017-02-13 15:14:35,778[INFO] About to submit: Node(0-rawreads)
2017-02-13 15:14:35,780[INFO] starting job Job(jobid='P49b18037ed8be9', cmd='/bin/bash run.sh', rundir='/home/ubuntu/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads', options={'job_queue': 'production', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'})
2017-02-13 15:14:35,787[INFO] Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='P49b18037ed8be9', cmd='/bin/bash run.sh', rundir='/home/ubuntu/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads', options={'job_queue': 'production', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'}), lang_exe='/bin/bash'))
2017-02-13 15:14:35,789[INFO] sleep 0.1s
2017-02-13 15:14:35,890[INFO] sleep 0.2s
2017-02-13 15:14:36,092[INFO] recently_satisfied: set([Node(0-rawreads)])
2017-02-13 15:14:36,093[INFO] Num satisfied in this iteration: 1
2017-02-13 15:14:36,094[INFO] Num still unsatisfied: 0
2017-02-13 15:14:36,097[INFO] Num unsatisfied: 1, graph: 3
2017-02-13 15:14:36,097[INFO] About to submit: Node(0-rawreads/daligner-scatter)
2017-02-13 15:14:36,100[INFO] starting job Job(jobid='Pf1102d82360c1c', cmd='/bin/bash run.sh', rundir='/home/ubuntu/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/daligner-scatter', options={'job_queue': 'production', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'})
2017-02-13 15:14:36,106[INFO] Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='Pf1102d82360c1c', cmd='/bin/bash run.sh', rundir='/home/ubuntu/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/daligner-scatter', options={'job_queue': 'production', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'}), lang_exe='/bin/bash'))
2017-02-13 15:14:36,108[INFO] sleep 0.1s
2017-02-13 15:14:36,210[INFO] sleep 0.2s
2017-02-13 15:14:36,412[INFO] recently_satisfied: set([Node(0-rawreads/daligner-scatter)])
2017-02-13 15:14:36,413[INFO] Num satisfied in this iteration: 1
2017-02-13 15:14:36,414[INFO] Num still unsatisfied: 0
2017-02-13 15:14:36,420[INFO] Num unsatisfied: 3, graph: 6
2017-02-13 15:14:36,421[INFO] About to submit: Node(0-rawreads/job_0001)
2017-02-13 15:14:36,422[INFO] About to submit: Node(0-rawreads/job_0000)
2017-02-13 15:14:36,425[INFO] starting job Job(jobid='P0575aeb4f70298', cmd='/bin/bash run.sh', rundir=u'/home/ubuntu/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001', options={'job_queue': 'production', 'sge_option': u'-pe smp 8 -q production', 'job_type': 'local'})
2017-02-13 15:14:36,431[INFO] Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='P0575aeb4f70298', cmd='/bin/bash run.sh', rundir=u'/home/ubuntu/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001', options={'job_queue': 'production', 'sge_option': u'-pe smp 8 -q production', 'job_type': 'local'}), lang_exe='/bin/bash'))
2017-02-13 15:14:36,432[INFO] starting job Job(jobid='Pbfd65427d9f391', cmd='/bin/bash run.sh', rundir=u'/home/ubuntu/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0000', options={'job_queue': 'production', 'sge_option': u'-pe smp 8 -q production', 'job_type': 'local'})
2017-02-13 15:14:36,440[INFO] Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='Pbfd65427d9f391', cmd='/bin/bash run.sh', rundir=u'/home/ubuntu/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0000', options={'job_queue': 'production', 'sge_option': u'-pe smp 8 -q production', 'job_type': 'local'}), lang_exe='/bin/bash'))
2017-02-13 15:14:36,442[INFO] sleep 0.1s
2017-02-13 15:14:36,543[INFO] sleep 0.2s
2017-02-13 15:14:36,746[ERROR] Task Node(0-rawreads/job_0001) failed with exit-code=256
2017-02-13 15:14:36,747[ERROR] Task Node(0-rawreads/job_0000) failed with exit-code=256
2017-02-13 15:14:36,748[INFO] recently_satisfied: set([])
2017-02-13 15:14:36,749[INFO] Num satisfied in this iteration: 0
2017-02-13 15:14:36,750[INFO] Num still unsatisfied: 3
2017-02-13 15:14:36,751[ERROR] Some tasks are recently_done but not satisfied: set([Node(0-rawreads/job_0001), Node(0-rawreads/job_0000)])
2017-02-13 15:14:36,751[ERROR] ready: set([])
submitted: set([])
Traceback (most recent call last):
  File "/home/ubuntu/FALCON-integrate/fc_env/bin/fc_run.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/home/ubuntu/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 461, in main
    main1(argv[0], args.config, args.logger)
  File "/home/ubuntu/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 136, in main1
    input_fofn_plf=input_fofn_plf,
  File "/home/ubuntu/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 234, in run
    wf.refreshTargets(exitOnFailure=exitOnFailure)
  File "/home/ubuntu/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 226, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/ubuntu/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 297, in _refreshTargets
    failures, len(unsatg)))
Exception: We had 2 failures. 3 tasks remain unsatisfied.
makefile:4: recipe for target 'run-synth0' failed
make[3]: *** [run-synth0] Error 1
make[3]: Leaving directory '/home/ubuntu/FALCON-integrate/FALCON-examples'
makefile:11: recipe for target 'test' failed
make[2]: *** [test] Error 2
make[2]: Leaving directory '/home/ubuntu/FALCON-integrate/FALCON-examples'
makefile:67: recipe for target 'test' failed
make[1]: *** [test] Error 2
make[1]: Leaving directory '/home/ubuntu/FALCON-integrate/FALCON-make'
makefile:23: recipe for target 'test' failed
make: *** [test] Error 2
ubuntu@ubuntu-xenial:~/FALCON-integrate$
```

**Comment by pb-cdunn** [comment]
It's probably something simple. Look for the the output of the failing tasks, e.g. `[ERROR] Some tasks are recently_done but not satisfied: set([Node(0-rawreads/job_0001), Node(0-rawreads/job_0000)])
`
```sh
cd /home/ubuntu/FALCON-integrate/FALCON-examples/run/synth0/data/synth5k/0-rawreads/job_0001
```
I think you will have `*.stderr` there, but if not then look at `pwatcher.dir/stderr`. (It depends on which process-watcher you used.)

**Comment by martinghunt** [comment]
Thanks, the answer was indeed in the stderr files. For the record, in case anyone else has the same issue, I needed more RAM. 4GB wasn't enough. Was fine on a machine with 64GB. The end of one of the stderr files was this on the 4GB machine:
```
`LAmerge: Out of memory (Allocating LAmerge blocks)
2017-03-21 14:42:52,117 - root - DEBUG - CD: '/tmp/ubuntu/pypetmp//home/ubuntu/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001' -> '/home/ubuntu/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001'
2017-03-21 14:42:52,117 - root - DEBUG - CD: '/home/ubuntu/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001' -> '/home/ubuntu/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001'
2017-03-21 14:42:52,118 - root - CRITICAL - Error in /home/ubuntu/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': '/home/ubuntu/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/task.json',\n 'timeout': 60,\n 'tmpdir': '/tmp'}"
Traceback (most recent call last):
  File "/home/ubuntu/Python-2.7.9.install/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/ubuntu/Python-2.7.9.install/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 190, in <module>
    main()
  File "/home/ubuntu/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 182, in main
    run(**vars(parsed_args))
  File "/home/ubuntu/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 136, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/home/ubuntu/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 160, in run_cfg_in_tmpdir
    run_python_func(func, myinputs, myoutputs, parameters)
  File "/home/ubuntu/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 125, in run_python_func
    do_support.run_bash(script_fn)
  File "/home/ubuntu/FALCON-integrate/pypeFLOW/pypeflow/do_support.py", line 51, in run_bash
    raise Exception('{} <- {!r}'.format(rc, cmd))
Exception: 256 <- '/bin/bash -vex /tmp/ubuntu/pypetmp/home/ubuntu/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/rj_0001.sh'

real	0m0.201s
user	0m0.112s
sys	0m0.028s
 returned: 256
```
