### ISSUE TITLE
Problem with https://downloads.pacbcloud.com server?

### ISSUE THREAD

**Issue by JPascualAnaya** [PacificBiosciences/FALCON-integrate#127]
Hi there, 

I was trying to install FALCON, following the easy way as in https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation

However, when running make test, it cannot complete becasue it cannot even download the data:

```
$ make test
make -C ./FALCON-make/ test
make[1]: Entering directory `/home/champi/Software/FALCON-integrate/FALCON-make'
make -C /home/champi/Software/FALCON-integrate/FALCON-examples test
make[2]: Entering directory `/home/champi/Software/FALCON-integrate/FALCON-examples'
python -c 'import pypeflow.pwatcher_workflow; print pypeflow.pwatcher_workflow'
<module 'pypeflow.pwatcher_workflow' from '/home/champi/Software/FALCON-integrate/pypeFLOW/pypeflow/pwatcher_workflow.pyc'>
python -c 'import falcon_kit; print falcon_kit.falcon'
<CDLL '/home/champi/Software/FALCON-integrate/FALCON/ext_falcon.so', handle 91e950 at 2b6677577890>
make run-synth0
make[3]: Entering directory `/home/champi/Software/FALCON-integrate/FALCON-examples'
git-sym update run/synth0
-> in dir 'run/synth0'
<- back to dir '/home/champi/Software/FALCON-integrate/FALCON-examples'
symlink: 'run/synth0/data/synth5k'
'run/synth0/data/synth5k' -> '../../../.git-sym/synth5k.2016-11-02' does not exist
-> in dir '/home/champi/Software/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/links'
-> in dir '/home/champi/Software/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/cache'
make -j  -f /home/champi/Software/FALCON-integrate/FALCON-examples/git-sym.makefile 'synth5k.2016-11-02'
make[4]: Entering directory `/home/champi/Software/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/cache'
curl -L https://downloads.pacbcloud.com/public/data/git-sym/synth5k.2016-11-02.tgz | tar xvfz -

curl: (60) Peer certificate cannot be authenticated with known CA certificates
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make[4]: *** [synth5k.2016-11-02] Error 2
make[4]: Leaving directory `/home/champi/Software/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/cache'
Traceback (most recent call last):
  File "/home/champi/Software/FALCON-integrate/fc_env/bin/git-sym", line 455, in main
    cmd_table[cmd](**args)
  File "/home/champi/Software/FALCON-integrate/fc_env/bin/git-sym", line 357, in git_sym_update
    retrieve(needed)
  File "/home/champi/Software/FALCON-integrate/fc_env/bin/git-sym", line 284, in retrieve
    retrieve_using_make(makefilename, paths)
  File "/home/champi/Software/FALCON-integrate/fc_env/bin/git-sym", line 277, in retrieve_using_make
    system(cmd)
  File "/home/champi/Software/FALCON-integrate/fc_env/bin/git-sym", line 81, in system
    raise Exception('%d <- %r' %(rc, cmd))
Exception: 512 <- "make -j  -f /home/champi/Software/FALCON-integrate/FALCON-examples/git-sym.makefile 'synth5k.2016-11-02'"

make[3]: *** [setup-synth0] Error 1
make[3]: Leaving directory `/home/champi/Software/FALCON-integrate/FALCON-examples'
make[2]: *** [test] Error 2
make[2]: Leaving directory `/home/champi/Software/FALCON-integrate/FALCON-examples'
make[1]: *** [test] Error 2
make[1]: Leaving directory `/home/champi/Software/FALCON-integrate/FALCON-make'
make: *** [test] Error 2
```

Trying to visit https://downloads.pacbcloud.com gets me a warning from Google Chrome telling that the certificate of the site finished yesterday. Is this a problem due to a firewall from my institute or is there really a problem with the PB download server?

Thanks,
Juan

**Comment by pb-cdunn** [comment]
Edit `FALCON/examples/git-sym.makefile` to add `-k` (or `--insecure`) to the curl command.

I will push a fix for this soon. I am wondering what happened though.

**Comment by pb-cdunn** [comment]
> The certificate expired on Wednesday, March 01, 2017 4:59 PM. The current time is Thursday, March 02, 2017 9:57 AM. A new cert is being issued.

I guess that's better than using `--insecure`. Should be fixed in 2 ways soon. Thanks for reporting this!
