### ISSUE TITLE
[ERROR]Some tasks are recently_done but not satisfied: set([Node(0-rawreads)])

### ISSUE THREAD

**Issue by myshu2017-03-14** [PacificBiosciences/FALCON-integrate#131]
Hi,
I recently installed FALCON on ubuntu 12.04. But when I run my subreads datas of Pacbio RS II, which format is fastq, there are some errors just as below:
```
> myshu@ubuntu-headnode:~/software_han/FALCON-integrate/myshu_test$ fc_run.py fc_run.cfg 
[INFO]Setup logging from file "None".
[INFO]fc_run started with configuration fc_run.cfg
[INFO] No target specified, assuming "assembly" as target 
/analysis/software_han/FALCON-integrate/FALCON/falcon_kit/run_support.py:351: UserWarning: Unexpected keys in input config: set(['jobqueue'])
  warnings.warn("Unexpected keys in input config: %s" %repr(unused))
[WARNING]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/analysis/software_han/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
[INFO]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/analysis/software_han/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
[INFO]job_type='local', job_queue='default', sge_option='-pe smp 8 -q production', use_tmpdir=False, squash=False
[INFO]Num unsatisfied: 0, graph: 1
[INFO]Num unsatisfied: 1, graph: 2
[INFO]About to submit: Node(0-rawreads)
[INFO]starting job Job(jobid='Pd3bf02abfb9a66', cmd='/bin/bash run.sh', rundir='/analysis/software_han/FALCON-integrate/myshu_test/0-rawreads', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'})
[INFO]Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='Pd3bf02abfb9a66', cmd='/bin/bash run.sh', rundir='/analysis/software_han/FALCON-integrate/myshu_test/0-rawreads', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', ')
[ERROR]Task Node(0-rawreads) failed with exit-code=65280
[INFO]recently_satisfied: set([])
[INFO]Num satisfied in this iteration: 0
[INFO]Num still unsatisfied: 1
[ERROR]Some tasks are recently_done but not satisfied: set([Node(0-rawreads)])
[ERROR]ready: set([])
submitted: set([])
Traceback (most recent call last):
  File "/home/myshu/.local/bin/fc_run.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/analysis/software_han/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/analysis/software_han/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 461, in main
    main1(argv[0], args.config, args.logger)
  File "/analysis/software_han/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 136, in main1
    input_fofn_plf=input_fofn_plf,
  File "/analysis/software_han/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 195, in run
    wf.refreshTargets([rdb_build_done])
  File "/analysis/software_han/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 226, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/analysis/software_han/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 292, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads)])
```
And the fc_run.cfg just as below:
```
> [General]
> job_type = local
> #list of files of the initial bas.h5 files
> input_fofn = /home/myshu/software_han/FALCON-integrate/myshu_test/input.fofn
> #input_fofn = preads.fofn
> input_type = raw
>#input_type = preads
>  #The length cutoff used for seed reads used for initial mapping
> length_cutoff = 12000
>#The length cutoff used for seed reads usef for pre-assembly
> length_cutoff_pr = 12000
> jobqueue = production
> sge_option_da = -pe smp 8 -q %(jobqueue)s
> sge_option_la = -pe smp 2 -q %(jobqueue)s
> sge_option_pda = -pe smp 8 -q %(jobqueue)s
> sge_option_pla = -pe smp 2 -q %(jobqueue)s
> sge_option_fc = -pe smp 24 -q %(jobqueue)s
> sge_option_cns = -pe smp 8 -q %(jobqueue)s
> pa_concurrent_jobs = 32
> ovlp_concurrent_jobs = 32
> pa_HPCdaligner_option =  -v -B4 -t16 -e.70 -l1000 -s1000
> ovlp_HPCdaligner_option = -v -B4 -t32 -h60 -e.96 -l500 -s1000
> pa_DBsplit_option = -x500 -s50
> ovlp_DBsplit_option = -x500 -s50
> falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6
> overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24
> 
```
And the stderr file is as below:
```
+ python2.7 -m pwatcher.mains.fs_heartbeat --directory=/analysis/software_han/FALCON-integrate/myshu_test/0-rawreads --heartbeat-file=/analysis/software_han/FALCON-integrate/myshu_test/mypwatcher/heartbeats/heartbeat-Pd3bf02abfb9a66 --exit-file=/analysis/h
Namespace(command=['/bin/bash', 'run.sh'], directory='/analysis/software_han/FALCON-integrate/myshu_test/0-rawreads', exit_file='/analysis/software_han/FALCON-integrate/myshu_test/mypwatcher/exits/exit-Pd3bf02abfb9a66', heartbeat_file='/analysis/software_)

cwd:'/analysis/software_han/FALCON-integrate/myshu_test/0-rawreads'
hostname=ubuntu-headnode
heartbeat_fn='/analysis/software_han/FALCON-integrate/myshu_test/mypwatcher/heartbeats/heartbeat-Pd3bf02abfb9a66'
exit_fn='/analysis/software_han/FALCON-integrate/myshu_test/mypwatcher/exits/exit-Pd3bf02abfb9a66'
sleep_s=10.0
before setpgid: pid=5986 pgid=5956
 after setpgid: pid=5986 pgid=5986
In cwd: /analysis/software_han/FALCON-integrate/myshu_test/0-rawreads, Blocking call: '/bin/bash run.sh'
cd /analysis/software_han/FALCON-integrate/myshu_test/0-rawreads
+ cd /analysis/software_han/FALCON-integrate/myshu_test/0-rawreads
bash task.sh
+ bash task.sh
2017-03-14 03:18:25,614 - root - DEBUG - Running "/analysis/software_han/FALCON-integrate/pypeFLOW/pypeflow/do_task.py /analysis/software_han/FALCON-integrate/myshu_test/0-rawreads/task.json"
2017-03-14 03:18:25,615 - root - DEBUG - Checking existence of '/analysis/software_han/FALCON-integrate/myshu_test/0-rawreads/task.json' with timeout=60
2017-03-14 03:18:25,615 - root - DEBUG - Loading JSON from '/analysis/software_han/FALCON-integrate/myshu_test/0-rawreads/task.json'
2017-03-14 03:18:25,616 - root - DEBUG - {u'inputs': {u'input_fofn': u'/analysis/software_han/FALCON-integrate/myshu_test/0-rawreads/raw-fofn-abs/input.fofn'},
 u'outputs': {u'length_cutoff': u'length_cutoff',
              u'raw_reads_db': u'raw_reads.db',
              u'rdb_build_done': u'rdb_build_done',
              u'run_jobs': u'run_jobs.sh'},
 u'parameters': {u'config': {u'avoid_text_file_busy': True,
                             u'cns_concurrent_jobs': 8,
                             u'dazcon': False,
                             u'dust': False,
                             u'falcon_sense_greedy': False,
                             u'falcon_sense_option': u'--output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6',
                             u'falcon_sense_skip_contained': False,
                             u'fc_ovlp_to_graph_option': u' --min_len 12000',
                             u'genome_size': 0,
                             u'input_fofn': u'/home/myshu/software_han/FALCON-integrate/myshu_test/input.fofn',
                             u'input_type': u'raw',
                             u'install_prefix': u'/usr',
                             u'job_queue': u'default',
                             u'job_type': u'local',
                             u'length_cutoff': 12000,
                             u'length_cutoff_pr': 12000,
                             u'overlap_filtering_setting': u'--max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24',
                             u'ovlp_DBsplit_option': u'-x500 -s50',
                             u'ovlp_HPCdaligner_option': u'-v -B4 -t32 -h60 -e.96 -l500 -s1000',
                             u'ovlp_concurrent_jobs': 32,
                             u'pa_DBdust_option': u'-w128 -t2.5 -m20',
                             u'pa_DBsplit_option': u'-x500 -s50',
                             u'pa_HPCdaligner_option': u'-v -B4 -t16 -e.70 -l1000 -s1000',
                             u'pa_concurrent_jobs': 32,
                             u'pa_dazcon_option': u'-j 4 -x -l 500',
                             u'pwatcher_directory': u'mypwatcher',
                             u'pwatcher_type': u'fs_based',
                             u'seed_coverage': 20,
                             u'sge_option': u'-pe smp 8 -q production',
                             u'sge_option_cns': u'-pe smp 8 -q production',
                             u'sge_option_da': u'-pe smp 8 -q production',
                             u'sge_option_fc': u'-pe smp 24 -q production',
                             u'sge_option_la': u'-pe smp 2 -q production',
                             u'sge_option_pda': u'-pe smp 8 -q production',
                             u'sge_option_pla': u'-pe smp 2 -q production',
                             u'skip_checks': False,
                             u'stop_all_jobs_on_failure': False,
                             u'target': u'assembly',
                             u'use_tmpdir': False},
                 u'config_fn': u'/analysis/software_han/FALCON-integrate/myshu_test/fc_run.cfg',
                 u'sge_option': u'-pe smp 8 -q production',
                 u'work_dir': u'/analysis/software_han/FALCON-integrate/myshu_test/0-rawreads'},
 u'python_function': u'falcon_kit.pype_tasks.task_build_rdb'}
2017-03-14 03:18:25,616 - root - DEBUG - CD: '/analysis/software_han/FALCON-integrate/myshu_test/0-rawreads' <- '/analysis/software_han/FALCON-integrate/myshu_test/0-rawreads'
2017-03-14 03:18:25,616 - root - DEBUG - Checking existence of u'/analysis/software_han/FALCON-integrate/myshu_test/0-rawreads/raw-fofn-abs/input.fofn' with timeout=60
2017-03-14 03:18:25,632 - root - DEBUG - CD: '/analysis/software_han/FALCON-integrate/myshu_test/0-rawreads' <- '/analysis/software_han/FALCON-integrate/myshu_test/0-rawreads'
2017-03-14 03:18:25,632 - pypeflow.do_support - INFO - !/bin/bash -vex /analysis/software_han/FALCON-integrate/myshu_test/0-rawreads/prepare_rdb.sh
#!/bin/bash
set -vex
+ set -vex
set -o pipefail
+ set -o pipefail
#fc_fasta2fasta < /analysis/software_han/FALCON-integrate/myshu_test/0-rawreads/raw-fofn-abs/input.fofn >| fc.fofn
while read fn; do  cat  $fn | fasta2DB -v raw_reads -i${fn##*/}; done < /analysis/software_han/FALCON-integrate/myshu_test/0-rawreads/raw-fofn-abs/input.fofn
+ read fn
+ cat /analysis/software_han/1-data/HLA-datas/pacbio-data/HLA-raw-data/processed-raw-data/Subreads-sequences/lbc1--lbc1.fastq
+ fasta2DB -v raw_reads -ilbc1--lbc1.fastq
/analysis/software_han/FALCON-integrate/myshu_test/0-rawreads/prepare_rdb.sh: line 5: fasta2DB: command not found
cat: write error: Broken pipe
2017-03-14 03:18:25,636 - root - DEBUG - CD: '/analysis/software_han/FALCON-integrate/myshu_test/0-rawreads' -> '/analysis/software_han/FALCON-integrate/myshu_test/0-rawreads'
2017-03-14 03:18:25,636 - root - DEBUG - CD: '/analysis/software_han/FALCON-integrate/myshu_test/0-rawreads' -> '/analysis/software_han/FALCON-integrate/myshu_test/0-rawreads'
2017-03-14 03:18:25,637 - root - CRITICAL - Error in /analysis/software_han/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': '/analysis/software_han/FALCON-integrate/myshu_test/0-rawreads/task.json',\n 'timeout': 60,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/analysis/software_han/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 190, in <module>
    main()
  File "/analysis/software_han/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 182, in main
    run(**vars(parsed_args))
  File "/analysis/software_han/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 136, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/analysis/software_han/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 160, in run_cfg_in_tmpdir
    run_python_func(func, myinputs, myoutputs, parameters)
  File "/analysis/software_han/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 125, in run_python_func
    do_support.run_bash(script_fn)
  File "/analysis/software_han/FALCON-integrate/pypeFLOW/pypeflow/do_support.py", line 51, in run_bash
    raise Exception('{} <- {!r}'.format(rc, cmd))
Exception: 32512 <- '/bin/bash -vex /analysis/software_han/FALCON-integrate/myshu_test/0-rawreads/prepare_rdb.sh'

real	0m0.109s
user	0m0.092s
sys	0m0.004s
 returned: 65280
```

Can anyone knows what should I do?

**Comment by pb-jchin** [comment]
`fasta2DB: command not found`
you execution environment does not have the file. Have you done the "source evn.sh" thing or use a virtualenv?

**Comment by myshu2017-03-14** [comment]
@pb-jchin yes, I have done the "source env.sh"...And I rerun the install steps as folliw:
```
git checkout master  # or whatever version you want
make init
source env.sh
make config-edit-user
make -j all
make test
```
And there is no error. But when I run fc_run.py with my data, there are errors as below:

> Traceback (most recent call last):
>   File "/home/myshu/.local/bin/fc_run.py", line 4, in <module>
>     __import__('pkg_resources').require('falcon-kit==0.7+git.7a6ac0d8e8492c64733a997d72a9359e1275bb57')
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
>     working_set.require(__requires__)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 556, in resolve
>     requirements = list(requirements)[::-1]  # set up the stack
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2507, in parse_requirements
>     line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2485, in scan_list
>     "Expected ',' or end-of-list in",line,"at",line[p:]
> ValueError: ("Expected ',' or end-of-list in", 'falcon-kit==0.7+git.7a6ac0d8e8492c64733a997d72a9359e1275bb57', 'at', '+git.7a6ac0d8e8492c64733a997d72a9359e1275bb57')

I searched in github and find that some solutions is to set the PYTYHONUSERBASE, but it seems my PYTYHONUSERBASE is Ok... I don't know what the wrong with my test?
Looking for your help. Thank you  very much.

**Comment by pb-cdunn** [comment]
Try:

    pip -v install --user --upgrade pip
    pip -v install --user --upgrade setuptools

And try again.

What version of Python are you running? And of git?

**Comment by yhsYhsYhs** [comment]
Hello, I have encounter the problem as you mentioned uppermost "Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads)])
"   
I want to ask you for your solve solution.thanks

**Comment by pb-cdunn** [comment]
When you see that message, always look at for `stderr/stdout` in the run-directory for the failed task, in this case `./0-rawreads`.

**Comment by qiracle** [comment]
Hello, I have meet same problem, how to solve the problem? Thank you !
-------
2018-04-22 22:25:50,249 - pwatcher.blocking - ERROR - Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
.....
Exception: Some tasks are recently_done but not satisfied: set([Node(1-preads_ovl/daligner-runs/j_000f)])

**Comment by pb-cdunn** [comment]
@qiracle, You would need to look into the directory `1-preads_ovl/daligner-runs/j_000f`. It's usually obvious from there.

**Comment by ViriatoII** [comment]
It's not obvious!! I've been for days reading posts always with the same problem and I can't find the solution. It doesn't help that your tutorial page is oversimplified and outdated.
