### ISSUE TITLE
Make test passed but failed to run ecoli test

### ISSUE THREAD

**Issue by EnigmaHuang** [PacificBiosciences/FALCON-integrate#133]
I installed FALCON-integrate on my VM (CentOS 7.1, 4 vCPU, 4G RAM). The installation seems to be correct because the `make test` showed that "shifted by 3269 (rc)". 

Then, I modified the `FALCON-integrate/FALCON-examples/run/ecoli/fc_run.cfg` and changed the "job_type" to "local" and executed "make run-ecoli" in the directory` FALCON-integrate/FALCON-examples`. But I got an error. The outpute is:

```shell
[enigma@cn0 ~/FALCON-integrate/FALCON-examples]$ make run-ecoli
git-sym update run/ecoli
-> in dir 'run/ecoli'
<- back to dir '/home/enigma/FALCON-integrate/FALCON-examples'
symlink: 'run/ecoli/data/ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0.subreads'
'run/ecoli/data/ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0.subreads' -> '../../../.git-sym/ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0' does not exist
-> in dir '/home/enigma/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/links'
-> in dir '/home/enigma/.git-sym-cache'
make -j  -f /home/enigma/FALCON-integrate/FALCON-examples/git-sym.makefile 'ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0'
make[1]: Entering directory `/home/enigma/.git-sym-cache'
make[1]: `ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0' is up to date.
make[1]: Leaving directory `/home/enigma/.git-sym-cache'
<- back to dir '/home/enigma/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/links'
os.symlink('/home/enigma/.git-sym-cache/ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0', 'ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0')
<- back to dir '/home/enigma/FALCON-integrate/FALCON-examples'
git-sym show run/ecoli
-> in dir 'run/ecoli'
<- back to dir '/home/enigma/FALCON-integrate/FALCON-examples'
symlink: 'run/ecoli/data/ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0.subreads'
symlink: 'run/ecoli/logging.ini'
/ run/ecoli/data/ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0.subreads	.git-sym/ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0
O run/ecoli/logging.ini	logging.ini
git-sym check run/ecoli
-> in dir 'run/ecoli'
<- back to dir '/home/enigma/FALCON-integrate/FALCON-examples'
symlink: 'run/ecoli/data/ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0.subreads'
cd run/ecoli; fc_run.py fc_run.cfg logging.ini
2017-03-21 16:12:10,681 - fc_run - INFO - Setup logging from file "logging.ini".
2017-03-21 16:12:10,682 - fc_run - INFO - fc_run started with configuration fc_run.cfg
2017-03-21 16:12:10,683 - fc_run - INFO -  No target specified, assuming "assembly" as target 
/home/enigma/FALCON-integrate/FALCON/falcon_kit/run_support.py:351: UserWarning: Unexpected keys in input config: set(['jobqueue'])
  warnings.warn("Unexpected keys in input config: %s" %repr(unused))
2017-03-21 16:12:10,684 - pypeflow.simple_pwatcher_bridge - WARNING - In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/home/enigma/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
2017-03-21 16:12:10,684 - pypeflow.simple_pwatcher_bridge - INFO - In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/home/enigma/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
2017-03-21 16:12:10,684 - pypeflow.simple_pwatcher_bridge - INFO - job_type='local', job_queue='default', sge_option='-pe smp 8 -q production', use_tmpdir=False, squash=False
2017-03-21 16:12:10,686 - pypeflow.simple_pwatcher_bridge - INFO - Num unsatisfied: 1, graph: 1
2017-03-21 16:12:10,687 - pypeflow.simple_pwatcher_bridge - INFO - About to submit: Node(0-rawreads/raw-fofn-abs)
2017-03-21 16:12:10,688 - pwatcher.fs_based - INFO - starting job Job(jobid='Pb904d2e487f477', cmd='/bin/bash run.sh', rundir='/home/enigma/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'})
2017-03-21 16:12:10,692 - pwatcher.fs_based - INFO - Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='Pb904d2e487f477', cmd='/bin/bash run.sh', rundir='/home/enigma/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'}), lang_exe='/bin/bash'))
2017-03-21 16:12:10,692 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.1s
2017-03-21 16:12:10,793 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.2s
2017-03-21 16:12:10,996 - pypeflow.simple_pwatcher_bridge - INFO - recently_satisfied: set([Node(0-rawreads/raw-fofn-abs)])
2017-03-21 16:12:10,996 - pypeflow.simple_pwatcher_bridge - INFO - Num satisfied in this iteration: 1
2017-03-21 16:12:10,996 - pypeflow.simple_pwatcher_bridge - INFO - Num still unsatisfied: 0
2017-03-21 16:12:11,002 - pypeflow.simple_pwatcher_bridge - INFO - Num unsatisfied: 1, graph: 2
2017-03-21 16:12:11,003 - pypeflow.simple_pwatcher_bridge - INFO - About to submit: Node(0-rawreads)
2017-03-21 16:12:11,007 - pwatcher.fs_based - INFO - starting job Job(jobid='P420499e651e904', cmd='/bin/bash run.sh', rundir='/home/enigma/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'})
2017-03-21 16:12:11,015 - pwatcher.fs_based - INFO - Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='P420499e651e904', cmd='/bin/bash run.sh', rundir='/home/enigma/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads', options={'job_queue': 'default', 'sge_option': '-pe smp 8 -q production', 'job_type': 'local'}), lang_exe='/bin/bash'))
2017-03-21 16:12:11,016 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.1s
2017-03-21 16:12:11,117 - pypeflow.simple_pwatcher_bridge - INFO - sleep 0.2s
2017-03-21 16:12:11,319 - pypeflow.simple_pwatcher_bridge - ERROR - Task Node(0-rawreads) failed with exit-code=256
2017-03-21 16:12:11,320 - pypeflow.simple_pwatcher_bridge - INFO - recently_satisfied: set([])
2017-03-21 16:12:11,321 - pypeflow.simple_pwatcher_bridge - INFO - Num satisfied in this iteration: 0
2017-03-21 16:12:11,321 - pypeflow.simple_pwatcher_bridge - INFO - Num still unsatisfied: 1
2017-03-21 16:12:11,321 - pypeflow.simple_pwatcher_bridge - ERROR - Some tasks are recently_done but not satisfied: set([Node(0-rawreads)])
2017-03-21 16:12:11,322 - pypeflow.simple_pwatcher_bridge - ERROR - ready: set([])
submitted: set([])
Traceback (most recent call last):
  File "/home/enigma/FALCON-integrate/fc_env/bin/fc_run.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/enigma/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/home/enigma/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 461, in main
    main1(argv[0], args.config, args.logger)
  File "/home/enigma/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 136, in main1
    input_fofn_plf=input_fofn_plf,
  File "/home/enigma/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 195, in run
    wf.refreshTargets([rdb_build_done])
  File "/home/enigma/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 226, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/enigma/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 292, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads)])
make: *** [run-ecoli] Error 1
```

I also checked `FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/pwatcher.dir/stderr`, the lines near the error message are:
```shell
 73 #!/bin/bash
 74 set -vex
 75 + set -vex
 76 set -o pipefail
 77 + set -o pipefail
 78 #fc_fasta2fasta < /home/enigma/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs/input.fofn >| fc.fofn
 79 while read fn; do  undexta -vkU -w60 -i <  $fn | fasta2DB -v raw_reads -i${fn##*/}; done < /home/enigma/FALCON-integrate/FALCON-examples/run/ecoli    /0-rawreads/raw-fofn-abs/input.fofn
 80 + read fn
 81 + undexta -vkU -w60 -i
 82 + fasta2DB -v raw_reads -isubreads.1.dexta
 83 Processing 'Standard Input' ...
 84 Adding 'subreads.1.dexta.fasta' ...
 85 undexta: System error, read failed!
 86 2017-03-22 00:12:11,163 - root - DEBUG - CD: '/home/enigma/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads' -> '/home/enigma/FALCON-integrat    e/FALCON-examples/run/ecoli/0-rawreads'
 87 2017-03-22 00:12:11,163 - root - DEBUG - CD: '/home/enigma/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads' -> '/home/enigma/FALCON-integrat    e/FALCON-examples/run/ecoli/0-rawreads'
 88 2017-03-22 00:12:11,163 - root - CRITICAL - Error in /home/enigma/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': '/home/enig    ma/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/task.json',\n 'timeout': 60,\n 'tmpdir': None}"
 89 Traceback (most recent call last):
```

Any suggestion will be appreciated.

**Comment by EnigmaHuang** [comment]
I re-installed FALCOn-integrate and tried to run ecoli test again. I noticed that my system was unable to download the 242MB data package due to my unstable network. When I run `make run-ecoli`, it seems that the job script did not re-download the data package. Is there any method to solve this problem?

**Comment by pb-cdunn** [comment]
If you are using FALCON-examples, you can run `git-sym` from the command-line. Try `git-sym update` on the test-directory. It runs rules in `git-sym.makefile` in FALCON-examples.
```make
ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0:
    curl -kL https://downloads.pacbcloud.com/public/data/git-sym/ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0.subreads.tar | tar xvf -
```
Hmm. Possibly we need to wait for a full download before starting `tar`. But you can clear existing bad data by removing files from `FALCON-example/.git-sym/ecoli.m140913_050931_42139_c100713652400000001823152404301535_s1_p0/`
and then re-run `git-sym update run/ecoli`
