### ISSUE TITLE
merge-scatter fails with CRITICAL

### ISSUE THREAD

**Issue by fbemm** [PacificBiosciences/FALCON-integrate#134]
I am trying to assemble a 0.5Gb genome and FALCON throws the following error during merge-scatter:
```py
2017-03-22 08:43:12,555 - root - CRITICAL - Error in /ebio/abt6_projects9/abt6_software/tmp/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': '/tmp/global2/fbemm/grape/vb/assembly/falcon/0-rawreads/merge-scatter/task.json',\n 'timeout': 60,\n 'tmpdir': '/tmp'}"
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/ebio/abt6_projects9/abt6_software/tmp/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 190, in <module>
    main()
  File "/ebio/abt6_projects9/abt6_software/tmp/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 182, in main
    run(**vars(parsed_args))
  File "/ebio/abt6_projects9/abt6_software/tmp/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 136, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/ebio/abt6_projects9/abt6_software/tmp/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 160, in run_cfg_in_tmpdir
    run_python_func(func, myinputs, myoutputs, parameters)
  File "/ebio/abt6_projects9/abt6_software/tmp/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 122, in run_python_func
    func(self=self)
  File "/ebio/abt6_projects9/abt6_software/tmp/FALCON-integrate/FALCON/falcon_kit/pype_tasks.py", line 293, in task_merge_scatter
    for p_id, merge_script, merged_las_fn in merge_scripts:
  File "/ebio/abt6_projects9/abt6_software/tmp/FALCON-integrate/FALCON/falcon_kit/bash.py", line 310, in scripts_merge
    assert las_fn == os.path.basename(las_files[0])
AssertionError
Command exited with non-zero status 1
0.93user 0.09system 0:01.07elapsed 96%CPU (0avgtext+0avgdata 15580maxresident)k
9inputs+0outputs (0major+5366minor)pagefaults 0swaps
```
task.json contains this:
```json
{
    "inputs": {
        "gathered_las": "/tmp/global2/fbemm/grape/vb/assembly/falcon/0-rawreads/raw-gather/gathered_las.txt",
        "run_jobs": "/tmp/global2/fbemm/grape/vb/assembly/falcon/0-rawreads/run_jobs.sh"
    },
    "outputs": {
        "scattered": "scattered.json"
    },
    "parameters": {
        "config": {
            "avoid_text_file_busy": true,
            "cns_concurrent_jobs": 32,
            "dazcon": false,
            "dust": false,
            "falcon_sense_greedy": false,
            "falcon_sense_option": "--output_multi --min_idt 0.70 --min_cov 4 --max_n_read 400 --n_core 8",
            "falcon_sense_skip_contained": false,
            "fc_ovlp_to_graph_option": " --min_len 1",
            "genome_size": 500000000,
            "input_fofn": "asm.fofn",
            "input_type": "raw",
            "install_prefix": "/usr",
            "job_queue": "long.q",
            "job_type": "sge",
            "length_cutoff": 1000,
            "length_cutoff_pr": 1,
            "overlap_filtering_setting": "--max_diff 120 --max_cov 120 --min_cov 2 --n_core 24",
            "ovlp_DBsplit_option": "-s200",
            "ovlp_HPCdaligner_option": "-v -B128  -M24 -k24 -h1250 -e.96 -l1500 -s100",
            "ovlp_concurrent_jobs": 32,
            "pa_DBdust_option": "-w128 -t2.5 -m20",
            "pa_DBsplit_option": "-s200 -x500",
            "pa_HPCdaligner_option": "-v -B128  -e0.75 -M24 -l2500 -k18 -h1250 -w8 -s100",
            "pa_concurrent_jobs": 32,
            "pa_dazcon_option": "-j 4 -x -l 500",
            "pwatcher_directory": "mypwatcher",
            "pwatcher_type": "fs_based",
            "seed_coverage": 75.0,
            "sge_option": "-cwd -V -pe parallel 4  -l h_rt=48:0:0 -l h_vmem=25G -q long.q",
            "sge_option_cns": "-cwd -V -pe parallel 8  -l h_rt=48:0:0 -l h_vmem=10G -q long.q",
            "sge_option_da": "-cwd -V -pe parallel 4  -l h_rt=48:0:0 -l h_vmem=25G -q long.q",
            "sge_option_fc": "-cwd -V -pe parallel 24 -l h_rt=48:0:0 -l h_vmem=10G -q long.q",
            "sge_option_la": "-cwd -V -pe parallel 2  -l h_rt=48:0:0 -l h_vmem=25G -q long.q",
            "sge_option_pda": "-cwd -V -pe parallel 4  -l h_rt=48:0:0 -l h_vmem=25G -q long.q",
            "sge_option_pla": "-cwd -V -pe parallel 2  -l h_rt=48:0:0 -l h_vmem=25G -q long.q",
            "skip_checks": false,
            "stop_all_jobs_on_failure": false,
            "target": "assembly",
            "use_tmpdir": "/tmp"
        },
        "db_prefix": "raw_reads"
    },
    "python_function": "falcon_kit.pype_tasks.task_merge_scatter"
}
```
Any idea what is going on?

Thanks,
F

**Comment by pb-jchin** [comment]
@fbemm what happen when you restart the jobs?

**Comment by fbemm** [comment]
I get the same error. Same happens if I invoke the task locally.

**Comment by pb-cdunn** [comment]
What commit of FALCON?

    cd FALCON
    git rev-parse HEAD

**Comment by pb-cdunn** [comment]
I think we need to push an update to FALCON-integrate. FALCON is on the latest commit, I think...
