### ISSUE TITLE
 [ERROR] in _refreshTargets   

### ISSUE THREAD

**Issue by marynias** [PacificBiosciences/FALCON-integrate#139]
My run fails at the end of the pread generation stage. I am trying to assemble reads enriched for a specific gene family, and not an entire genome.
**Log:**
```
[ERROR]Task Node(0-rawreads/report) failed with exit-code=256
[INFO]recently_satisfied: set([])
[INFO]Num satisfied in this iteration: 0
[INFO]Num still unsatisfied: 1
[ERROR]Some tasks are recently_done but not satisfied: set([Node(0-rawreads/report)])
[ERROR]ready: set([])
submitted: set([])
Traceback (most recent call last):
  File "/home/sobczm/bin/FALCON-integrate/fc_env/bin/fc_run.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/sobczm/bin/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/home/sobczm/bin/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 462, in main
    main1(argv[0], args.config, args.logger)
  File "/home/sobczm/bin/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 136, in main1
    input_fofn_plf=input_fofn_plf,
  File "/home/sobczm/bin/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 307, in run
    wf.refreshTargets(exitOnFailure=exitOnFailure)
  File "/home/sobczm/bin/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 226, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/sobczm/bin/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 297, in _refreshTargets
    failures, len(unsatg)))
Exception: We had 1 failures. 1 tasks remain unsatisfied.
```
And here is the stderror report in /0-rawreads/report/pwatcher.dir
```
+ python2.7 -m pwatcher.mains.fs_heartbeat --directory=/data/projects/sobczm/renseq/F06/0-rawreads/report --heartbeat-file=/data/projects/sobczm/renseq/F06/mypwatcher/heartbeats/heartbeat-P023a5fa7ec5109 --exit-file=/data/projects/sobczm/renseq/F06/mypwatcher/exits/exit-P023a5fa7ec5109 --rate=10.0 /bin/bash run.sh
Namespace(command=['/bin/bash', 'run.sh'], directory='/data/projects/sobczm/renseq/F06/0-rawreads/report', exit_file='/data/projects/sobczm/renseq/F06/mypwatcher/exits/exit-P023a5fa7ec5109', heartbeat_file='/data/projects/sobczm/renseq/F06/mypwatcher/heartbeats/heartbeat-P023a5fa7ec5109', rate=10.0)

cwd:'/data/projects/sobczm/renseq/F06/0-rawreads/report'
hostname=triticum.niab
heartbeat_fn='/data/projects/sobczm/renseq/F06/mypwatcher/heartbeats/heartbeat-P023a5fa7ec5109'
exit_fn='/data/projects/sobczm/renseq/F06/mypwatcher/exits/exit-P023a5fa7ec5109'
sleep_s=10.0
before setpgid: pid=104946 pgid=102663
 after setpgid: pid=104946 pgid=104946
In cwd: /data/projects/sobczm/renseq/F06/0-rawreads/report, Blocking call: '/bin/bash run.sh'
cd /data/projects/sobczm/renseq/F06/0-rawreads/report
+ cd /data/projects/sobczm/renseq/F06/0-rawreads/report
bash task.sh
+ bash task.sh
2017-04-27 12:26:04,970 - root - DEBUG - Running "/home/sobczm/bin/FALCON-integrate/pypeFLOW/pypeflow/do_task.py --tmpdir /tmp /data/projects/sobczm/renseq/F06/0-rawreads/report/task.json"
2017-04-27 12:26:04,972 - root - DEBUG - Checking existence of '/data/projects/sobczm/renseq/F06/0-rawreads/report/task.json' with timeout=60
2017-04-27 12:26:04,972 - root - DEBUG - Loading JSON from '/data/projects/sobczm/renseq/F06/0-rawreads/report/task.json'
2017-04-27 12:26:04,973 - root - DEBUG - {u'inputs': {u'length_cutoff_fn': u'/data/projects/sobczm/renseq/F06/0-rawreads/length_cutoff',
             u'preads_fofn': u'/data/projects/sobczm/renseq/F06/0-rawreads/preads/input_preads.fofn',
             u'raw_reads_db': u'/data/projects/sobczm/renseq/F06/0-rawreads/raw_reads.db'},
 u'outputs': {u'pre_assembly_report': u'pre_assembly_stats.json'},
 u'parameters': {u'avoid_text_file_busy': True,
                 u'cns_concurrent_jobs': 32,
                 u'cwd': u'/data/projects/sobczm/renseq/F06/0-rawreads/report',
                 u'da_concurrent_jobs': 32,
                 u'dazcon': False,
                 u'default_concurrent_jobs': 32,
                 u'dust': False,
                 u'falcon_sense_greedy': False,
                 u'falcon_sense_option': u'--output_multi --min_idt 0.70 --min_cov 2 --max_n_read 200 --n_core 12',
                 u'falcon_sense_skip_contained': False,
                 u'fc_concurrent_jobs': 32,
                 u'fc_ovlp_to_graph_option': u' --min_len 1000',
                 u'genome_size': 100000,
                 u'input_fofn': u'input.fofn',
                 u'input_type': u'raw',
                 u'install_prefix': u'/usr',
                 u'job_queue': u'default',
                 u'job_type': u'local',
                 u'la_concurrent_jobs': 32,
                 u'length_cutoff': -1,
                 u'length_cutoff_pr': 1000,
                 u'overlap_filtering_setting': u'--max_diff 100 --max_cov 100 --min_cov 2 --n_core 12',
                 u'ovlp_DBsplit_option': u'-s400',
                 u'ovlp_HPCdaligner_option': u'-v -B128 -M32 -h1024 -e.96 -l2400 -s100 -k18',
                 u'pa_DBdust_option': u'-w128 -t2.5 -m20',
                 u'pa_DBsplit_option': u'-a -x500 -s400',
                 u'pa_HPCdaligner_option': u'-v -B128 -M32 -e.70 -l4800 -s100 -k18 -h480 -w8',
                 u'pa_dazcon_option': u'-j 4 -x -l 500',
                 u'pda_concurrent_jobs': 32,
                 u'pla_concurrent_jobs': 32,
                 u'pwatcher_directory': u'mypwatcher',
                 u'pwatcher_type': u'fs_based',
                 u'seed_coverage': 10.0,
                 u'sge_option': u'',
                 u'sge_option_cns': u'',
                 u'sge_option_da': u'',
                 u'sge_option_fc': u'',
                 u'sge_option_la': u'',
                 u'sge_option_pda': u'',
                 u'sge_option_pla': u'',
                 u'skip_checks': False,
                 u'stop_all_jobs_on_failure': False,
                 u'target': u'assembly',
                 u'use_tmpdir': True},
 u'python_function': u'falcon_kit.pype_tasks.task_report_pre_assembly'}
2017-04-27 12:26:04,973 - root - DEBUG - CD: '/data/projects/sobczm/renseq/F06/0-rawreads/report' <- '/data/projects/sobczm/renseq/F06/0-rawreads/report'
2017-04-27 12:26:04,974 - root - DEBUG - Checking existence of u'/data/projects/sobczm/renseq/F06/0-rawreads/raw_reads.db' with timeout=60
2017-04-27 12:26:04,974 - root - DEBUG - Checking existence of u'/data/projects/sobczm/renseq/F06/0-rawreads/length_cutoff' with timeout=60
2017-04-27 12:26:04,974 - root - DEBUG - Checking existence of u'/data/projects/sobczm/renseq/F06/0-rawreads/preads/input_preads.fofn' with timeout=60
2017-04-27 12:26:04,991 - root - INFO - mkdir -p /tmp/sobczm/pypetmp//data/projects/sobczm/renseq/F06/0-rawreads/report
2017-04-27 12:26:04,995 - root - DEBUG - CD: '/tmp/sobczm/pypetmp//data/projects/sobczm/renseq/F06/0-rawreads/report' <- '/data/projects/sobczm/renseq/F06/0-rawreads/report'
2017-04-27 12:26:04,995 - falcon_kit.run_support - INFO - length_cutoff=27665 from u'/data/projects/sobczm/renseq/F06/0-rawreads/length_cutoff'
2017-04-27 12:26:04,995 - falcon_kit.pype_tasks - INFO - Report inputs: {'job_done': '/tmp/sobczm/pypetmp/data/projects/sobczm/renseq/F06/0-rawreads/report/report_pa_done', 'length_cutoff': 27665, 'i_preads_fofn_fn': u'/data/projects/sobczm/renseq/F06/0-rawreads/preads/input_preads.fofn', 'genome_length': 100000, 'script_fn': '/tmp/sobczm/pypetmp/data/projects/sobczm/renseq/F06/0-rawreads/report/run_report_pre_assembly.sh', 'o_json_fn': u'pre_assembly_stats.json', 'i_raw_reads_db_fn': u'/data/projects/sobczm/renseq/F06/0-rawreads/raw_reads.db'}
2017-04-27 12:26:04,996 - pypeflow.do_support - INFO - !/bin/bash -vex /tmp/sobczm/pypetmp/data/projects/sobczm/renseq/F06/0-rawreads/report/run_report_pre_assembly.sh
#!/bin/bash
set -vex
+ set -vex
python -m falcon_kit.mains.report_pre_assembly --genome-length 100000 --length-cutoff 27665 --db /data/projects/sobczm/renseq/F06/0-rawreads/raw_reads.db --preads-fofn /data/projects/sobczm/renseq/F06/0-rawreads/preads/input_preads.fofn --out pre_assembly_stats.json
+ python -m falcon_kit.mains.report_pre_assembly --genome-length 100000 --length-cutoff 27665 --db /data/projects/sobczm/renseq/F06/0-rawreads/raw_reads.db --preads-fofn /data/projects/sobczm/renseq/F06/0-rawreads/preads/input_preads.fofn --out pre_assembly_stats.json
[104960]$ perl -e 'while (<>) { if ( m{>[^/]+/(\d+)\d/} ) { $id{$1}++; } }; while (my ($k, $v) = each %id) { $counts{$v}++; }; while (my ($k, $v) = each %counts) { print "$v $k
"; };' /data/projects/sobczm/renseq/F06/0-rawreads/preads/cns_00001/cns_00001.fasta /data/projects/sobczm/renseq/F06/0-rawreads/preads/cns_00002/cns_00002.fasta /data/projects/sobczm/renseq/F06/0-rawreads/preads/cns_00003/cns_00003.fasta /data/projects/sobczm/renseq/F06/0-rawreads/preads/cns_00004/cns_00004.fasta >
[104960]WARNING: 'perl -e \'while (<>) { if ( m{>[^/]+/(\\d+)\\d/} ) { $id{$1}++; } }; while (my ($k, $v) = each %id) { $counts{$v}++; }; while (my ($k, $v) = each %counts) { print "$v $k\n"; };\' /data/projects/sobczm/renseq/F06/0-rawreads/preads/cns_00001/cns_00001.fasta /data/projects/sobczm/renseq/F06/0-rawreads/preads/cns_00002/cns_00002.fasta /data/projects/sobczm/renseq/F06/0-rawreads/preads/cns_00003/cns_00003.fasta /data/projects/sobczm/renseq/F06/0-rawreads/preads/cns_00004/cns_00004.fasta' failed to produce any output.
ERROR:falcon_kit.stats_preassembly:Using arbitrary fragmentation metric: -1.0
Traceback (most recent call last):
  File "/home/sobczm/bin/FALCON-integrate/FALCON/falcon_kit/stats_preassembly.py", line 206, in calc_dict
    frag = metric_fragmentation(i_preads_fofn_fn)
  File "/home/sobczm/bin/FALCON-integrate/FALCON/falcon_kit/stats_preassembly.py", line 124, in metric_fragmentation
    return functional.calc_metric_fragmentation(counts)
  File "/home/sobczm/bin/FALCON-integrate/FALCON/falcon_kit/functional.py", line 363, in calc_metric_fragmentation
    avg = weighted_average(cols)
  File "/home/sobczm/bin/FALCON-integrate/FALCON/falcon_kit/functional.py", line 307, in weighted_average
    return sum(w*v for (w,v) in cols) / sum(w for (w,v) in cols)
ZeroDivisionError: division by zero
[104960]$ perl -e 'while (<>) { if ( m{>[^/]+/0*(\d+)\d/(\d+)_(\d+)} ) { $lengths{(1 + $1)} += ($3 - $2); } }; while (my ($k, $v) = each %lengths) { print "$k $v
"; };' /data/projects/sobczm/renseq/F06/0-rawreads/preads/cns_00001/cns_00001.fasta /data/projects/sobczm/renseq/F06/0-rawreads/preads/cns_00002/cns_00002.fasta /data/projects/sobczm/renseq/F06/0-rawreads/preads/cns_00003/cns_00003.fasta /data/projects/sobczm/renseq/F06/0-rawreads/preads/cns_00004/cns_00004.fasta >
[104960]WARNING: 'perl -e \'while (<>) { if ( m{>[^/]+/0*(\\d+)\\d/(\\d+)_(\\d+)} ) { $lengths{(1 + $1)} += ($3 - $2); } }; while (my ($k, $v) = each %lengths) { print "$k $v\n"; };\' /data/projects/sobczm/renseq/F06/0-rawreads/preads/cns_00001/cns_00001.fasta /data/projects/sobczm/renseq/F06/0-rawreads/preads/cns_00002/cns_00002.fasta /data/projects/sobczm/renseq/F06/0-rawreads/preads/cns_00003/cns_00003.fasta /data/projects/sobczm/renseq/F06/0-rawreads/preads/cns_00004/cns_00004.fasta' failed to produce any output.
[104960]$ DBdump -rh /data/projects/sobczm/renseq/F06/0-rawreads/raw_reads.db >
ERROR:falcon_kit.stats_preassembly:Using arbitrary truncation metric: -1.0
Traceback (most recent call last):
  File "/home/sobczm/bin/FALCON-integrate/FALCON/falcon_kit/stats_preassembly.py", line 211, in calc_dict
    trunc = metric_truncation(i_raw_reads_db_fn, i_preads_fofn_fn)
  File "/home/sobczm/bin/FALCON-integrate/FALCON/falcon_kit/stats_preassembly.py", line 134, in metric_truncation
    return functional.calc_metric_truncation(dbdump_output, length_pairs_output)
  File "/home/sobczm/bin/FALCON-integrate/FALCON/falcon_kit/functional.py", line 371, in calc_metric_truncation
    avg = -average_difference(pread_lengths, orig_lengths)
  File "/home/sobczm/bin/FALCON-integrate/FALCON/falcon_kit/functional.py", line 358, in average_difference
    return total_diff / len(dictA)
ZeroDivisionError: float division by zero
[104960]$ DBdump -h /data/projects/sobczm/renseq/F06/0-rawreads/raw_reads.db >
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sobczm/bin/FALCON-integrate/FALCON/falcon_kit/mains/report_pre_assembly.py", line 46, in <module>
    main()
  File "/home/sobczm/bin/FALCON-integrate/FALCON/falcon_kit/mains/report_pre_assembly.py", line 40, in main
    do_report(**vars(ARGS))
  File "/home/sobczm/bin/FALCON-integrate/FALCON/falcon_kit/mains/report_pre_assembly.py", line 16, in do_report
    report_dict = stats_preassembly.calc_dict(**kwds)
  File "/home/sobczm/bin/FALCON-integrate/FALCON/falcon_kit/stats_preassembly.py", line 223, in calc_dict
    stats_preads = stats_from_sorted_readlengths(preads)
  File "/home/sobczm/bin/FALCON-integrate/FALCON/falcon_kit/stats_preassembly.py", line 92, in stats_from_sorted_readlengths
    p95 = percentile(read_lens, 0.95)
  File "/home/sobczm/bin/FALCON-integrate/FALCON/falcon_kit/stats_preassembly.py", line 86, in percentile
    return read_lens[int(len(read_lens)*p)]
IndexError: list index out of range
2017-04-27 12:26:11,071 - root - DEBUG - CD: '/tmp/sobczm/pypetmp//data/projects/sobczm/renseq/F06/0-rawreads/report' -> '/data/projects/sobczm/renseq/F06/0-rawreads/report'
2017-04-27 12:26:11,072 - root - DEBUG - CD: '/data/projects/sobczm/renseq/F06/0-rawreads/report' -> '/data/projects/sobczm/renseq/F06/0-rawreads/report'
2017-04-27 12:26:11,072 - root - CRITICAL - Error in /home/sobczm/bin/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': '/data/projects/sobczm/renseq/F06/0-rawreads/report/task.json',\n 'timeout': 60,\n 'tmpdir': '/tmp'}"
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sobczm/bin/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 190, in <module>
    main()
  File "/home/sobczm/bin/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 182, in main
    run(**vars(parsed_args))
  File "/home/sobczm/bin/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 136, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/home/sobczm/bin/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 160, in run_cfg_in_tmpdir
    run_python_func(func, myinputs, myoutputs, parameters)
  File "/home/sobczm/bin/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 125, in run_python_func
    do_support.run_bash(script_fn)
  File "/home/sobczm/bin/FALCON-integrate/pypeFLOW/pypeflow/do_support.py", line 51, in run_bash
    raise Exception('{} <- {!r}'.format(rc, cmd))
Exception: 256 <- '/bin/bash -vex /tmp/sobczm/pypetmp/data/projects/sobczm/renseq/F06/0-rawreads/report/run_report_pre_assembly.sh'

real	0m6.190s
user	0m5.848s
sys	0m0.496s
 returned: 256
```

**Comment by pb-cdunn** [comment]
That's not a great error message, but it simply means that your pre-assembly failed to find any seed reads. You would need to look into earlier directories and maybe re-run **daligner** manually based on the scripts there. Unfortunately, this is difficult to debug remotely.
