### ISSUE TITLE
LAmerge: Cannot open ./L1.14.78.las for 'r'

### ISSUE THREAD

**Issue by Chenghong412** [PacificBiosciences/FALCON-integrate#148]
Hi developers,
    I have finished the dalinger, LAsort , error occurs during the merge process. The detailed information in stderr file is:
###
LAmerge: Cannot open ./L1.14.78.las for 'r'
2017-08-06 21:10:54,011 - root - DEBUG - CD: '/mnt/wangwen/chenghong/falcon/0-rawreads/m_00014' -> '/mnt/wangwen/chenghong/falcon/0-rawreads/m_00014'
2017-08-06 21:10:54,423 - root - DEBUG - CD: '/mnt/wangwen/chenghong/falcon/0-rawreads/m_00014' -> '/mnt/wangwen/chenghong/falcon/0-rawreads/m_00014'
2017-08-06 21:10:54,424 - root - CRITICAL - Error in /home/tibet_loach/bio/test/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': '/mnt/wangwen/chenghong/falcon/0-rawreads/m_00014/task.json',\n 'timeout': 60,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/home/tibet_loach/bio/Anacoda/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/tibet_loach/bio/Anacoda/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tibet_loach/bio/test/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 166, in <module>
    main()
  File "/home/tibet_loach/bio/test/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 158, in main
    run(**vars(parsed_args))
  File "/home/tibet_loach/bio/test/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 112, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/home/tibet_loach/bio/test/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 136, in run_cfg_in_tmpdir
    run_python_func(func, myinputs, myoutputs, parameters)
  File "/home/tibet_loach/bio/test/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 101, in run_python_func
    do_support.run_bash(script_fn)
  File "/home/tibet_loach/bio/test/FALCON-integrate/pypeFLOW/pypeflow/do_support.py", line 51, in run_bash
    raise Exception('{} <- {!r}'.format(rc, cmd))
Exception: 256 <- '/bin/bash -vex /mnt/wangwen/chenghong/falcon/0-rawreads/m_00014/rp_00014.sh'
###
  I checked the folder, but can not fint the file named L1.14.78.las . I want to know what can I do to solve this problem. Thank you !

**Comment by pb-cdunn** [comment]
Weird filesystem problem? Dunno.
