### ISSUE TITLE
Falcon test run is failed 

### ISSUE THREAD

**Issue by madhubioinfo** [PacificBiosciences/FALCON-integrate#149]
After installing the falcon i tried the running the test run with ecoli it was failed and this is the error i got

2017-08-25 16:50:47,462 - fc_run - INFO - Setup logging from file "None".
2017-08-25 16:50:47,462 - fc_run - INFO - fc_run started with configuration fc_run.cfg
2017-08-25 16:50:47,463 - fc_run - INFO -  No target specified, assuming "assembly" as target 
2017-08-25 16:50:47,463 - pypeflow.simple_pwatcher_bridge - WARNING - In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/usr/local/source/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
2017-08-25 16:50:47,463 - pypeflow.simple_pwatcher_bridge - INFO - In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/usr/local/source/FALCON-integrate/pypeFLOW/pwatcher/fs_based.pyc'>
2017-08-25 16:50:47,463 - pypeflow.simple_pwatcher_bridge - INFO - job_type='local', job_queue='', sge_option='', use_tmpdir=False, squash=False
2017-08-25 16:50:47,463 - pypeflow.simple_pwatcher_bridge - DEBUG - Created PypeTask('0-rawreads/raw-fofn-abs', '/usr/local/source/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs', "{'o_fofn': PLF('0-rawreads/raw-fofn-abs/input.fofn', None)}", "{'i_fofn': PLF('input.fofn', None)}")
2017-08-25 16:50:47,464 - pypeflow.simple_pwatcher_bridge - DEBUG - Added PRODUCERS['0-rawreads/raw-fofn-abs'] = PypeTask('0-rawreads/raw-fofn-abs', '/usr/local/source/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs', "{'o_fofn': PLF('0-rawreads/raw-fofn-abs/input.fofn', None)}", "{'i_fofn': PLF('input.fofn', None)}")
2017-08-25 16:50:47,464 - pypeflow.simple_pwatcher_bridge - DEBUG - Built PypeTask('0-rawreads/raw-fofn-abs', '/usr/local/source/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs', "{'o_fofn': PLF('input.fofn', '0-rawreads/raw-fofn-abs')}", "{'i_fofn': PLF('input.fofn', None)}")
2017-08-25 16:50:47,464 - pypeflow.simple_pwatcher_bridge - DEBUG - New Node(0-rawreads/raw-fofn-abs) needs set([])
2017-08-25 16:50:47,464 - pypeflow.simple_pwatcher_bridge - INFO - Num unsatisfied: 1, graph: 1
2017-08-25 16:50:47,464 - pypeflow.simple_pwatcher_bridge - INFO - About to submit: Node(0-rawreads/raw-fofn-abs)
2017-08-25 16:50:47,464 - pypeflow.simple_pwatcher_bridge - DEBUG - enque nodes:
set([Node(0-rawreads/raw-fofn-abs)])
2017-08-25 16:50:47,465 - pypeflow.simple_pwatcher_bridge - DEBUG - In rundir='/usr/local/source/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs', sge_option=None, __sge_option=''
2017-08-25 16:50:47,465 - pwatcher.fs_based - DEBUG - run(jobids=<1>, job_type=local, job_queue=)
2017-08-25 16:50:47,465 - pwatcher.fs_based - DEBUG - jobs:
{'P6c88d42f4ece16': Job(jobid='P6c88d42f4ece16', cmd='/bin/bash run.sh', rundir='/usr/local/source/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs', options={'job_queue': '', 'sge_option': '', 'job_type': 'local'})}
2017-08-25 16:50:47,465 - pwatcher.fs_based - INFO - starting job Job(jobid='P6c88d42f4ece16', cmd='/bin/bash run.sh', rundir='/usr/local/source/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs', options={'job_queue': '', 'sge_option': '', 'job_type': 'local'})
2017-08-25 16:50:47,465 - pwatcher.fs_based - DEBUG - Wrapped "python2.7 -m pwatcher.mains.fs_heartbeat --directory=/usr/local/source/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs --heartbeat-file=/usr/local/source/FALCON-integrate/FALCON-examples/run/ecoli/mypwatcher/heartbeats/heartbeat-P6c88d42f4ece16 --exit-file=/usr/local/source/FALCON-integrate/FALCON-examples/run/ecoli/mypwatcher/exits/exit-P6c88d42f4ece16 --rate=10.0 /bin/bash run.sh || echo 99 >| /usr/local/source/FALCON-integrate/FALCON-examples/run/ecoli/mypwatcher/exits/exit-P6c88d42f4ece16"
2017-08-25 16:50:47,465 - pwatcher.fs_based - DEBUG - Writing wrapper "/usr/local/source/FALCON-integrate/FALCON-examples/run/ecoli/mypwatcher/wrappers/run-P6c88d42f4ece16.bash"
2017-08-25 16:50:47,466 - pwatcher.fs_based - DEBUG - CD: '/usr/local/source/FALCON-integrate/FALCON-examples/run/ecoli/mypwatcher/jobs/P6c88d42f4ece16' <- '/usr/local/source/FALCON-integrate/FALCON-examples/run/ecoli'
2017-08-25 16:50:47,466 - pwatcher.fs_based - DEBUG - dir: '/usr/local/source/FALCON-integrate/FALCON-examples/run/ecoli/mypwatcher/jobs/P6c88d42f4ece16'
call: '/bin/bash /usr/local/source/FALCON-integrate/FALCON-examples/run/ecoli/mypwatcher/wrappers/run-P6c88d42f4ece16.bash 1>|stdout 2>|stderr & '
2017-08-25 16:50:47,469 - pwatcher.fs_based - DEBUG - pid=26768 pgid=26768 sub-pid=26772
2017-08-25 16:50:47,469 - pwatcher.fs_based - DEBUG - CD: '/usr/local/source/FALCON-integrate/FALCON-examples/run/ecoli/mypwatcher/jobs/P6c88d42f4ece16' -> '/usr/local/source/FALCON-integrate/FALCON-examples/run/ecoli'
2017-08-25 16:50:47,469 - pwatcher.fs_based - INFO - Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='P6c88d42f4ece16', cmd='/bin/bash run.sh', rundir='/usr/local/source/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/raw-fofn-abs', options={'job_queue': '', 'sge_option': '', 'job_type': 'local'}), lang_exe='/bin/bash'))
2017-08-25 16:50:47,470 - pypeflow.simple_pwatcher_bridge - DEBUG - Result of watcher.run()={'submitted': ['P6c88d42f4ece16']}
2017-08-25 16:50:47,470 - pypeflow.simple_pwatcher_bridge - DEBUG - N in queue: 1 (max_jobs=8)
2017-08-25 16:50:47,470 - pwatcher.fs_based - DEBUG - query(which='list', jobids=<1>)
2017-08-25 16:50:47,470 - pwatcher.fs_based - DEBUG - Unable to remove heartbeat '/usr/local/source/FALCON-integrate/FALCON-examples/run/ecoli/mypwatcher/heartbeats/heartbeat-P6c88d42f4ece16' when sentinal was found in exit-sentinels listdir.
Traceback (most recent call last):
  File "/usr/local/source/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 565, in get_status
OSError: [Errno 2] No such file or directory: '/usr/local/source/FALCON-integrate/FALCON-examples/run/ecoli/mypwatcher/heartbeats/heartbeat-P6c88d42f4ece16'

2017-08-25 16:50:47,470 - pwatcher.fs_based - DEBUG - Status EXIT 99 for heartbeat:heartbeat-P6c88d42f4ece16
2017-08-25 16:50:47,470 - pypeflow.simple_pwatcher_bridge - ERROR - Task Node(0-rawreads/raw-fofn-abs) failed with exit-code=99
2017-08-25 16:50:47,470 - pypeflow.simple_pwatcher_bridge - DEBUG - recently_done: [(Node(0-rawreads/raw-fofn-abs), False)]
2017-08-25 16:50:47,470 - pypeflow.simple_pwatcher_bridge - DEBUG - Num done in this iteration: 1
2017-08-25 16:50:47,470 - pypeflow.simple_pwatcher_bridge - INFO - recently_satisfied: set([])
2017-08-25 16:50:47,470 - pypeflow.simple_pwatcher_bridge - INFO - Num satisfied in this iteration: 0
2017-08-25 16:50:47,470 - pypeflow.simple_pwatcher_bridge - INFO - Num still unsatisfied: 1
2017-08-25 16:50:47,471 - pypeflow.simple_pwatcher_bridge - ERROR - Some tasks are recently_done but not satisfied: set([Node(0-rawreads/raw-fofn-abs)])
2017-08-25 16:50:47,471 - pypeflow.simple_pwatcher_bridge - ERROR - ready: set([])
submitted: set([])
2017-08-25 16:50:47,471 - pwatcher.fs_based - DEBUG - delete(which='known', jobids=<0>)
2017-08-25 16:50:47,471 - pwatcher.fs_based - DEBUG - Deleting jobs for jobids from known ([])
2017-08-25 16:50:47,471 - pwatcher.fs_based - DEBUG - Failed to kill job for heartbeat 'heartbeat-P6c88d42f4ece16': IOError(2, 'No such file or directory')
2017-08-25 16:50:47,471 - pwatcher.fs_based - DEBUG - Cannot remove heartbeat: OSError(2, 'No such file or directory')
2017-08-25 16:50:47,471 - pypeflow.simple_pwatcher_bridge - DEBUG - In notifyTerminate(), result of delete:None

**Comment by gconcepcion** [comment]
There is a failure in the first step of the pipeline `raw-fofn-abs`

Please provide `0-rawreads/raw-fofn-abs/pwatcher.dir/stderr` for further troubleshooting.

**Comment by madhubioinfo** [comment]
python2.7 -m pwatcher.mains.fs_heartbeat --directory=/usr/local/source/FALCON-integrate/0-rawreads/raw-fofn-abs --heartbeat-file=/usr/local/source/FALCON-integrate/mypwatcher/heartbeats/heartbeat-P033301522eff24 --exit-file=/usr/local/source/FALCON-integrate/mypwatcher/exits/exit-P033301522eff24 --rate=10.0 /bin/bash run.sh
/usr/bin/python2.7: No module named pwatcher.mains.fs_heartbeat
+ echo 99

**Comment by gconcepcion** [comment]
There is a problem with your installation, the python executable is unable to find the FALCON environment. What installation instructions did you follow?

I recommend following these directions to setup your FALCON environment:
http://pb-falcon.readthedocs.io/en/latest/quick_start.html

**Comment by madhubioinfo** [comment]
Hai 
I followed the instruction and when its installing  and did this bash -ex install_unzip.sh /usr/local/source
+ ROOT=/usr/local/source
+ SRC=/usr/local/source/src
+ VENV_BASE=/usr/local/source/fc_env
++ date +%y%m%d
+ SLUG=170830
+ VENV=/usr/local/source/fc_env_170830
+ FALCON_PATH=/usr/local/source/src/FALCON-integrate
+ FALCON_REPO=https://github.com/PacificBiosciences/FALCON-integrate.git
+ DL_CLOUD=https://downloads.pacbcloud.com/public/falcon/
+ UNZIP_TARBALL=falcon-2017.06.28-18.01-py2.7-ucs4.tar.gz
+ '[' '!' -d /usr/local/source ']'
+ '[' '!' -d /usr/local/source/src ']'
+ '[' -d /usr/local/source/fc_env_170830 ']'
+ '[' -d /usr/local/source/src/FALCON-integrate ']'
+ echo 'Removing old FALCON-integrate repo'
Removing old FALCON-integrate repo
+ rm -rf /usr/local/source/src/FALCON-integrate
+ '[' -L /usr/local/source/fc_env ']'
+ virtualenv --no-site-packages /usr/local/source/fc_env_170830
New python executable in /usr/local/source/fc_env_170830/bin/python
Installing setuptools, pip, wheel...done.
+ echo 'export LD_LIBRARY_PATH=/usr/local/source/fc_env_170830/lib:${LD_LIBRARY_                                                                                        PATH}'
+ source /usr/local/source/fc_env_170830/bin/activate
++ deactivate nondestructive
++ unset -f pydoc
++ '[' -z '' ']'
++ '[' -z '' ']'
++ '[' -n /bin/bash ']'
++ hash -r
++ '[' -z '' ']'
++ unset VIRTUAL_ENV
++ '[' '!' nondestructive = nondestructive ']'
++ VIRTUAL_ENV=/usr/local/source/fc_env_170830
++ export VIRTUAL_ENV
++ _OLD_VIRTUAL_PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bi                                                                                        n:/usr/games:/usr/local/games
++ PATH=/usr/local/source/fc_env_170830/bin:/usr/local/sbin:/usr/local/bin:/usr/                                                                                        sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
++ export PATH
++ '[' -z '' ']'
++ '[' -z '' ']'
++ _OLD_VIRTUAL_PS1=
++ '[' x '!=' x ']'
+++ basename /usr/local/source/fc_env_170830
++ PS1='(fc_env_170830) '
++ export PS1
++ alias pydoc
++ '[' -n /bin/bash ']'
++ hash -r
++ export LD_LIBRARY_PATH=/usr/local/source/fc_env_170830/lib:
++ LD_LIBRARY_PATH=/usr/local/source/fc_env_170830/lib:
+ cd /usr/local/source/src
+ git clone https://github.com/PacificBiosciences/FALCON-integrate.git
Cloning into 'FALCON-integrate'...
remote: Counting objects: 323, done.
remote: Total 323 (delta 0), reused 0 (delta 0), pack-reused 323
Receiving objects: 100% (323/323), 58.65 KiB | 56.00 KiB/s, done.
Resolving deltas: 100% (153/153), done.
Checking connectivity... done.
+ cd /usr/local/source/src/FALCON-integrate
+ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
+ git submodule update --init
Submodule 'DALIGNER' (https://github.com/PacificBiosciences/DALIGNER.git) regist                                                                                        ered for path 'DALIGNER'
Submodule 'DAMASKER' (https://github.com/PacificBiosciences/DAMASKER) registered                                                                                         for path 'DAMASKER'
Submodule 'DAZZ_DB' (https://github.com/PacificBiosciences/DAZZ_DB.git) register                                                                                        ed for path 'DAZZ_DB'
Submodule 'DEXTRACTOR' (https://github.com/PacificBiosciences/DEXTRACTOR) regist                                                                                        ered for path 'DEXTRACTOR'
Submodule 'FALCON' (https://github.com/PacificBiosciences/FALCON.git) registered                                                                                         for path 'FALCON'
Submodule 'FALCON-examples' (git://github.com/pb-cdunn/FALCON-examples.git) regi                                                                                        stered for path 'FALCON-examples'
Submodule 'FALCON-make' (git://github.com/pb-cdunn/FALCON-make.git) registered f                                                                                        or path 'FALCON-make'
Submodule 'git-sym' (git://github.com/cdunn2001/git-sym.git) registered for path                                                                                         'git-sym'
Submodule 'pypeFLOW' (https://github.com/PacificBiosciences/pypeFLOW.git) regist                                                                                        ered for path 'pypeFLOW'
Cloning into 'DALIGNER'...
remote: Counting objects: 764, done.
remote: Total 764 (delta 0), reused 0 (delta 0), pack-reused 764
Receiving objects: 100% (764/764), 743.77 KiB | 137.00 KiB/s, done.
Resolving deltas: 100% (512/512), done.
Checking connectivity... done.
Submodule path 'DALIGNER': checked out '0fe5240d2cc6b55bf9e04465b700b76110749c9d                                                                                        '
Cloning into 'DAMASKER'...
remote: Counting objects: 188, done.
remote: Total 188 (delta 0), reused 0 (delta 0), pack-reused 188
Receiving objects: 100% (188/188), 139.77 KiB | 0 bytes/s, done.
Resolving deltas: 100% (119/119), done.
Checking connectivity... done.
Submodule path 'DAMASKER': checked out '144244b77d52cb785cb1b3b8ae3ab6f3f0c63264                                                                                        '
Cloning into 'DAZZ_DB'...
remote: Counting objects: 600, done.
remote: Total 600 (delta 0), reused 0 (delta 0), pack-reused 600
Receiving objects: 100% (600/600), 480.84 KiB | 183.00 KiB/s, done.
Resolving deltas: 100% (408/408), done.
Checking connectivity... done.
Submodule path 'DAZZ_DB': checked out 'f29d27d51f460563481cd227d17f4bdc5e288365'
Cloning into 'DEXTRACTOR'...
remote: Counting objects: 221, done.
remote: Total 221 (delta 0), reused 0 (delta 0), pack-reused 221
Receiving objects: 100% (221/221), 197.58 KiB | 188.00 KiB/s, done.
Resolving deltas: 100% (150/150), done.
Checking connectivity... done.
Submodule path 'DEXTRACTOR': checked out '89726800346d0bed15d98dcc577f4c7733aab4                                                                                        b1'
Cloning into 'FALCON'...
remote: Counting objects: 4126, done.
remote: Total 4126 (delta 0), reused 0 (delta 0), pack-reused 4126
Receiving objects: 100% (4126/4126), 1.41 MiB | 632.00 KiB/s, done.
Resolving deltas: 100% (2928/2928), done.
Checking connectivity... done.
Submodule path 'FALCON': checked out '86cec6157291679095ea6080b0cde6561eccc041'
Cloning into 'FALCON-examples'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=Connection timed out
github.com[1: 192.30.253.113]: errno=Connection timed out

fatal: clone of 'git://github.com/pb-cdunn/FALCON-examples.git' into submodule p                                                                                        ath 'FALCON-examples' failed

**Comment by madhubioinfo** [comment]
I think it should be changed to https://github.com/pb-cdunn/FALCON-examples.git

How to change this in a install script if so?

**Comment by gconcepcion** [comment]
Are you sure you didn't temporarily lose connectivity? I just tried 
`git clone git://github.com/pb-cdunn/FALCON-examples.git`
on several different systems(Ubuntu/CentOS/MacOSX) with several different git binaries (1.8, 2.1.0 and 2.8.3) and all worked fine for me.
Which version git binaries do you have installed?

**Comment by madhubioinfo** [comment]
I have the git version of 2.7.4

I Tried installing again now some new error is showing 
./lib/python2.7/site-packages/falcon_kit/fc_asm_graph.py
./lib/python2.7/site-packages/falcon_kit/bash.pyc
./lib/python2.7/site-packages/h5py-2.4.0.dist-info/
./lib/python2.7/site-packages/h5py-2.4.0.dist-info/top_level.txt
./lib/python2.7/site-packages/h5py-2.4.0.dist-info/metadata.json
./lib/python2.7/site-packages/h5py-2.4.0.dist-info/DESCRIPTION.rst
./lib/python2.7/site-packages/h5py-2.4.0.dist-info/INSTALLER
./lib/python2.7/site-packages/h5py-2.4.0.dist-info/RECORD
./lib/python2.7/site-packages/h5py-2.4.0.dist-info/METADATA
./lib/python2.7/site-packages/h5py-2.4.0.dist-info/WHEEL
./lib/python2.7/site-packages/ConsensusCore2.pyc
./lib/libhdf5.so.10
./lib/libhdf5_hl.so.10.0.2
./lib/libhdf5_hl_cpp.so
./lib/libpbbam.so
./lib/pkgconfig/
./lib/pkgconfig/zlib.pc
./lib/libhdf5.so
./lib/libz.so
./lib/libblasr.so
./lib/libhdf5_cpp.so.11
./lib/libpbihdf.so
./install_unzip.sh: line 86: cd: /src/FALCON-integrate/FALCON-examples: No such file or directory
./install_unzip.sh: line 87: ../git-sym/git-sym: No such file or directory
./install_unzip.sh: line 88: cd: run/greg200k-sv2: No such file or directory
[31899]$('lfs setstripe -c 12 /src')
sh: 1: lfs: not found
[31899]WARNING: Call 'lfs setstripe -c 12 /src' returned 32512.
[INFO]Setup logging from file "None".
[INFO]fc_run started with configuration fc_run.cfg
[ERROR]Failed to parse config "fc_run.cfg".
Traceback (most recent call last):
  File "/fc_env_170831/local/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 120, in main1
    config = support.get_dict_from_old_falcon_cfg(support.parse_config(input_config_fn))
  File "/fc_env_170831/local/lib/python2.7/site-packages/falcon_kit/run_support.py", line 131, in parse_config
    config.readfp(open(config_fn))
IOError: [Errno 2] No such file or directory: 'fc_run.cfg'
Traceback (most recent call last):
  File "/fc_env_170831/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit==0.7+git.b65bf34a259ac9537d10ddf4774862ec0adfef10', 'console_scripts', 'fc_run')()
  File "/fc_env_170831/local/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 466, in main
    main1(argv[0], args.config, args.logger)
  File "/fc_env_170831/local/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 120, in main1
    config = support.get_dict_from_old_falcon_cfg(support.parse_config(input_config_fn))
  File "/fc_env_170831/local/lib/python2.7/site-packages/falcon_kit/run_support.py", line 131, in parse_config
    config.readfp(open(config_fn))
IOError: [Errno 2] No such file or directory: 'fc_run.cfg'
sed: can't read fc_unzip.cfg: No such file or directory
[INFO]Setup logging from file "None".
[WARNING]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/fc_env_170831/local/lib/python2.7/site-packages/pwatcher/fs_based.pyc'>
[INFO]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/fc_env_170831/local/lib/python2.7/site-packages/pwatcher/fs_based.pyc'>
[INFO]job_type='SGE', job_queue='default', sge_option=None, use_tmpdir=None, squash=False
[INFO]Num unsatisfied: 1, graph: 1
[INFO]About to submit: Node(3-unzip/reads)
[INFO]starting job Job(jobid='P63dd7d019a21c4', cmd='/bin/bash run.sh', rundir='/src/3-unzip/reads', options={'job_queue': 'default', 'sge_option': ' -pe smp 12 -q bigmem', 'job_type': 'SGE'})
[INFO]!qsub -N P63dd7d019a21c4 -q default -pe smp 12 -V -cwd -o stdout -e stderr -S /bin/bash /src/mypwatcher/wrappers/run-P63dd7d019a21c4.bash
sh: 1: qsub: not found
[ERROR]In pwatcher.fs_based.cmd_run(), failed to submit background-job:
MetaJobSge(MetaJob(job=Job(jobid='P63dd7d019a21c4', cmd='/bin/bash run.sh', rundir='/src/3-unzip/reads', options={'job_queue': 'default', 'sge_option': ' -pe smp 12 -q bigmem', 'job_type': 'SGE'}), lang_exe='/bin/bash'))
Traceback (most recent call last):
  File "/fc_env_170831/local/lib/python2.7/site-packages/pwatcher/fs_based.py", line 532, in cmd_run
    state.submit_background(bjob)
  File "/fc_env_170831/local/lib/python2.7/site-packages/pwatcher/fs_based.py", line 117, in submit_background
    bjob.submit(self, exe, script_fn) # Can raise
  File "/fc_env_170831/local/lib/python2.7/site-packages/pwatcher/fs_based.py", line 300, in submit
    system(sge_cmd, checked=True) # TODO: Capture q-jobid
  File "/fc_env_170831/local/lib/python2.7/site-packages/pwatcher/fs_based.py", line 551, in system
    raise Exception('{} <- {!r}'.format(rc, call))
Exception: 32512 <- 'qsub -N P63dd7d019a21c4 -q default -pe smp 12 -V -cwd -o stdout -e stderr -S /bin/bash /src/mypwatcher/wrappers/run-P63dd7d019a21c4.bash'
[ERROR]Failed to enqueue 1 of 1 jobs: set([Node(3-unzip/reads)])
[WARNING]Nothing is happening, and we had 0 failures. Should we quit? Instead, we will just sleep.
[INFO]sleep 0.1s
Traceback (most recent call last):
  File "/fc_env_170831/bin/fc_unzip.py", line 11, in <module>
    load_entry_point('falcon-unzip==0.4.0', 'console_scripts', 'fc_unzip.py')()
  File "/scratch/cdunn/fork/.git/LOCAL/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 382, in main
  File "/scratch/cdunn/fork/.git/LOCAL/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 222, in unzip_all
IOError: [Errno 2] No such file or directory: './3-unzip/reads/ctg_list'
FALCON & FALCON_unzip have been successfully installed into a virtualenv.
To activate the FALCON_unzip environment:
$ source /fc_env_170831/bin/activate

**Comment by pb-cdunn** [comment]
We would need more details, e.g. actual command-lines. Assuming this has been resolved.

**Comment by madhubioinfo** [comment]
Hello I tried my level best to install and check all possibilities i can give the commandline which i used , please reopen the issue i have been waiting for you all to reply since its bit urgent to install. Iam installing as a root. the following error is coming
fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=Connection timed out
github.com[1: 192.30.253.113]: errno=Connection timed out

fatal: clone of 'git://github.com/pb-cdunn/FALCON-examples.git' into submodule path 'FALCON-examples' failed
cp -f default-env.sh env.sh
bash ./FALCON-make/config-standard.sh
bash: ./FALCON-make/config-standard.sh: No such file or directory
makefile:15: recipe for target 'config-standard' failed
make: *** [config-standard] Error 127
make -C ./FALCON-make/ all
make[1]: Entering directory '/src/FALCON-integrate/FALCON-make'
make[1]: *** No rule to make target 'all'.  Stop.
make[1]: Leaving directory '/src/FALCON-integrate/FALCON-make'
makefile:18: recipe for target 'all' failed
make: *** [all] Error 2
make -C ./FALCON-make/ install
make[1]: Entering directory '/src/FALCON-integrate/FALCON-make'
make[1]: *** No rule to make target 'install'.  Stop.
make[1]: Leaving directory '/src/FALCON-integrate/FALCON-make'
makefile:20: recipe for target 'install' failed
make: *** [install] Error 2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  5 93.7M    5 5472k    0     0   358k      0  0:04:27  0:00:15  0:04:12  781k
