### ISSUE TITLE
Falcon-integrate test run is failed 

### ISSUE THREAD

**Issue by zhangqing970** [PacificBiosciences/FALCON-integrate#156]
After installing the falcon i tried the running the test run with ecoli it was failed and this is the error i got, what should i do? Thanks
```
$ fc_run.py fc_run.cfg
[14553]$('lfs setstripe -c 12 /public3/stu_zhangqing/Program/LZ_assembly/assembly/Falcon')
sh: lfs: command not found
[14553]WARNING: Call 'lfs setstripe -c 12 /public3/stu_zhangqing/Program/LZ_assembly/assembly/Falcon' returned 32512.
[INFO]Setup logging from file "None".
[INFO]fc_run started with configuration fc_run.cfg
/public1/home/stu_zhangqing/anaconda2/lib/python2.7/site-packages/falcon_kit-0.7+git.3ec3d6d1699f6409930ced549d2730cbdb5b44c7-py2.7-linux-x86_64.egg/falcon_kit/run_support.py:194: UserWarning: Deprecated setting in config: 'pa_concurrent_jobs' -- Prefer da_concurrent_jobs and la_concurrent_jobs separately
  "Deprecated setting in config: 'pa_concurrent_jobs' -- Prefer da_concurrent_jobs and la_concurrent_jobs separately")
/public1/home/stu_zhangqing/anaconda2/lib/python2.7/site-packages/falcon_kit-0.7+git.3ec3d6d1699f6409930ced549d2730cbdb5b44c7-py2.7-linux-x86_64.egg/falcon_kit/run_support.py:199: UserWarning: Deprecated setting in config: 'ovlp_concurrent_jobs' -- Prefer pda_concurrent_jobs and pla_concurrent_jobs separately
  "Deprecated setting in config: 'ovlp_concurrent_jobs' -- Prefer pda_concurrent_jobs and pla_concurrent_jobs separately")
[INFO] No target specified, assuming "assembly" as target
/public1/home/stu_zhangqing/anaconda2/lib/python2.7/site-packages/falcon_kit-0.7+git.3ec3d6d1699f6409930ced549d2730cbdb5b44c7-py2.7-linux-x86_64.egg/falcon_kit/run_support.py:456: UserWarning: Unexpected keys in input config: set(['pa_concurrent_jobs', 'ovlp_concurrent_jobs'])
  warnings.warn("Unexpected keys in input config: %s" % repr(unused))
[WARNING]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/public1/home/stu_zhangqing/anaconda2/lib/python2.7/site-packages/pypeflow-1.0.0-py2.7.egg/pwatcher/fs_based.pyc'>
[INFO]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/public1/home/stu_zhangqing/anaconda2/lib/python2.7/site-packages/pypeflow-1.0.0-py2.7.egg/pwatcher/fs_based.pyc'>
[INFO]job_type='SGE', job_queue='all.q', sge_option='-pe mpi 8 -q all.q -l mem_free=40g', use_tmpdir=False, squash=False, job_name_style=0
[INFO]Num unsatisfied: 1, graph: 1
[INFO]About to submit: Node(1-preads_ovl/preads-fofn-abs)
[INFO]starting job Job(jobid='P3d40382a5fe4cd', cmd='/bin/bash run.sh', rundir='/public3/stu_zhangqing/Program/LZ_assembly/assembly/Falcon/1-preads_ovl/preads-fofn-abs', options={'job_queue': 'all.q', 'sge_option': '-pe mpi 8 -q all.q -l mem_free=40g', 'job_type': 'SGE'})
[INFO]!qsub -N P3d40382a5fe4cd -q all.q -pe mpi 8 -l mem_free=40g -V -cwd -o stdout -e stderr -S /bin/bash /public3/stu_zhangqing/Program/LZ_assembly/assembly/Falcon/mypwatcher/wrappers/run-P3d40382a5fe4cd.bash
Your job 148116 ("P3d40382a5fe4cd") has been submitted
[INFO]Submitted backgroundjob=MetaJobSge(MetaJob(job=Job(jobid='P3d40382a5fe4cd', cmd='/bin/bash run.sh', rundir='/public3/stu_zhangqing/Program/LZ_assembly/assembly/Falcon/1-preads_ovl/preads-fofn-abs', options={'job_queue': 'all.q', 'sge_option': '-pe mpi 8 -q all.q -l mem_free=40g', 'job_type': 'SGE'}), lang_exe='/bin/bash'))
[INFO]sleep 0.1s
[INFO]sleep 0.2s
[INFO]sleep 0.3s
[INFO]sleep 0.4s
[INFO]sleep 0.5s
[INFO]sleep 0.6s
[INFO]sleep 0.7s
[INFO]sleep 0.8s
[INFO]sleep 0.9s
[INFO]sleep 1.0s
[INFO]sleep 1.1s
[INFO]sleep 1.2s
[INFO]sleep 1.3s
[INFO]sleep 1.4s
[INFO]sleep 1.5s
[INFO]sleep 1.6s
[INFO]sleep 1.7s
[INFO]sleep 1.8s
[ERROR]Task Node(1-preads_ovl/preads-fofn-abs) failed with exit-code=32512
[INFO]recently_satisfied: set([])
[INFO]Num satisfied in this iteration: 0
[INFO]Num still unsatisfied: 1
[ERROR]Some tasks are recently_done but not satisfied: set([Node(1-preads_ovl/preads-fofn-abs)])
[ERROR]ready: set([])
submitted: set([])
[INFO]!qdel -k P3d40382a5fe4cd
The job -k of user(s) stu_zhangqing does not exist
stu_zhangqing has deleted job 148116
Traceback (most recent call last):
  File "/public1/home/stu_zhangqing/anaconda2/bin/fc_run.py", line 11, in <module>
    load_entry_point('falcon-kit==0.7+git.3ec3d6d1699f6409930ced549d2730cbdb5b44c7', 'console_scripts', 'fc_run.py')()
  File "/public1/home/stu_zhangqing/anaconda2/lib/python2.7/site-packages/falcon_kit-0.7+git.3ec3d6d1699f6409930ced549d2730cbdb5b44c7-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 504, in main
    main1(argv[0], args.config, args.logger)
  File "/public1/home/stu_zhangqing/anaconda2/lib/python2.7/site-packages/falcon_kit-0.7+git.3ec3d6d1699f6409930ced549d2730cbdb5b44c7-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 150, in main1
    input_fofn_plf=input_fofn_plf,
  File "/public1/home/stu_zhangqing/anaconda2/lib/python2.7/site-packages/falcon_kit-0.7+git.3ec3d6d1699f6409930ced549d2730cbdb5b44c7-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 356, in run
    wf.refreshTargets([fofn_abs_task])
  File "/public1/home/stu_zhangqing/anaconda2/lib/python2.7/site-packages/pypeflow-1.0.0-py2.7.egg/pypeflow/simple_pwatcher_bridge.py", line 273, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/public1/home/stu_zhangqing/anaconda2/lib/python2.7/site-packages/pypeflow-1.0.0-py2.7.egg/pypeflow/simple_pwatcher_bridge.py", line 339, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(1-preads_ovl/preads-fofn-abs)])
```

**Comment by pb-cdunn** [comment]
You'd have to look into the directory `./1-preads_ovl/preads-fofn-abs` for `stderr/stdout` to learn what happened. You can even re-run that specific program yourself, maybe with a debugger.

I think our examples need to be updated though.
