### ISSUE TITLE
FALCON-integrate Installation Error

### ISSUE THREAD

**Issue by tamim07** [PacificBiosciences/FALCON-integrate#160]
Hello there,

After following the FALCON installation instruction, I have got the error below down there. Can anyone help me please. 
```
export GIT_SYM_CACHE_DIR=~/.git-sym-cache # to speed things up
git clone git://github.com/PacificBiosciences/FALCON-integrate.git
cd FALCON-integrate
git checkout develop  # or whatever version you want
git submodule update --init --recursive # Note: You must do this yourself! No longer via `make init`.
make init
source env.sh
make config-edit-user
make -j all
```
#157  #159  I have all of these.
```
PREFIX=/home/tamim/Desktop/software/FALCON-integrate/fc_env make -C /home/tamim/Desktop/software/FALCON-integrate/DAZZ_DB symlink
make[3]: Entering directory '/home/tamim/Desktop/software/FALCON-integrate/nim-falcon/src'
nim --threads:on --threadAnalysis:off --verbosity:2 -d:release  --tlsemulation:on --out:fc_rr_hctg_track2.exe c fc_rr_hctg_track2.nim
make[3]: nim: Command not found
make[3]: *** [makefile:41: fc_rr_hctg_track2.exe] Error 127
make[3]: Leaving directory '/home/tamim/Desktop/software/FALCON-integrate/nim-falcon/src'
make[2]: *** [makefile:44: install-nim-falcon] Error 2
make[2]: *** Waiting for unfinished jobs....
make[3]: Entering directory '/home/tamim/Desktop/software/FALCON-integrate/DEXTRACTOR'
ln -sf /home/tamim/Desktop/software/FALCON-integrate/DEXTRACTOR/dexta /home/tamim/Desktop/software/FALCON-integrate/DEXTRACTOR/undexta /home/tamim/Desktop/software/FALCON-integrate/fc_env/bin
make[3]: Entering directory '/home/tamim/Desktop/software/FALCON-integrate/DAMASKER'
ln -sf /home/tamim/Desktop/software/FALCON-integrate/DAMASKER/datander /home/tamim/Desktop/software/FALCON-integrate/DAMASKER/TANmask /home/tamim/Desktop/software/FALCON-integrate/DAMASKER/REPmask /home/tamim/Desktop/software/FALCON-integrate/DAMASKER/HPC.TANmask /home/tamim/Desktop/software/FALCON-integrate/DAMASKER/HPC.REPmask /home/tamim/Desktop/software/FALCON-integrate/fc_env/bin
make[3]: Entering directory '/home/tamim/Desktop/software/FALCON-integrate/DAZZ_DB'
ln -sf /home/tamim/Desktop/software/FALCON-integrate/DAZZ_DB/fasta2DB /home/tamim/Desktop/software/FALCON-integrate/DAZZ_DB/DB2fasta /home/tamim/Desktop/software/FALCON-integrate/DAZZ_DB/DBsplit /home/tamim/Desktop/software/FALCON-integrate/DAZZ_DB/DBdust /home/tamim/Desktop/software/FALCON-integrate/DAZZ_DB/Catrack /home/tamim/Desktop/software/FALCON-integrate/DAZZ_DB/DBshow /home/tamim/Desktop/software/FALCON-integrate/DAZZ_DB/DBstats /home/tamim/Desktop/software/FALCON-integrate/DAZZ_DB/DBrm /home/tamim/Desktop/software/FALCON-integrate/DAZZ_DB/simulator /home/tamim/Desktop/software/FALCON-integrate/DAZZ_DB/fasta2DAM /home/tamim/Desktop/software/FALCON-integrate/DAZZ_DB/DAM2fasta /home/tamim/Desktop/software/FALCON-integrate/DAZZ_DB/DBdump /home/tamim/Desktop/software/FALCON-integrate/DAZZ_DB/rangen /home/tamim/Desktop/software/FALCON-integrate/fc_env/bin
make[3]: Leaving directory '/home/tamim/Desktop/software/FALCON-integrate/DEXTRACTOR'
make[3]: Leaving directory '/home/tamim/Desktop/software/FALCON-integrate/DAMASKER'
ln -sf /home/tamim/Desktop/software/FALCON-integrate/DAZZ_DB/libdazzdb.a /home/tamim/Desktop/software/FALCON-integrate/fc_env/lib
ln -sf /home/tamim/Desktop/software/FALCON-integrate/DAZZ_DB/DB.h /home/tamim/Desktop/software/FALCON-integrate/DAZZ_DB/QV.h /home/tamim/Desktop/software/FALCON-integrate/fc_env/include
make[3]: Leaving directory '/home/tamim/Desktop/software/FALCON-integrate/DAZZ_DB'
Obtaining file:///home/tamim/Desktop/software/FALCON-integrate/pypeFLOW
  Running setup.py (path:/home/tamim/Desktop/software/FALCON-integrate/pypeFLOW/setup.py) egg_info for package from file:///home/tamim/Desktop/software/FALCON-integrate/pypeFLOW
    Running command python setup.py egg_info
    running egg_info
    writing requirements to pypeflow.egg-info/requires.txt
    writing pypeflow.egg-info/PKG-INFO
    writing top-level names to pypeflow.egg-info/top_level.txt
    writing dependency_links to pypeflow.egg-info/dependency_links.txt
    writing entry points to pypeflow.egg-info/entry_points.txt
    reading manifest file 'pypeflow.egg-info/SOURCES.txt'
    writing manifest file 'pypeflow.egg-info/SOURCES.txt'
  Source in /home/tamim/Desktop/software/FALCON-integrate/pypeFLOW has version 1.0.0, which satisfies requirement pypeflow==1.0.0 from file:///home/tamim/Desktop/software/FALCON-integrate/pypeFLOW
Requirement already satisfied: networkx<=1.11,>=1.7 in /home/tamim/Desktop/software/FALCON-integrate/fc_env/lib/python2.7/site-packages (from pypeflow==1.0.0)
Requirement already satisfied: decorator>=3.4.0 in /home/tamim/Desktop/software/FALCON-integrate/fc_env/lib/python2.7/site-packages (from networkx<=1.11,>=1.7->pypeflow==1.0.0)
Installing collected packages: pypeflow
  Found existing installation: pypeflow 1.0.0
    Uninstalling pypeflow-1.0.0:
      Removing file or directory /home/tamim/Desktop/software/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow.egg-link
      Removing pth entries from /home/tamim/Desktop/software/FALCON-integrate/fc_env/lib/python2.7/site-packages/easy-install.pth:
      Removing entry: /home/tamim/Desktop/software/FALCON-integrate/pypeFLOW
      Successfully uninstalled pypeflow-1.0.0
  Running setup.py develop for pypeflow
    Running command /usr/bin/python2 -c "import setuptools, tokenize;__file__='/home/tamim/Desktop/software/FALCON-integrate/pypeFLOW/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps
    running develop
    error: can't create or remove files in install directory

    The following error occurred while trying to add or remove files in the
    installation directory:

        [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/test-easy-install-3804.write-test'

    The installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:

        /usr/lib/python2.7/site-packages/

    Perhaps your account does not have write access to this directory?  If the
    installation directory is a system-owned directory, you may need to sign in
    as the administrator or "root" account.  If you do not have administrative
    access to this machine, you may wish to choose a different installation
    directory, preferably one that is listed in your PYTHONPATH environment
    variable.

    For information on other options, you may wish to consult the
    documentation at:

      https://setuptools.readthedocs.io/en/latest/easy_install.html

    Please make the appropriate changes for your system and try again.

  Rolling back uninstall of pypeflow
  Replacing /home/tamim/Desktop/software/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow.egg-link
  Rolling /home/tamim/Desktop/software/FALCON-integrate/fc_env/lib/python2.7/site-packages/easy-install.pth back to previous state
Cleaning up...
Command "/usr/bin/python2 -c "import setuptools, tokenize;__file__='/home/tamim/Desktop/software/FALCON-integrate/pypeFLOW/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/tamim/Desktop/software/FALCON-integrate/pypeFLOW/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 365, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 844, in install
    install_options, global_options, prefix=prefix)
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 1011, in install_editable
    show_stdout=False)
  File "/usr/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/bin/python2 -c "import setuptools, tokenize;__file__='/home/tamim/Desktop/software/FALCON-integrate/pypeFLOW/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/tamim/Desktop/software/FALCON-integrate/pypeFLOW/
make[2]: *** [makefile:38: install-pypeFLOW] Error 1
make[2]: Leaving directory '/home/tamim/Desktop/software/FALCON-integrate/FALCON-make'
make[1]: *** [makefile:19: all] Error 2
make[1]: Leaving directory '/home/tamim/Desktop/software/FALCON-integrate/FALCON-make'
make: *** [makefile:18: all] Error 2
```
I need your kind help. @pb-cdunn

**Comment by pb-cdunn** [comment]
You had 2 problems:

1. You needed to install the `nim` compiler: https://nim-lang.org/install.html
2. You seem to have an old version of pip/setuptools. That's hard to solve from here, but possible.
