### ISSUE TITLE
WARNING: Call 'lfs setstripe -c 12 FALCON-integrate' returned 32512.

### ISSUE THREAD

**Issue by yhsYhsYhs** [PacificBiosciences/FALCON-integrate#166]
Hello,I run falcon on my server and following  error occured. And, If I only want to run error-correct step, how should I use?thanks
python FALCON/src/py_scripts/fc_run.py  FALCON-integrate/FALCON-examples/run/ecoli2/fc_run.cfg
[19705]$('lfs setstripe -c 12 FALCON-integrate')
sh: 1: lfs: not found
[19705]WARNING: Call 'lfs setstripe -c 12 FALCON-integrate' returned 32512.
[INFO]Setup logging from file "None".
[INFO]fc_run started with configuration FALCON-integrate/FALCON-examples/run/ecoli2/fc_run.cfg
[ERROR]Failed to parse config "FALCON-integrate/FALCON-examples/run/ecoli2/fc_run.cfg".
Traceback (most recent call last):
  File "FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 132, in main1
    support.parse_config(input_config_fn))
  File "FALCON-integrate/FALCON/falcon_kit/run_support.py", line 161, in get_dict_from_old_falcon_cfg
    sge_option = config.get(section, 'sge_option_da')
  File "miniconda2/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'sge_option_da' in section: 'General'
Traceback (most recent call last):
  File "FALCON/src/py_scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 504, in main
    main1(argv[0], args.config, args.logger)
  File "FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 132, in main1
    support.parse_config(input_config_fn))
  File "FALCON-integrate/FALCON/falcon_kit/run_support.py", line 161, in get_dict_from_old_falcon_cfg
    sge_option = config.get(section, 'sge_option_da')
  File "miniconda2/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'sge_option_da' in section: 'General'

**Comment by pb-cdunn** [comment]
The `lfs` warning is fine. We have huge slow-downs on LFS when we do *not* set the stripe, so we want to know. Since you are not on LFS, it's harmless.

The ConfigParser means you need to supply `sge_option_da` in your `fc_run.cfg`. (Possibly that example needs to be updated.)
