### ISSUE TITLE
input preads errors

### ISSUE THREAD

**Issue by yplee614** [PacificBiosciences/FALCON-integrate#171]
when i set the input_type = preads, the errors show below:
```
[11291]$(u'lfs setstripe -c 12 /home/yplee/falcon_correct')
sh: lfs: command not found
[11291]WARNING: Call u'lfs setstripe -c 12 /home/yplee/falcon_correct' returned 32512.
[INFO]Setup logging from file "None".
[INFO]fc_run started with configuration fc_run_preads.cfg
/home/yplee/software/falcon_all/fc_env_180407/lib/python2.7/site-packages/falcon_kit/run_support.py:200: UserWarning: Deprecated setting in config: 'pa_concurrent_jobs' -- Prefer da_concurrent_jobs and la_concurrent_jobs separately
  "Deprecated setting in config: 'pa_concurrent_jobs' -- Prefer da_concurrent_jobs and la_concurrent_jobs separately")
/home/yplee/software/falcon_all/fc_env_180407/lib/python2.7/site-packages/falcon_kit/run_support.py:205: UserWarning: Deprecated setting in config: 'ovlp_concurrent_jobs' -- Prefer pda_concurrent_jobs and pla_concurrent_jobs separately
  "Deprecated setting in config: 'ovlp_concurrent_jobs' -- Prefer pda_concurrent_jobs and pla_concurrent_jobs separately")
[INFO] No target specified, assuming "assembly" as target 
/home/yplee/software/falcon_all/fc_env_180407/lib/python2.7/site-packages/falcon_kit/run_support.py:462: UserWarning: Unexpected keys in input config: set(['pa_concurrent_jobs', 'ovlp_concurrent_jobs'])
  warnings.warn("Unexpected keys in input config: %s" % repr(unused))
[WARNING]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.blocking' from '/home/yplee/software/falcon_all/fc_env_180407/lib/python2.7/site-packages/pwatcher/blocking.pyc'>
[INFO]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.blocking' from '/home/yplee/software/falcon_all/fc_env_180407/lib/python2.7/site-packages/pwatcher/blocking.pyc'>
[INFO]job_type='local', job_queue='bash -C ${CMD}', sge_option='-pe smp 5 -q bigmem', use_tmpdir=False, squash=False, job_name_style=0
[INFO]u'Serializing 52 records'
[INFO]u"  Opened for write: u'./config.json'"
[INFO]u'  Serialized to 0.0MB as json'
[INFO]u"Deserializing from u'/home/yplee/falcon_correct/config.json'"
[INFO]u"  Opened for read: u'/home/yplee/falcon_correct/config.json'"
[INFO]u'  Read 0.0MB as json'
[INFO]u'  Deserialized 52 records'
Traceback (most recent call last):
  File "/home/yplee/software/falcon_all/fc_env_180407/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit==1.0+git.6bb3daa96931aece9bd3742bccc77ad257b7bb65', 'console_scripts', 'fc_run')()
  File "/home/yplee/software/falcon_all/fc_env_180407/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 644, in main
    main1(argv[0], args.config, args.logger)
  File "/home/yplee/software/falcon_all/fc_env_180407/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 159, in main1
    input_fofn_plf=input_fofn_plf,
  File "/home/yplee/software/falcon_all/fc_env_180407/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 448, in run
    raise Exception('TODO')
Exception: TODO
```

**Comment by pb-cdunn** [comment]
The `input_type = preads` workflow will be resurrected in the next release, sometime next week.

**Comment by chelidphile** [comment]
Hi I have been having the very same problem. I fed FALCON two fasta files corrected by FALCON itself. Here's what I got:

[WARNING]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.blocking' from '/yshare2/home/hshibata/src/FALCON-integrate/pypeFLOW/pwatcher/blocking.pyc'>
[INFO]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.blocking' from '/yshare2/home/hshibata/src/FALCON-integrate/pypeFLOW/pwatcher/blocking.pyc'>
[INFO]job_type='sge', (default)job_defaults={'pwatcher_type': 'blocking', 'MB': '4096', 'job_type': 'sge', 'submit': 'qsub -S /bin/bash -cwd -sync y -V \\\n-l os7,s_vmem=48G,mem_req=48G -pe def_slot 4 \\\n"${JOB_SCRIPT}"', 'NPROC': '4', 'njobs': 8}, use_tmpdir=None, squash=False, job_name_style=0
[INFO]'Serializing 42 records'
[INFO]"  Opened for write: './config.json'"
[INFO]'  Serialized to 0.0MB as json'
[INFO]"Deserializing from '/yshare2/home/hshibata/Falcon_preads_test_090319/Habu_preads_test_090319/config.json'"
[INFO]"  Opened for read: '/yshare2/home/hshibata/Falcon_preads_test_090319/Habu_preads_test_090319/config.json'"
[INFO]'  Read 0.0MB as json'
[INFO]'  Deserialized 42 records'
Traceback (most recent call last):
  File "/home/hshibata/src/FALCON-integrate/fc_env/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit', 'console_scripts', 'fc_run')()
  File "/yshare2/home/hshibata/src/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 625, in main
    main1(argv[0], args.config, args.logger)
  File "/yshare2/home/hshibata/src/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 153, in main1
    input_fofn_plf=input_fofn_plf,
  File "/yshare2/home/hshibata/src/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 436, in run
    raise Exception('TODO')
Exception: TODO

**Comment by pb-cdunn** [comment]
Try `conda update --all` and restart. Might be working now. (Don't use the source-code in GitHub; it's out of date.)
