### ISSUE TITLE
More nim problems in installation

### ISSUE THREAD

**Issue by peterthorpe5** [PacificBiosciences/FALCON-integrate#176]
Hello,

I am having issues with Falcon-intergrate installation and on https://github.com/PacificBiosciences/FALCON-integrate/issues/157 it says to download this nim version from Github (https://github.com/bio-nim/nim-falcon/tree/dev). Although it says the goal is a single executable,  there is no executable. And make fails when run in the downloaded folder. There are no installation instructions. Can you tell me if anything needs to be done to this download?

So, it tried `chmod -R 777 *`  anyway, added it to my path. Installed nim: https://nim-lang.org/install_unix.html, `curl https://nim-lang.org/choosenim/init.sh -sSf | sh`   , added it to my path. When I run the installation instructions for FALCON-intergrate, at the `make -j` all stage, It still fails:

**......  (selection of failure)**
```
make[3]: nim: Command not found
makefile:41: recipe for target 'fc_rr_hctg_track2.exe' failed
make[3]: *** [fc_rr_hctg_track2.exe] Error 127
make[3]: Leaving directory '/PATH_to/Downloads/FALCON/FALCON-integrate/nim-falcon/src'
makefile:44: recipe for target 'install-nim-falcon' failed
make[2]: *** [install-nim-falcon] Error 2
make[2]: *** Waiting for unfinished jobs....

**If I run nim:**
$ nim
Nim Compiler Version 0.18.0 [Linux: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf
::

    nim command [options] [projectfile] [arguments]

Command:
  compile, c                compile project with default code generator (C)
  doc                       generate the documentation for inputfile

Arguments:
  arguments are passed to the program being run (if --run option is selected)
......
```
**Question:**
Do you have any idea on how to resolve this issue: the full output of make -j all is pasted below.

**My system settings:**
```
Python 2.7.9
centos-release-7-4.1708.el7.centos.x86_64
centos-release-scl-rh-2-2.el7.centos.noarch
```

The following errors do not make it to the output file when running make -j all > errors.txt
```
make[3]: nim: Command not found
make[3]: *** [fc_rr_hctg_track2.exe] Error 127
make[2]: *** [install-nim-falcon] Error 2
make[2]: *** Waiting for unfinished jobs....
You must give at least one requirement to uninstall (see "pip help uninstall")
make[1]: *** [all] Error 2
make: *** [all] Error 2
```
OUTPUT:
```
make -C ./FALCON-make/ all
make[1]: Entering directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/FALCON-make'
make show
make[2]: Entering directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/FALCON-make'
mkdir -p /home/username/scratch/Downloads/FALCON/FALCON-integrate/fc_env/bin
which python
/mnt/shared/scratch/synology/username/apps/conda/envs/falcon_intergrate/bin/python
echo "PYTHONUSERBASE=/home/username/scratch/Downloads/FALCON/FALCON-integrate/fc_env"
PYTHONUSERBASE=/home/username/scratch/Downloads/FALCON/FALCON-integrate/fc_env
python -c 'import site; print site.USER_BASE'
/home/username/scratch/Downloads/FALCON/FALCON-integrate/fc_env
echo "FALCON_PIP_EDIT=--edit"
FALCON_PIP_EDIT=--edit
echo "FALCON_PIP_USER=--user"
FALCON_PIP_USER=--user
make[2]: Leaving directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/FALCON-make'
make install-pip
make[2]: Entering directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/FALCON-make'
python -c 'import pip; print pip' || python get-pip.py --user
<module 'pip' from '/mnt/shared/scratch/synology/username/apps/conda/envs/falcon_intergrate/lib/python2.7/site-packages/pip/__init__.pyc'>
pip install --user --upgrade pip
Requirement already up-to-date: pip in /mnt/du-synology/v1shr1/PATH_TO/apps/conda/envs/falcon_intergrate/lib/python2.7/site-packages (10.0.1)
pip install --user --upgrade setuptools # needed when --edit is used
Requirement already up-to-date: setuptools in /mnt/du-synology/v1shr1/PATH_TO/apps/conda/envs/falcon_intergrate/lib/python2.7/site-packages (39.2.0)
pip install --user nose pytest # for running tests while building
Requirement already satisfied: nose in /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (1.3.7)
Requirement already satisfied: pytest in /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (3.5.1)
Requirement already satisfied: py>=1.5.0 in /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (from pytest) (1.5.3)
Requirement already satisfied: more-itertools>=4.0.0 in /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (from pytest) (4.1.0)
Requirement already satisfied: pluggy<0.7,>=0.5 in /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (from pytest) (0.6.0)
Requirement already satisfied: funcsigs; python_version < "3.0" in /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (from pytest) (1.0.2)
Requirement already satisfied: six>=1.10.0 in /mnt/du-synology/v1shr1/PATH_TO/apps/conda/envs/falcon_intergrate/lib/python2.7/site-packages (from pytest) (1.11.0)
Requirement already satisfied: setuptools in /mnt/du-synology/v1shr1/PATH_TO/apps/conda/envs/falcon_intergrate/lib/python2.7/site-packages (from pytest) (39.2.0)
Requirement already satisfied: attrs>=17.4.0 in /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (from pytest) (18.1.0)
make[2]: Leaving directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/FALCON-make'
make install # This will double -D_GNU_SOURCE, but that is ok for now.
make[2]: Entering directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/FALCON-make'
make -C /home/username/scratch/Downloads/FALCON/FALCON-integrate/DAZZ_DB all
make -C /home/username/scratch/Downloads/FALCON/FALCON-integrate/DAMASKER all
make -C /home/username/scratch/Downloads/FALCON/FALCON-integrate/DEXTRACTOR all
cd /home/username/scratch/Downloads/FALCON/FALCON-integrate/pypeFLOW; pip uninstall -v .; pip install -v --user --edit .
# TODO: copy vs. symlink?
make -C /home/username/scratch/Downloads/FALCON/FALCON-integrate/nim-falcon/src -j1 all
ln -sf /home/username/scratch/Downloads/FALCON/FALCON-integrate/git-sym/git-sym /home/username/scratch/Downloads/FALCON/FALCON-integrate/fc_env/bin/git-sym
make[3]: Entering directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/nim-falcon/src'
nim --threads:on --threadAnalysis:off --verbosity:2 -d:release  --tlsemulation:on --out:fc_rr_hctg_track2.exe c fc_rr_hctg_track2.nim
make[3]: Entering directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DEXTRACTOR'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DEXTRACTOR'
PREFIX=/home/username/scratch/Downloads/FALCON/FALCON-integrate/fc_env make -C /home/username/scratch/Downloads/FALCON/FALCON-integrate/DEXTRACTOR symlink
make[3]: Entering directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAMASKER'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAMASKER'
PREFIX=/home/username/scratch/Downloads/FALCON/FALCON-integrate/fc_env make -C /home/username/scratch/Downloads/FALCON/FALCON-integrate/DAMASKER symlink
make[3]: Entering directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAZZ_DB'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAZZ_DB'
PREFIX=/home/username/scratch/Downloads/FALCON/FALCON-integrate/fc_env make -C /home/username/scratch/Downloads/FALCON/FALCON-integrate/DAZZ_DB symlink
make[3]: Entering directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DEXTRACTOR'
ln -sf /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DEXTRACTOR/dexta /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DEXTRACTOR/undexta /home/username/scratch/Downloads/FALCON/FALCON-integrate/fc_env/bin
make[3]: Entering directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAMASKER'
ln -sf /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAMASKER/datander /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAMASKER/TANmask /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAMASKER/REPmask /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAMASKER/HPC.TANmask /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAMASKER/HPC.REPmask /home/username/scratch/Downloads/FALCON/FALCON-integrate/fc_env/bin
make[3]: Entering directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAZZ_DB'
ln -sf /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAZZ_DB/fasta2DB /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAZZ_DB/DB2fasta /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAZZ_DB/DBsplit /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAZZ_DB/DBdust /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAZZ_DB/Catrack /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAZZ_DB/DBshow /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAZZ_DB/DBstats /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAZZ_DB/DBrm /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAZZ_DB/simulator /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAZZ_DB/fasta2DAM /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAZZ_DB/DAM2fasta /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAZZ_DB/DBdump /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAZZ_DB/rangen /home/username/scratch/Downloads/FALCON/FALCON-integrate/fc_env/bin
makefile:41: recipe for target 'fc_rr_hctg_track2.exe' failed
make[3]: Leaving directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/nim-falcon/src'
makefile:44: recipe for target 'install-nim-falcon' failed
make[3]: Leaving directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DEXTRACTOR'
make[3]: Leaving directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAMASKER'
ln -sf /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAZZ_DB/libdazzdb.a /home/username/scratch/Downloads/FALCON/FALCON-integrate/fc_env/lib
ln -sf /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAZZ_DB/QV.h /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAZZ_DB/DB.h /home/username/scratch/Downloads/FALCON/FALCON-integrate/fc_env/include
make[3]: Leaving directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/DAZZ_DB'
Exception information:
Traceback (most recent call last):
  File "/mnt/shared/scratch/synology/username/apps/conda/envs/falcon_intergrate/lib/python2.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/mnt/shared/scratch/synology/username/apps/conda/envs/falcon_intergrate/lib/python2.7/site-packages/pip/_internal/commands/uninstall.py", line 64, in run
    '"pip help %(name)s")' % dict(name=self.name)
InstallationError: You must give at least one requirement to uninstall (see "pip help uninstall")
Created temporary directory: /tmp/pip-ephem-wheel-cache-ZeKdjM
Created temporary directory: /tmp/pip-install-ttk9NN
Obtaining file:///mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/pypeFLOW
  Running setup.py (path:/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/pypeFLOW/setup.py) egg_info for package from file:///mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/pypeFLOW
    Running command python setup.py egg_info
    /mnt/shared/scratch/synology/username/apps/conda/envs/falcon_intergrate/lib/python2.7/site-packages/setuptools/dist.py:398: UserWarning: Normalizing '2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef
    ' to '2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef'
      normalized_version,
    running egg_info
    writing requirements to pypeflow.egg-info/requires.txt
    writing pypeflow.egg-info/PKG-INFO
    writing top-level names to pypeflow.egg-info/top_level.txt
    writing dependency_links to pypeflow.egg-info/dependency_links.txt
    writing entry points to pypeflow.egg-info/entry_points.txt
    reading manifest file 'pypeflow.egg-info/SOURCES.txt'
    writing manifest file 'pypeflow.egg-info/SOURCES.txt'
  Source in /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/pypeFLOW has version 2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef, which satisfies requirement pypeflow==2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef from file:///mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/pypeFLOW
Requirement already satisfied: networkx<=1.11,>=1.7 in /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (from pypeflow==2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef) (1.11)
Requirement already satisfied: future>=0.16.0 in /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (from pypeflow==2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef) (0.16.0)
Requirement already satisfied: decorator>=3.4.0 in /mnt/du-synology/v1shr1/PATH_TO/apps/conda/envs/falcon_intergrate/lib/python2.7/site-packages (from networkx<=1.11,>=1.7->pypeflow==2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef) (4.3.0)
Installing collected packages: pypeflow
  Found existing installation: pypeflow 2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef
    Uninstalling pypeflow-2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef:
      Created temporary directory: /tmp/pip-uninstall-1H8HbG
      Removing file or directory /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow.egg-link
      Removing pth entries from /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages/easy-install.pth:
      Removing entry: /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/pypeFLOW
      Successfully uninstalled pypeflow-2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef
  Running setup.py develop for pypeflow
    Running command /mnt/shared/scratch/synology/username/apps/conda/envs/falcon_intergrate/bin/python -c "import setuptools, tokenize;__file__='/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/pypeFLOW/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=
    /mnt/shared/scratch/synology/username/apps/conda/envs/falcon_intergrate/lib/python2.7/site-packages/setuptools/dist.py:398: UserWarning: Normalizing '2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef
    ' to '2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef'
      normalized_version,
    running develop
    running egg_info
    writing requirements to pypeflow.egg-info/requires.txt
    writing pypeflow.egg-info/PKG-INFO
    writing top-level names to pypeflow.egg-info/top_level.txt
    writing dependency_links to pypeflow.egg-info/dependency_links.txt
    writing entry points to pypeflow.egg-info/entry_points.txt
    reading manifest file 'pypeflow.egg-info/SOURCES.txt'
    writing manifest file 'pypeflow.egg-info/SOURCES.txt'
    running build_ext
    Creating /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow.egg-link (link to .)
    Adding pypeflow 2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef to easy-install.pth file
    Installing pwatcher-pypeflow-example script to /home/username/scratch/Downloads/FALCON/FALCON-integrate/fc_env/bin
    Installing heartbeat-wrapper script to /home/username/scratch/Downloads/FALCON/FALCON-integrate/fc_env/bin
    Installing pwatcher-main script to /home/username/scratch/Downloads/FALCON/FALCON-integrate/fc_env/bin

    Installed /mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/pypeFLOW
Successfully installed pypeflow
Cleaning up...
make[2]: Leaving directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/FALCON-make'
makefile:17: recipe for target 'all' failed
make[1]: Leaving directory '/mnt/shared/PATH_TO/Downloads/FALCON/FALCON-integrate/FALCON-make'
makefile:18: recipe for target 'all' failed


env.sh:

FALCON_WORKSPACE=$(pwd)
PYTHONUSERBASE=$(pwd)/fc_env
FALCON_PREFIX=${PYTHONUSERBASE}
PATH=${PYTHONUSERBASE}/bin:${FALCON_PREFIX}/bin:${PATH}
export PYTHONUSERBASE
export FALCON_WORKSPACE
export FALCON_PREFIX
export PATH
mkdir -p ${FALCON_PREFIX}/include
mkdir -p ${FALCON_PREFIX}/bin
mkdir -p ${FALCON_PREFIX}/lib
```
cheers,

Pete

**Comment by pb-cdunn** [comment]
nim: Command not found

The **nim** compiler must be in your `$PATH` before you start installation. I would ensure that `which nim` is working, and *then* redo the entire Falcon installation.

I wish I could help you more, but it's difficult from a distance. This is a simple environment integration problem somewhere. Good luck! Let us know what you learn, since there might be a way to help others avoid this in the future.
