### ISSUE TITLE
make test error

### ISSUE THREAD

**Issue by hollandorange** [PacificBiosciences/FALCON-integrate#183]
After two days efforts, I finally succeeded in installing FALCON. But when I run "make test", I got the following errors. Is the data still downloadable? or something else wrong? please help~ Thanks

```sh
zhangyanju@thinkstation:~/software/FALCON-integrate$ make test
make -C ./FALCON-make/ test
make[1]: Entering directory '/home/zhangyanju/software/FALCON-integrate/FALCON-make'
make -C /home/zhangyanju/software/FALCON-integrate/FALCON-examples test
make[2]: Entering directory '/home/zhangyanju/software/FALCON-integrate/FALCON-examples'
python -c 'import pypeflow.pwatcher_workflow; print pypeflow.pwatcher_workflow'
<module 'pypeflow.pwatcher_workflow' from '/home/zhangyanju/software/FALCON-integrate/pypeFLOW/pypeflow/pwatcher_workflow.pyc'>
python -c 'import falcon_kit; print falcon_kit.falcon'
<CDLL '/home/zhangyanju/software/FALCON-integrate/FALCON/ext_falcon.so', handle 180d8f0 at 7fbb03c84ad0>
make run-synth0
make[3]: Entering directory '/home/zhangyanju/software/FALCON-integrate/FALCON-examples'
git-sym update run/synth0
-> in dir 'run/synth0'
<- back to dir '/home/zhangyanju/software/FALCON-integrate/FALCON-examples'
symlink: 'run/synth0/data/synth5k'
'run/synth0/data/synth5k' -> '../../../.git-sym/synth5k.2016-11-02' does not exist
-> in dir '/home/zhangyanju/software/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/links'
-> in dir '/home/zhangyanju/software/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/cache'
make -j  -f /home/zhangyanju/software/FALCON-integrate/FALCON-examples/git-sym.makefile 'synth5k.2016-11-02'
make[4]: Entering directory '/home/zhangyanju/software/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/cache'
curl -kL https://downloads.pacbcloud.com/public/data/git-sym/synth5k.2016-11-02.tgz | tar xvfz -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   244  100   244    0     0    148      0  0:00:01  0:00:01 --:--:--   148

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
/home/zhangyanju/software/FALCON-integrate/FALCON-examples/git-sym.makefile:27: recipe for target 'synth5k.2016-11-02' failed
make[4]: *** [synth5k.2016-11-02] Error 2
make[4]: Leaving directory '/home/zhangyanju/software/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/cache'
Traceback (most recent call last):
  File "/home/zhangyanju/software/FALCON-integrate/fc_env/bin/git-sym", line 455, in main
    cmd_table[cmd](**args)
  File "/home/zhangyanju/software/FALCON-integrate/fc_env/bin/git-sym", line 357, in git_sym_update
    retrieve(needed)
  File "/home/zhangyanju/software/FALCON-integrate/fc_env/bin/git-sym", line 284, in retrieve
    retrieve_using_make(makefilename, paths)
  File "/home/zhangyanju/software/FALCON-integrate/fc_env/bin/git-sym", line 277, in retrieve_using_make
    system(cmd)
  File "/home/zhangyanju/software/FALCON-integrate/fc_env/bin/git-sym", line 81, in system
    raise Exception('%d <- %r' %(rc, cmd))
Exception: 512 <- "make -j  -f /home/zhangyanju/software/FALCON-integrate/FALCON-examples/git-sym.makefile 'synth5k.2016-11-02'"

makefile:6: recipe for target 'setup-synth0' failed
make[3]: *** [setup-synth0] Error 1
make[3]: Leaving directory '/home/zhangyanju/software/FALCON-integrate/FALCON-examples'
makefile:11: recipe for target 'test' failed
make[2]: *** [test] Error 2
make[2]: Leaving directory '/home/zhangyanju/software/FALCON-integrate/FALCON-examples'
makefile:72: recipe for target 'test' failed
make[1]: *** [test] Error 2
make[1]: Leaving directory '/home/zhangyanju/software/FALCON-integrate/FALCON-make'
makefile:22: recipe for target 'test' failed
make: *** [test] Error 2
```

**Comment by pb-cdunn** [comment]
`curl -kL https://downloads.pacbcloud.com/public/data/git-sym/synth5k.2016-11-02.tgz`

pacbcloud was down. If you try again, it should work. However, you might need to delete your git-sym cache. If so, I can help you with that.
