### ISSUE TITLE
configuration file error

### ISSUE THREAD

**Issue by xieruopeng** [PacificBiosciences/FALCON-integrate#187]
```py
Traceback (most recent call last):
  File "fc_run.py", line 7, in <module>
    main(sys.argv)
  File "/root/xieruopeng/FALCON/fc_env_181004/local/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 724, in main
    main1(argv[0], args.config, args.logger)
  File "/root/xieruopeng/FALCON/fc_env_181004/local/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 60, in main1
    check_general_config(general_config, input_config_fn)
  File "/root/xieruopeng/FALCON/fc_env_181004/local/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 40, in check_general_config
    raise Exception(msg)
Exception: Missing options.
We now require both "pa_daligner_option" (stage 0) and "ovlp_daligner_option" (stage 1),
which are automatically passed along to
  HPC.daligner
  HPC.TANmask
  HPC.REPmask

These can provide additional flags:
  pa_HPCdaligner_option
  pa_HPCTANmask_option
  ovlp_HPCdaligner_option
  pa_REPmask_code (-g/-c pairs for 3 iterations, e.g. '1,20;5,15;20,10')
```
I download fc_run_ecoli.cfg  from Official website. But run fc_run fc_run.cfg, the above error occurred.

**Comment by lijingjing1** [comment]
the fc_run.cfg you download is old for old version,you should get the cfg from the example make test.

**Comment by Hongchang-Gu** [comment]
hi，bro！Is your problem solved? I also met the same problem.
I hope to get your reply.

**Comment by pb-cdunn** [comment]
Because of PacBio policy, this repo is not maintained for external users anymore. Please use Bioconda.
```
conda install pb-assembly
conda update --all
```
Then, see https://github.com/PacificBiosciences/FALCON/wiki/Options-Available

**Comment by QiushiLi** [comment]
just put the "pa_daligner_option"  and "ovlp_daligner_option" under the [General].

**Comment by pb-cdunn** [comment]
@QiushiLi , I love your cat pic.
