### ISSUE TITLE
run errors

### ISSUE THREAD

**Issue by pengweixing** [PacificBiosciences/FALCON-integrate#188]
Falcon version: falcon-2018.08.08-21.41-py2.7-ucs4-beta
Platform: LSF 
The errors show below:
```py
[INFO] starting job Job(jobid='P7a61d3b25c378a', cmd='/bin/bash run.sh', rundir='/YZGROUP4/STORAGE/NOVO/Crop/Projects/Crop1/xingpengwei/P101SC1805
2225-01_rice_denovo/02.assemble_falcon_X8/1-preads_ovl/build', options={'JOB_QUEUE': '"Sharedqueue"', 'job_queue': '"Sharedqueue"', 'pwatcher_type': 'fs_based', 'use_tmpdir': False, 'MB': 4000, 'job_type': 'LSF', 'NPROC': 1, 'njobs': 8}) w/ job_type=LSFTraceback (most recent call last):
  File "/YZGROUP4/STORAGE/NOVO/Crop/Projects/Crop1/xingpengwei/software/falcon/bin/fc_run.py", line 11, in <module>
    sys.exit(main())
  File "/YZGROUP4/STORAGE/NOVO/Crop/Projects/Crop1/xingpengwei/software/falcon/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 724, in
 main    main1(argv[0], args.config, args.logger)
  File "/YZGROUP4/STORAGE/NOVO/Crop/Projects/Crop1/xingpengwei/software/falcon/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 76, in 
main1    input_fofn_fn=input_fofn_fn,
  File "/YZGROUP4/STORAGE/NOVO/Crop/Projects/Crop1/xingpengwei/software/falcon/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 437, in
 run    daligner_split_script=pype_tasks.TASK_DB_DALIGNER_SPLIT_SCRIPT,
  File "/YZGROUP4/STORAGE/NOVO/Crop/Projects/Crop1/xingpengwei/software/falcon/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 537, in
 add_daligner_and_merge_tasks    dist=Dist(NPROC=4, MB=4000, job_dict=daligner_job_config),
  File "/YZGROUP4/STORAGE/NOVO/Crop/Projects/Crop1/xingpengwei/software/falcon/lib/python2.7/site-packages/falcon_kit/pype.py", line 106, in gen_p
arallel_tasks    wf.refreshTargets()
  File "/YZGROUP4/STORAGE/NOVO/Crop/Projects/Crop1/xingpengwei/software/falcon/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", li
ne 277, in refreshTargets    self._refreshTargets(updateFreq, exitOnFailure)
  File "/YZGROUP4/STORAGE/NOVO/Crop/Projects/Crop1/xingpengwei/software/falcon/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", li
ne 316, in _refreshTargets    unsubmitted = set(self.tq.enque(to_submit)) # In theory, this traps exceptions.
  File "/YZGROUP4/STORAGE/NOVO/Crop/Projects/Crop1/xingpengwei/software/falcon/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", li
ne 152, in enque    result = self.watcher.run(**watcher_args)
  File "/YZGROUP4/STORAGE/NOVO/Crop/Projects/Crop1/xingpengwei/software/falcon/lib/python2.7/site-packages/pwatcher/fs_based.py", line 650, in run
    return cmd_run(self.state, jobids, job_type, job_defaults_dict)
  File "/YZGROUP4/STORAGE/NOVO/Crop/Projects/Crop1/xingpengwei/software/falcon/lib/python2.7/site-packages/pwatcher/fs_based.py", line 455, in cmd
_run    bjob = MetaJobLsf(mjob)
  File "/YZGROUP4/STORAGE/NOVO/Crop/Projects/Crop1/xingpengwei/software/falcon/lib/python2.7/site-packages/pwatcher/fs_based.py", line 404, in __i
nit__    super(MetaJobLsf, self).__init__(mjob)
TypeError: object.__init__() takes no parameters
```

**Comment by pb-cdunn** [comment]
The code here is out-of-date. Please use Bioconda.
```
conda install pb-assembly
conda update --all
```
