### ISSUE TITLE
Installing FALCON 

### ISSUE THREAD

**Issue by anuradhawick** [PacificBiosciences/FALCON-integrate#189]
During the installation I get the following error log;
```
[ERROR]Some tasks are recently_done but not satisfied: set([Node(1-preads_ovl/daligner-runs/j_0000)])
[ERROR]ready: set([])
	submitted: set([])
[ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
Traceback (most recent call last):
  File "/media/anuradhawick/data/Tools/FALCON/path/fc_env_181109/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit==1.0+git.6bb3daa96931aece9bd3742bccc77ad257b7bb65', 'console_scripts', 'fc_run')()
  File "/media/anuradhawick/data/Tools/FALCON/path/fc_env_181109/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 644, in main
    main1(argv[0], args.config, args.logger)
  File "/media/anuradhawick/data/Tools/FALCON/path/fc_env_181109/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 159, in main1
    input_fofn_plf=input_fofn_plf,
  File "/media/anuradhawick/data/Tools/FALCON/path/fc_env_181109/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 579, in run
    dist=Dist(NPROC=1, sge_option=sge_option),
  File "/media/anuradhawick/data/Tools/FALCON/path/fc_env_181109/lib/python2.7/site-packages/falcon_kit/pype.py", line 89, in gen_parallel_tasks
    wf.refreshTargets()
  File "/media/anuradhawick/data/Tools/FALCON/path/fc_env_181109/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 284, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/media/anuradhawick/data/Tools/FALCON/path/fc_env_181109/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 350, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(1-preads_ovl/daligner-runs/j_0000)])
```

I have set my python env to be in `Python 2.7.15 |Anaconda, Inc.`

**Comment by pb-cdunn** [comment]
You need to look for a `stderr` file under `1-preads_ovl/daligner-runs/j_0000`. It's probably something simple.
