### ISSUE TITLE
Falcon run incompletely ended

### ISSUE THREAD

**Issue by chelidphile** [PacificBiosciences/FALCON-integrate#196]
Hi, I started Falcon from raw PacBio reads. It ran two days and ended with this error log.
I am showing the last part only.
Any advice please!!!
```py
  File "/home/hshibata/src/FALCON-integrate/fc_env/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit', 'console_scripts', 'fc_run')()
  File "/yshare2/home/hshibata/src/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 625, in main
    main1(argv[0], args.config, args.logger)
  File "/yshare2/home/hshibata/src/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 153, in main1
    input_fofn_plf=input_fofn_plf,
  File "/yshare2/home/hshibata/src/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 317, in run
    dist=Dist(NPROC=1, job_dict=config['job.step.la']),
  File "/yshare2/home/hshibata/src/FALCON-integrate/FALCON/falcon_kit/pype.py", line 96, in gen_parallel_tasks
    wf.refreshTargets()
  File "/yshare2/home/hshibata/src/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 277, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/yshare2/home/hshibata/src/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 345, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads/daligner-chunks/j_7448), Node(0-rawreads/daligner-chunks/j_8212), Node(0-rawreads/daligner-chunks/j_9547)])
```

**Comment by pb-cdunn** [comment]
You need to look for `stderr` in a failed run-directory, e.g. `0-rawreads/daligner-chunks/j_7448/`

**Comment by chelidphile** [comment]
There you go:
```py
2019-11-07 19:39:33,791 - root - DEBUG - Running "/yshare2/home/hshibata/src/FALCON-integrate/pypeFLOW/pypeflow/do_task.py /yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_d890/task.json"
2019-11-07 19:39:33,793 - root - DEBUG - Checking existence of '/yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_d890/task.json' with timeout=30
2019-11-07 19:39:33,793 - root - DEBUG - Loading JSON from '/yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_d890/task.json'
2019-11-07 19:39:33,795 - root - DEBUG - {u'bash_template_fn': u'template.sh',
 u'inputs': {u'all': u'/yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-split/all-units-of-work.json'},
 u'outputs': {u'one': u'some-units-of-work.json'},
 u'parameters': {u'pypeflow_mb': 4000,
                 u'pypeflow_nproc': 1,
                 u'split_idx': 55440}}
2019-11-07 19:39:33,795 - root - WARNING - CD: '/yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_d890' <- '/yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_d890'
2019-11-07 19:39:33,795 - root - DEBUG - Checking existence of u'/yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-split/all-units-of-work.json' with timeout=30
2019-11-07 19:39:33,795 - root - DEBUG - Checking existence of u'template.sh' with timeout=30
2019-11-07 19:39:33,796 - root - WARNING - CD: '/yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_d890' <- '/yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_d890'
2019-11-07 19:39:33,799 - root - INFO - $('/bin/bash user_script.sh')
hostname
+ hostname
pwd
+ pwd
date
+ date
# Substitution will be similar to snakemake "shell".
python2.7 -m falcon_kit.mains.generic_scatter_one_uow --all-uow-list-fn=/yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-split/all-units-of-work.json --one-uow-list-fn=some-units-of-work.json --split-idx=55440
+ python2.7 -m falcon_kit.mains.generic_scatter_one_uow --all-uow-list-fn=/yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-split/all-units-of-work.json --one-uow-list-fn=some-units-of-work.json --split-idx=55440
INFO:root:"Deserializing from '/yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-split/all-units-of-work.json'"
INFO:root:"  Opened for read: '/yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-split/all-units-of-work.json'"
INFO:root:'  Read 25.1MB as json'
INFO:root:'  Deserialized 55444 records'
INFO:root:'Serializing 1 records'
INFO:root:"  Opened for write: 'some-units-of-work.json'"
INFO:root:'  Serialized to 0.0MB as json'

date
+ date
2019-11-07 19:39:34,673 - root - DEBUG - Call '/bin/bash user_script.sh' returned 0.
2019-11-07 19:39:34,674 - root - WARNING - CD: '/yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_d890' -> '/yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_d890'
2019-11-07 19:39:34,674 - root - DEBUG - Checking existence of u'some-units-of-work.json' with timeout=30
2019-11-07 19:39:34,675 - root - WARNING - CD: '/yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_d890' -> '/yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_d890'

real    0m1.063s
user    0m0.725s
sys     0m0.285s
touch /yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_d890/run.sh.done
+ touch /yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_d890/run.sh.done
+ finish
+ echo 'finish code: 0'
```

**Comment by pb-cdunn** [comment]
You need to look at one of these:

    Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads/daligner-chunks/j_7448), Node(0-rawreads/daligner-chunks/j_8212), Node(0-rawreads/daligner-chunks/j_9547)])

But instead, you posted from `0-rawreads/daligner-chunks/j_d890`. (I _think_ that's what you posted. I had to infer that.) If you look into a _failing_ run-dir, you can probably debug this yourself.

**Comment by chelidphile** [comment]
Oops sorry. Here you go:
```sh
executable=${PYPEFLOW_JOB_START_SCRIPT}
+ executable=/yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_9547/run-Pb23e8a47e1a73e.bash
timeout=${PYPEFLOW_JOB_START_TIMEOUT:-60} # wait 60s by default
+ timeout=60

# Wait up to timeout seconds for the executable to become "executable",
# then exec.
#timeleft = int(timeout)
while [[ ! -x "${executable}" ]]; do
    if [[ "${timeout}" == "0" ]]; then
        echo "timed out waiting for (${executable})"
        exit 77
    fi
    echo "not executable: '${executable}', waiting ${timeout}s"
    sleep 1
    timeout=$((timeout-1))
done
+ [[ ! -x /yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_9547/run-Pb23e8a47e1a73e.bash ]]

/bin/bash ${executable}
+ /bin/bash /yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_9547/run-Pb23e8a47e1a73e.bash
+ '[' '!' -d /yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_9547 ']'
+ cd /yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_9547
+ eval '/bin/bash run.sh'
++ /bin/bash run.sh
export PATH=$PATH:/bin
+ export PATH=/home/hshibata/src/FALCON-integrate/fc_env/bin:/home/hshibata/src/FALCON-integrate/fc_env/bin:/home/hshibata/fc_env_190830/bin:/usr/local/package/minimap/2.17/bin:/usr/local/package/samtools/1.9/bin:/home/geadmin/N1GE/bin/lx-amd64:/usr/local/package/virtuoso/7.2.5/bin:/usr/local/package/ruby/2.5.1/bin:/usr/local/package/r/3.5.0/bin:/usr/local/package/python/2.7.15/bin:/usr/local/package/protobuf/3.6.1/bin:/usr/local/package/postgresql/10.6/bin:/usr/local/package/perl/5.26.1/bin:/usr/local/package/octave/4.4.1/bin:/usr/local/package/nano/4.4/bin:/usr/local/package/mysql/5.7.24/bin:/usr/local/package/mongodb/3.6.9/bin:/usr/local/package/lua/5.3.5/bin:/usr/local/package/llvm/7.0.0/bin:/usr/local/package/java/10_2018-03-20/bin:/usr/local/package/haskell/8.4.3/bin:/usr/local/package/go/1.10.3/bin:/usr/local/package/git/2.20.0/bin:/usr/local/package/gcc/7.3.0/bin:/usr/local/package/ant/1.10.5/bin:/usr/local/hgc/bin:/tmp/10659302.1.lmem.q:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/bin
+ PATH=/home/hshibata/src/FALCON-integrate/fc_env/bin:/home/hshibata/src/FALCON-integrate/fc_env/bin:/home/hshibata/fc_env_190830/bin:/usr/local/package/minimap/2.17/bin:/usr/local/package/samtools/1.9/bin:/home/geadmin/N1GE/bin/lx-amd64:/usr/local/package/virtuoso/7.2.5/bin:/usr/local/package/ruby/2.5.1/bin:/usr/local/package/r/3.5.0/bin:/usr/local/package/python/2.7.15/bin:/usr/local/package/protobuf/3.6.1/bin:/usr/local/package/postgresql/10.6/bin:/usr/local/package/perl/5.26.1/bin:/usr/local/package/octave/4.4.1/bin:/usr/local/package/nano/4.4/bin:/usr/local/package/mysql/5.7.24/bin:/usr/local/package/mongodb/3.6.9/bin:/usr/local/package/lua/5.3.5/bin:/usr/local/package/llvm/7.0.0/bin:/usr/local/package/java/10_2018-03-20/bin:/usr/local/package/haskell/8.4.3/bin:/usr/local/package/go/1.10.3/bin:/usr/local/package/git/2.20.0/bin:/usr/local/package/gcc/7.3.0/bin:/usr/local/package/ant/1.10.5/bin:/usr/local/hgc/bin:/tmp/10659302.1.lmem.q:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/bin
cd /yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_9547
+ cd /yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_9547
/bin/bash task.sh
+ /bin/bash task.sh
2019-11-07 20:12:59,728 - root - DEBUG - Running "/yshare2/home/hshibata/src/FALCON-integrate/pypeFLOW/pypeflow/do_task.py /yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_9547/task.json"
2019-11-07 20:12:59,731 - root - DEBUG - Checking existence of '/yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_9547/task.json' with timeout=30
2019-11-07 20:15:20,119 - root - CRITICAL - Error in /yshare2/home/hshibata/src/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': '/yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_9547/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
```
```py
Traceback (most recent call last):
  File "/usr/local/package/python/2.7.15/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/package/python/2.7.15/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/yshare2/home/hshibata/src/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 250, in <module>
    main()
  File "/yshare2/home/hshibata/src/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 242, in main
    run(**vars(parsed_args))
  File "/yshare2/home/hshibata/src/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 230, in run
    wait_for(json_fn)
  File "/yshare2/home/hshibata/src/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 73, in wait_for
    raise Exception('Timed out waiting for {!r}'.format(fn))
Exception: Timed out waiting for '/yshare2/home/hshibata/Falcon_habu_110619/Falcon_habu_PB_110619/0-rawreads/daligner-chunks/j_9547/task.json'

real    2m20.578s
user    0m0.093s
```

**Comment by pb-cdunn** [comment]
Try deleting `0-rawreads/daligner-chunks/j_9547/` and restarting.

But first, you need a new Bioconda environment, based on `python3.7`. We no longer support `python2.7`, nor `python3.6`.

   /home/hshibata/src/FALCON-integrate/fc_env/bin

... Actually, you are not even using **Bioconda**, so you have completely out-of-date software.

**Comment by pb-cdunn** [comment]
https://github.com/pacificBiosciences/pbbioconda
