### ISSUE TITLE
Falcon fails on some reads (fastq files) but not other

### ISSUE THREAD

**Issue by ragowthaman** [PacificBiosciences/FALCON-integrate#20]
Hi
I installed Falcon-integrate (thanks for the submodule. its awesome!).  I am able to run example ecoli data set and obtained assembled contigs.

However, when I tried with our own data (600,000 fasta fitered_subreads) from 8 smrtcells, it fails. I split the fasta into 20 chunks with 30,000 reads each, it fails. [error below].

Intrestinlgy, I made 10 or 15 fasta files with only 1000 sequences each, then it works. But, If the total fasta sequences reach close to 30,000 it fails. However, the example ecoli data has 3 files of each with 35,000 reads.

I tried both 0.4.0 and 0.4.1 version of Falcon-integrate.

I would appreciate any help/pointers to resolve this issues. Thanks a lot.
Gowthaman

I should note that, it does submit "prepare_rd" job to cluster and it "finishes" too. Subsequently it throw's following error:

```
Your job 241100 ("prepare_rdb.sh-task_build_rdb-task_build_rdb") has been submitted
[INFO]Queued 'task:///autoxfs/ngs/software/PacBio_CentOS/FALCON-integrate_0.3.0/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py/task_build_rdb' ...
[INFO]tick: 8
[INFO]tick: 16
[INFO]tick: 32
[INFO]'/autoxfs/ngs/software/PacBio_CentOS/FALCON-integrate_0.3.0/FALCON-integrate/ldo_test/0-rawreads/rdb_build_done.exit' found.
[WARNING]'/autoxfs/ngs/software/PacBio_CentOS/FALCON-integrate_0.3.0/FALCON-integrate/ldo_test/0-rawreads/rdb_build_done' is missing. job: 'prepare_rdb.sh-task_build_rdb-task_build_rdb' failed!
[INFO]Failure ('fail'). Joining 'task:///autoxfs/ngs/software/PacBio_CentOS/FALCON-integrate_0.3.0/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py/task_build_rdb'...
[ERROR]Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
Traceback (most recent call last):
  File "/autoxfs/ngs/software/PacBio_CentOS/FALCON-integrate_0.3.0/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 531, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/autoxfs/ngs/software/PacBio_CentOS/FALCON-integrate_0.3.0/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 712, in _refreshTargets
    raise TaskFailureError("Counted %d failures." %failedJobCount)
TaskFailureError: 'Counted 1 failures.'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Please wait for all threads / processes to terminate !
! Also, maybe use 'ps' or 'qstat' to check all threads,!
! processes and/or jobs are terminated cleanly.        !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[WARNING]#tasks=2, #alive=0
Traceback (most recent call last):
  File "/autoxfs/ngs/software/PacBio_CentOS/FALCON-integrate_0.3.0/FALCON-integrate/fc_env/bin/fc_run", line 9, in <module>
    load_entry_point('falcon-kit==0.4.0', 'console_scripts', 'fc_run')()
  File "/autoxfs/ngs/software/PacBio_CentOS/FALCON-integrate_0.3.0/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 612, in main
    main1(*argv)
  File "/autoxfs/ngs/software/PacBio_CentOS/FALCON-integrate_0.3.0/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 473, in main1
    wf.refreshTargets([rdb_build_done])
  File "/autoxfs/ngs/software/PacBio_CentOS/FALCON-integrate_0.3.0/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 531, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/autoxfs/ngs/software/PacBio_CentOS/FALCON-integrate_0.3.0/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 712, in _refreshTargets
    raise TaskFailureError("Counted %d failures." %failedJobCount)
pypeflow.controller.TaskFailureError: 'Counted 1 failures.'
```

**Comment by pb-cdunn** [comment]
Check the sge_log directory. Or run it locally and look for `*.log` files under `0-rawreads/`.

**Comment by ragowthaman** [comment]
Thanks Christopher. The log file finds a problem with fasta header. 

```
Adding '4' ...
File 4.fasta, Line 959582: Pacbio header line name inconsisten
```

and that line is where I dont see any inconsistency.....but I will contiue to see if I see any pattern within all problematic headers 

```
>m151031_143221_42134_c100925862550000001823208005121623_s1_p0/109018/0_10852
```

Good headers below look exactly same...

```
>m151027_182500_42134_c100906642550000001823210804301634_s1_p0/110527/0_11717
>m151027_182500_42134_c100906642550000001823210804301634_s1_p0/110527/11762_19058
>m151027_182500_42134_c100906642550000001823210804301634_s1_p0/110528/5895_12043
>m151027_182500_42134_c100906642550000001823210804301634_s1_p0/110529/0_4247
>m151027_182500_42134_c100906642550000001823210804301634_s1_p0/110529/4295_12071
>m151027_182500_42134_c100906642550000001823210804301634_s1_p0/110531/0_10839
```

**Comment by pb-cdunn** [comment]
The prologs don't match. (Line 439 of `DAZZ_DB/fasta2DB.c`.)

```
m...623_s1_p0/...
  !=
m...634_s1_p0/...
```

I don't see how **fasta2DB** or **daligner** could fail from this, but I suppose it might catch real errors sometimes.

**Comment by ragowthaman** [comment]
oh!! Okay!. Thanks Christopher.

Now, I can see, all the reads that are giving this problem has a barcode that is different from that of previous fasta entry in that file.

Does that mean I should split filtered_reads.fasta into many many multifasta files so each contains reads from only one SMRT Cell Barcode (=smrt cell). I also notice ecoli output is like that. One fasta file per smrtcell.
