### ISSUE TITLE
FALCON-integrate 0.6.3 - No module named pwatcher.mains

### ISSUE THREAD

**Issue by fbemm** [PacificBiosciences/FALCON-integrate#60]
Pulled, compiled and started an assembly with 0.6.3 gives me:

```
[ERROR]Task Fred{'URL': 'task:///ebio/abt6_projects9/abt6_software/bin/FALCON-integrate/FALCON/falcon_kit/mains/run1.py/task_build_rdb'} failed with exit-code=99
[INFO]Failure ('fail'). Joining 'task:///ebio/abt6_projects9/abt6_software/bin/FALCON-integrate/FALCON/falcon_kit/mains/run1.py/task_build_rdb'...
...
Exception: Caused by:
Traceback (most recent call last):
  File "/ebio/abt6_projects9/abt6_software/bin/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 523, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/ebio/abt6_projects9/abt6_software/bin/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 740, in _refreshTargets
    raise TaskFailureError("Counted %d failure(s) with 0 successes so far." %failedJobCount)
TaskFailureError: 'Counted 1 failure(s) with 0 successes so far.'
```

pwatcher issues:

```
+ python -m pwatcher.mains.fs_heartbeat --directory=0-rawreads --heartbeat-file=mypwatcher/heartbeats/heartbeat-Jc1f0bbbd29bd8878cfbd16bdd68d84947a44db84c165f248749d241ee5bdb2bd --exit-file=mypwatcher/exits/exit-Jc1f0bbbd29bd8878cfbd16bdd68d84947a44db84c165f248749d241ee5bdb2bd --rate=1 /bin/bash prepare_rdb.sh
#/usr/bin/python: No module named pwatcher.mains
+ echo 99
```

Any idea?

**Comment by fbemm** [comment]
Same with 0.6.4

**Comment by pb-cdunn** [comment]
```
/usr/bin/python: No module named pwatcher.mains
```

If you are using **virtualenv**, then you need to run `. bin/activate` in the virtualenv dir first. That will update your `PATH` to use **python** from the virtualenv bin.
- https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation

**Comment by fbemm** [comment]
I am using the virtualenv!

**Comment by pb-cdunn** [comment]
Then possibly the ENV was not passed to the job on your grid machine. Maybe your job-submission flags need tweaking. You need to tell us your falcon cfg. Then, try running with `job_type=local` to prove that it works without the grid.

**Comment by fbemm** [comment]
Possibly! Should be the "-V" option in my case. What sge job types are submitted? Those are currently configured: Documentation?

```
sge_option_da = -cwd -V -pe parallel 4 -l h_rt=48:0:0 -l h_vmem=25G
sge_option_la = -cwd -V -pe parallel 2 -l h_rt=24:0:0 -l h_vmem=25G
sge_option_pda = -cwd -V -pe parallel 4 -l h_rt=24:0:0 -l h_vmem=25G
sge_option_pla = -cwd -V -pe parallel 2 -l h_rt=24:0:0 -l h_vmem=25G
sge_option_fc = -cwd -V -pe parallel 24 -l h_rt=24:0:0 -l h_vmem=10G
sge_option_cns = -cwd -V -pe parallel 8 -l h_rt=24:0:0 -l h_vmem=10G
```

Since "make test" went fine so it should not be necessary to rerun a full assembly.

**Comment by pb-cdunn** [comment]
What is your `job_type`?

And check `all.log` to learn the command-line used for job-submission.

**Comment by pb-cdunn** [comment]
Then, look into `mypwatcher/jobs/J*/stdout` and examine the ENV, which was dumped via `printenv`. Could you post that here?

**Comment by fbemm** [comment]
``` sh
LC_PAPER=de_DE.UTF-8
SGE_O_TZ=MET
LC_ADDRESS=de_DE.UTF-8
HOSTNAME=node448
LC_MONETARY=de_DE.UTF-8
SGE_TASK_STEPSIZE=undefined
TERM=screen
SHELL=/bin/bash
NHOSTS=1
SGE_O_WORKDIR=/ebio/abt6_projects9/bnap_genome/tardigrade/hd/genome/assembly/falcon-dev/mypwatcher/jobs/Jbd58bf6bd576abb27b9d3432b72a90c9ed51e8c19e70629ed8f610f49e74ac26
TMPDIR=/tmp/5000044.1.long.q
SSH_CLIENT=10.39.103.171 51792 22
SGE_O_HOME=/ebio/abt6/fbemm
PERL5LIB=/ebio/abt6_projects9/abt6_software/bin/proovread/lib:/ebio/abt6/fbemm/perl5/lib/perl5:/ebio/abt6_projects9/abt6_software/bin/proovread/lib:/ebio/abt6/fbemm/perl5/lib/perl5:
SGE_ARCH=lx26-amd64
SGE_CELL=default
LC_NUMERIC=de_DE.UTF-8
PERL_MB_OPT=--install_base "/ebio/abt6/fbemm/perl5"
RESTARTED=0
DB=/ebio/abt6_projects9/abt6_databases/db
SSH_TTY=/dev/pts/5
LC_ALL=en_US.UTF-8
ARC=lx26-amd64
USER=fbemm
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
LC_TELEPHONE=de_DE.UTF-8
LD_LIBRARY_PATH=/ebio/abt6_projects9/abt6_software/bin/blasr/libcpp/pbdata:/ebio/abt6_projects9/abt6_software/bin/blasr/libcpp/hdf:/ebio/abt6_projects9/abt6_software/bin/blasr/libcpp/alignment:/ebio/abt6_projects9/abt6_software/bin/hdf5/lib:/ebio/abt6_projects9/abt6_software/bin/boost/lib:
SGE_TASK_LAST=undefined
QUEUE=long.q
TERMCAP=SC|screen|VT 100/ANSI X3.64 virtual terminal:\
VIRTUAL_ENV=/ebio/abt6_projects9/abt6_software/bin/FALCON-integrate-dev/fc_env
SGE_TASK_ID=undefined
SGE_BINARY_PATH=/usr/sbin/lx26-amd64
MAIL=/var/mail/fbemm
PATH=/usr/local/bin:/usr/bin:/bin
STY=13772.hd-falcon-dev
vga=normal
SGE_STDERR_PATH=/ebio/abt6_projects9/bnap_genome/tardigrade/hd/genome/assembly/falcon-dev/mypwatcher/jobs/Jbd58bf6bd576abb27b9d3432b72a90c9ed51e8c19e70629ed8f610f49e74ac26/stderr
LC_IDENTIFICATION=de_DE.UTF-8
C_INCLUDE_PATH=/ebio/abt6_projects9/abt6_software/bin/hdf5/include:/ebio/abt6_projects9/abt6_software/bin/boost/include:/ebio/abt6_projects9/abt6_software/bin/hdf5/include:/ebio/abt6_projects9/abt6_software/bin/boost/include:
PWD=/ebio/abt6_projects9/bnap_genome/tardigrade/hd/genome/assembly/falcon-dev/mypwatcher/jobs/Jbd58bf6bd576abb27b9d3432b72a90c9ed51e8c19e70629ed8f610f49e74ac26
SGE_STDOUT_PATH=/ebio/abt6_projects9/bnap_genome/tardigrade/hd/genome/assembly/falcon-dev/mypwatcher/jobs/Jbd58bf6bd576abb27b9d3432b72a90c9ed51e8c19e70629ed8f610f49e74ac26/stdout
SGE_ACCOUNT=sge
EDITOR=emacs -nw
LANG=en_US.UTF-8
JOB_SCRIPT=/var/spool/gridengine/execd/node448/job_scripts/5000044
JOB_NAME=Jbd58bf6bd576ab
LC_MEASUREMENT=de_DE.UTF-8
SGE_ROOT=/var/lib/gridengine
TZ=MET
REQNAME=Jbd58bf6bd576ab
SGE_JOB_SPOOL_DIR=/var/spool/gridengine/execd/node448/active_jobs/5000044.1
ENVIRONMENT=BATCH
PE_HOSTFILE=/var/spool/gridengine/execd/node448/active_jobs/5000044.1/pe_hostfile
SHLVL=3
HOME=/ebio/abt6/fbemm
SGE_CWD_PATH=/ebio/abt6_projects9/bnap_genome/tardigrade/hd/genome/assembly/falcon-dev/mypwatcher/jobs/Jbd58bf6bd576abb27b9d3432b72a90c9ed51e8c19e70629ed8f610f49e74ac26
NQUEUES=1
BOOT_IMAGE=bzImage
SGE_O_LOGNAME=fbemm
SF=/ebio/abt6_projects9/abt6_software/bin
SGE_O_MAIL=/var/mail/fbemm
TMP=/tmp/5000044.1.long.q
JOB_ID=5000044
LOGNAME=fbemm
WINDOW=0
PE=parallel
SSH_CONNECTION=10.39.103.171 51792 10.39.6.118 22
LC_CTYPE=en_US.UTF-8
SGE_TASK_FIRST=undefined
LESSOPEN=| /usr/bin/lesspipe %s
SGE_O_PATH=/ebio/abt6_projects9/abt6_software/bin/FALCON-integrate-dev/fc_env/bin:/ebio/abt6_projects9/abt6_software/bin/cmake/bin:/ebio/abt6_projects9/abt6_software/bin/r/bin:/ebio/abt6_projects9/abt6_software/bin/besst/scripts:/ebio/abt6_projects9/abt6_software/bin/besst:/ebio/abt6_projects9/abt6_software/bin/spades/bin/:/ebio/abt6_projects9/abt6_software/bin/nxtrim/:/ebio/abt6_projects9/abt6_software/bin/skewer:/ebio/abt6_projects9/abt6_software/bin/bwa:/ebio/abt6_projects9/abt6_software/bin/samtools/bin:/ebio/abt6_projects9/abt6_software/bin/proovread/util/SeqChuncker/bin:/ebio/abt6_projects9/abt6_software/bin/proovread/util/SeqFilter/bin:/ebio/abt6_projects9/abt6_software/bin/proovread/bin:/ebio/abt6_projects9/abt6_software/bin/cmake/bin:/ebio/abt6_projects9/abt6_software/bin/r/bin:/ebio/abt6_projects9/abt6_software/bin/besst/scripts:/ebio/abt6_projects9/abt6_software/bin/besst:/ebio/abt6_projects9/abt6_software/bin/spades/bin/:/ebio/abt6_projects9/abt6_software/bin/nxtrim/:/ebio/abt6_projects9/abt6_software/bin/skewer:/ebio/abt6_projects9/abt6_software/bin/bwa:/ebio/abt6_projects9/abt6_software/bin/samtools/bin:/ebio/abt6_projects9/abt6_software/bin/proovread/util/SeqChuncker/bin:/ebio/abt6_projects9/abt6_software/bin/proovread/util/SeqFilter/bin:/ebio/abt6_projects9/abt6_software/bin/proovread/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
SGE_O_HOST=burrito
SGE_O_SHELL=/bin/bash
REQUEST=Jbd58bf6bd576ab
NSLOTS=4
LESSCLOSE=/usr/bin/lesspipe %s %s
LC_TIME=de_DE.UTF-8
SGE_STDIN_PATH=/dev/null
PERL_MM_OPT=INSTALL_BASE=/ebio/abt6/fbemm/perl5
LC_NAME=de_DE.UTF-8
_=/usr/bin/printenv
```

**Comment by fbemm** [comment]
```
job_type = SGE
```

**Comment by pb-cdunn** [comment]
```
PATH=/usr/local/bin:/usr/bin:/bin
```

The virtualenv was definitely not passed in. Either `-V` is not working for you, or you did not use python from the virtualenv in the first place. Please let us know when you learn the solution. We can update the `qsub` flags if necessary.

**Comment by pb-cdunn** [comment]
This is interesting:

```
VIRTUAL_ENV=/ebio/abt6_projects9/abt6_software/bin/FALCON-integrate-dev/fc_env
```

That's not what you need at runtime, but it means that the virtualenv was at least created. Are you sure that it's activated in the shell when you started `fc_run`? Could you show the `PATH` in your shell?

**Comment by fbemm** [comment]
That is clear now. Thx! Still the question is which sge_option_XX is it that needs modifications?

```
                       'avoid_text_file_busy': True,
                       'cns_concurrent_jobs': 8,
                       'dazcon': False,
                       'dust': False,
                       'falcon_sense_option': '--output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6',
                       'falcon_sense_skip_contained': False,
                       'fc_ovlp_to_graph_option': ' --min_len 5000',
                       'genome_size': 0,
                       'input_fofn': 'HD_gen.mo.fofn',
                       'input_type': 'raw',
                       'install_prefix': '/ebio/abt6_projects9/abt6_software/bin/FALCON-integrate-dev/fc_env',
                       'job_type': 'SGE',
                       'length_cutoff': 5000,
                       'length_cutoff_pr': 5000,
                       'overlap_filtering_setting': '--max_diff 64 --max_cov 64 --min_cov 2 --n_core 24',
                       'ovlp_DBsplit_option': '-x500 -s400',
                       'ovlp_HPCdaligner_option': '-v -B128 -t32 -h60 -e.96 -l500 -s1000',
                       'ovlp_concurrent_jobs': 64,
                       'pa_DBdust_option': '-w128 -t2.5 -m20',
                       'pa_DBsplit_option': '-x500 -s400',
                       'pa_HPCdaligner_option': '-v -B128 -t16 -e.70 -l1000 -s1000',
                       'pa_concurrent_jobs': 64,
                       'pa_dazcon_option': '-j 4 -x -l 500',
                       'seed_coverage': 20,
                       'sge_option_cns': '-cwd -V -pe parallel 8 -l h_rt=24:0:0 -l h_vmem=10G',
                       'sge_option_da': '-cwd -V -pe parallel 4 -l h_rt=48:0:0 -l h_vmem=25G',
                       'sge_option_fc': '-cwd -V -pe parallel 24 -l h_rt=24:0:0 -l h_vmem=10G',
                       'sge_option_la': '-cwd -V -pe parallel 2 -l h_rt=24:0:0 -l h_vmem=25G',
                       'sge_option_pda': '-cwd -V -pe parallel 4 -l h_rt=24:0:0 -l h_vmem=25G',
                       'sge_option_pla': '-cwd -V -pe parallel 2 -l h_rt=24:0:0 -l h_vmem=25G',
                       'stop_all_jobs_on_failure': False,
                       'target': 'assembly',
                       'use_tmpdir': False},
            'sge_option': '-cwd -V -pe parallel 4 -l h_rt=48:0:0 -l h_vmem=25G'
```

**Comment by fbemm** [comment]
```
. /ebio/abt6_projects9/abt6_software/bin/FALCON-integrate-dev/fc_env/bin/activate
```

``` sh
LD_LIBRARY_PATH=/ebio/abt6_projects9/abt6_software/bin/blasr/libcpp/pbdata:/ebio/abt6_projects9/abt6_software/bin/blasr/libcpp/hdf:/ebio/abt6_projects9/abt6_software/bin/blasr/libcpp/alignment:/ebio/abt6_projects9/abt6_software/bin/hdf5/lib:/ebio/abt6_projects9/abt6_software/bin/boost/lib:
VIRTUAL_ENV=/ebio/abt6_projects9/abt6_software/bin/FALCON-integrate-dev/fc_env
PATH=/ebio/abt6_projects9/abt6_software/bin/FALCON-integrate-dev/fc_env/bin:/ebio/abt6_projects9/abt6_software/bin/cmake/bin:/ebio/abt6_projects9/abt6_software/bin/r/bin:/ebio/abt6_projects9/abt6_software/bin/besst/scripts:/ebio/abt6_projects9/abt6_software/bin/besst:/ebio/abt6_projects9/abt6_software/bin/spades/bin/:/ebio/abt6_projects9/abt6_software/bin/nxtrim/:/ebio/abt6_projects9/abt6_software/bin/skewer:/ebio/abt6_projects9/abt6_software/bin/bwa:/ebio/abt6_projects9/abt6_software/bin/samtools/bin:/ebio/abt6_projects9/abt6_software/bin/proovread/util/SeqChuncker/bin:/ebio/abt6_projects9/abt6_software/bin/proovread/util/SeqFilter/bin:/ebio/abt6_projects9/abt6_software/bin/proovread/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

**Comment by pb-cdunn** [comment]
> Still the question is which sge_option_XX is it that needs modifications?

I don't know. Ask a sysadmin maybe? If you can't find a solution, then we'll change pypeflow to dump the ENV into the run script.

**Comment by fbemm** [comment]
I think we are not speaking about the same thing here. I know that I have to pass "-V" to set the ENV right. So far I have used the "sge_option_XX" parameters in the Falcon config to do that for individual tasks. As it seems there are tasks now,that are not covered by this configuration anymore. And just to mention it 0.5.3 works perfectly fine. Something change on the way to 0.6.3 that is causing this issue.

**Comment by pb-cdunn** [comment]
Maybe you did not run `git submodule update`? Or maybe you need to re-run `make install`, since we have switched to using `pip install -e` for Python (so it will automatically be up-to-date after any `git checkout` without having to re-install). **pypeFLOW**'s `pwatcher` will add `-V` for you when you use `job_type=sge`.

To verify, you need to examine `all.log` to see the actual qsub command. Please do that.

**Comment by fbemm** [comment]
I tested a bit. It seems as the SGE uses a minimalist PATH in my case but puts the right one in $SGE_O_PATH. I have not figured out how to set PATH to SGE_O_PATH so far.

**Comment by pb-jchin** [comment]
This is what I did to make the non-virtualenv thing work.

Our system python default is python 2.6. When I setup virtualenv, I remember to use python2.7 and install everything in the VNEV in user space. I can't install the system one. It took me a while to figure out how to do it.

We have a GNU module of python 2.7, so I load it. This makes the default "python" command pointing to the python2.7 binary.  (If you don't have GNU module, I am not sure how to work around it without VENV now.)  

I install everything following cdunn's wiki page `https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation` . BTW, I typically have minimal `LD_LIBRARY_PATH`, `PATH`, `PYTHONPATH` etc, in my starting environment. It goes through and I can test it.  However, if I restart from a clean shell, I will have to source `default-env.sh` to get the environment up to run it.  

You can check the shebang of the FALCON python scripts are set to the correct python.  If that is the case, I think you don't need to pass the PATH for the python part. I am not sure about how the daligner part is handled yet.

**Comment by fbemm** [comment]
The issues I have is sort of described here: http://arc.liv.ac.uk/pipermail/gridengine-users/2009-October/027563.html Basically I source the falcon env, I can see it on the submission shell, but it is not passed to the job and that makes falcon fail.

**Comment by pb-jchin** [comment]
maybe @pb-cdunn has a better idea, you can probably hard-code the path through `write_sub_script()` inside `FALCON/falcon_kit/bash.py`.

**Comment by fbemm** [comment]
Found a problem and a solution. My .bashrc had these funny lines:

# If not running interactively, don't do anything
case $- in
    _i_) ;;
      *) return;;
esac 

This prevents the .bashrc being loaded after submitting a non-interactive cluster job. I removed it and  PATH is there now. Sourcing the falcon env in the submission shell still does not work instead I source it in the .bashrc meanwhile.

**Comment by pb-cdunn** [comment]
That's interesting. However, we pass the entire environment into the Grid job, via `-V` for SGE:
- https://github.com/PacificBiosciences/pypeFLOW/blob/master/pwatcher/fs_based.py#L268

In general, you need to have `python2.7` in your PATH when you start `fc_run`. However, I notice that we currently run `python` instead of `python2.7` in a couple places. I'll fix that right away, which should fix your problem....
