### ISSUE TITLE
test fail

### ISSUE THREAD

**Issue by qw1mb0** [PacificBiosciences/FALCON-integrate#75]
Hello.
How can i know because of what the error occurs?
I get an error on run 'make test':

``` python
> make -C ./FALCON-make/ test
> make[1]: Вход в каталог /usr/local/src/FALCON-integrate/FALCON-make'
> make -C /usr/local/src/FALCON-integrate/FALCON-examples test
> make[2]: Вход в каталог /usr/local/src/FALCON-integrate/FALCON-examples'
> python -c 'import pypeflow.common; print pypeflow.common'
> <module 'pypeflow.common' from '/usr/local/src/FALCON-integrate/pypeFLOW/pypeflow/common.pyc'>
> python -c 'import falcon_kit; print falcon_kit.falcon'
> <CDLL '/usr/local/src/FALCON-integrate/FALCON/ext_falcon.so', handle 121b9c0 at 7f0858d20350>
> make run-synth0
> make[3]: Вход в каталог /usr/local/src/FALCON-integrate/FALCON-examples'
> git-sym update run/synth0
> mkdir -p /usr/local/src/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/links
> os.symlink('../.git/modules/FALCON-examples/git-sym-local/links', '/usr/local/src/FALCON-integrate/FALCON-examples/.git-sym')
> mkdir -p /usr/local/src/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/cache
> -> in dir 'run/synth0'
> <- back to dir '/usr/local/src/FALCON-integrate/FALCON-examples'
> symlink: 'run/synth0/data/ref.fasta'
> symlink: 'run/synth0/data/synth0.fasta'
> 'run/synth0/data/ref.fasta' -> '../../../.git-sym/synth0.ref.fasta' does not exist
> 'run/synth0/data/synth0.fasta' -> '../../../.git-sym/synth0-circ-20.pb.fasta' does not exist
> -> in dir '/usr/local/src/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/links'
> -> in dir '/usr/local/src/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/cache'
> make -j  -f /usr/local/src/FALCON-integrate/FALCON-examples/git-sym.makefile 'synth0.ref.fasta'
> make[4]: Вход в каталог /usr/local/src/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/cache'
> curl -L https://www.dropbox.com/s/jz0m0n2a1b19xyd/from.fasta.gz | zcat > synth0.ref.fasta
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100  1694  100  1694    0     0   1003      0  0:00:01  0:00:01 --:--:--     0
> #cp -f /lustre/hpcprod/cdunn/data/synth0/from.fasta synth0.ref.fasta
> make[4]: Выход из каталога /usr/local/src/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/cache'
> make -j  -f /usr/local/src/FALCON-integrate/FALCON-examples/git-sym.makefile 'synth0-circ-20.pb.fasta'
> make[4]: Вход в каталог /usr/local/src/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/cache'
> curl -L https://www.dropbox.com/s/bjhcvp05u46o2qy/circ-20.pb.fasta.gz | zcat > synth0-circ-20.pb.fasta
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100 13565  100 13565    0     0   8352      0  0:00:01  0:00:01 --:--:--  8352
> #cp -f /lustre/hpcprod/cdunn/data/synth0/circ-20.pb.fasta synth0-circ-20.pb.fasta
> make[4]: Выход из каталога /usr/local/src/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/cache'
> <- back to dir '/usr/local/src/FALCON-integrate/.git/modules/FALCON-examples/git-sym-local/links'
> os.symlink('../cache/synth0-circ-20.pb.fasta', 'synth0-circ-20.pb.fasta')
> os.symlink('../cache/synth0.ref.fasta', 'synth0.ref.fasta')
> <- back to dir '/usr/local/src/FALCON-integrate/FALCON-examples'
> git-sym show run/synth0
> -> in dir 'run/synth0'
> <- back to dir '/usr/local/src/FALCON-integrate/FALCON-examples'
> symlink: 'run/synth0/data/ref.fasta'
> symlink: 'run/synth0/data/synth0.fasta'
> . run/synth0/data/ref.fasta   .git-sym/synth0.ref.fasta
> . run/synth0/data/synth0.fasta    .git-sym/synth0-circ-20.pb.fasta
> git-sym check run/synth0
> -> in dir 'run/synth0'
> <- back to dir '/usr/local/src/FALCON-integrate/FALCON-examples'
> symlink: 'run/synth0/data/ref.fasta'
> symlink: 'run/synth0/data/synth0.fasta'
> cd run/synth0; fc_run.py fc_run.cfg logging.ini
> 2016-07-21 19:11:48,531[INFO] Setup logging from file "logging.ini".
> 2016-07-21 19:11:48,532[INFO] fc_run started with configuration fc_run.cfg
> 2016-07-21 19:11:48,532[INFO]  No target specified, assuming "assembly" as target 
> /usr/local/src/FALCON-integrate/FALCON/falcon_kit/run_support.py:320: UserWarning: Unexpected keys in input config: set(['jobqueue'])
>   warnings.warn("Unexpected keys in input config: %s" %repr(unused))
> 2016-07-21 19:11:49,023[INFO] # of tasks in complete graph: 1
> 2016-07-21 19:11:49,023[INFO] tick: 1, #updatedTasks: 0, sleep_time=0.000000
> 2016-07-21 19:11:49,025[INFO] tick: 2, #updatedTasks: 0, sleep_time=0.100000
> 2016-07-21 19:11:49,025[INFO] Running task from function task_make_fofn_abs_raw()
> 2016-07-21 19:11:49,025[WARNING] Missing taskObj.generated_script_fn for task. Maybe we did not need it? Skipping and continuing.
> 2016-07-21 19:11:49,126[INFO] Queued 'task:///usr/local/src/FALCON-integrate/FALCON/falcon_kit/mains/run1.py/task_make_fofn_abs_raw' ...
> 2016-07-21 19:11:49,126[INFO] Success ('done'). Joining 'task:///usr/local/src/FALCON-integrate/FALCON/falcon_kit/mains/run1.py/task_make_fofn_abs_raw'...
> 2016-07-21 19:11:49,127[INFO] _refreshTargets() finished with no thread running and no new job to submit
> 2016-07-21 19:11:49,136[INFO] # of tasks in complete graph: 2
> 2016-07-21 19:11:49,136[INFO] tick: 1, #updatedTasks: 0, sleep_time=0.000000
> 2016-07-21 19:11:49,140[INFO] tick: 2, #updatedTasks: 0, sleep_time=0.100000
> 2016-07-21 19:11:49,140[INFO] Running task from function task_build_rdb()
> 2016-07-21 19:11:49,141[INFO] script_fn:'/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/prepare_rdb.sh'
> 2016-07-21 19:11:49,141[INFO] jobid=J299d53b05cceaa84be81e6ba9e5d351c7fbfd7c5fe430a4b7e45414be9dcc43b
> 2016-07-21 19:11:49,142[INFO] starting job Job(jobid='J299d53b05cceaa84be81e6ba9e5d351c7fbfd7c5fe430a4b7e45414be9dcc43b', cmd='/bin/bash prepare_rdb.sh', rundir='/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads', options={'sge_option': '-pe smp 8 -q production', 'job_type': None})
> 2016-07-21 19:11:49,146[INFO] Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='J299d53b05cceaa84be81e6ba9e5d351c7fbfd7c5fe430a4b7e45414be9dcc43b', cmd='/bin/bash prepare_rdb.sh', rundir='/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads', options={'sge_option': '-pe smp 8 -q production', 'job_type': None}), lang_exe='/bin/bash'))
> 2016-07-21 19:11:49,248[INFO] Queued 'task:///usr/local/src/FALCON-integrate/FALCON/falcon_kit/mains/run1.py/task_build_rdb' ...
> 2016-07-21 19:11:49,249[INFO] tick: 4, #updatedTasks: 1, sleep_time=0.100000
> 2016-07-21 19:11:49,552[INFO] Success ('done'). Joining 'task:///usr/local/src/FALCON-integrate/FALCON/falcon_kit/mains/run1.py/task_build_rdb'...
> 2016-07-21 19:11:49,553[INFO] _refreshTargets() finished with no thread running and no new job to submit
> 2016-07-21 19:11:49,554[INFO] Skip LAcheck after daligner? True
> 2016-07-21 19:11:49,568[INFO] # of tasks in complete graph: 5
> 2016-07-21 19:11:49,569[INFO] tick: 1, #updatedTasks: 0, sleep_time=0.000000
> 2016-07-21 19:11:49,580[INFO] tick: 2, #updatedTasks: 0, sleep_time=0.100000
> 2016-07-21 19:11:49,580[INFO] Running task from function task_run_daligner()
> 2016-07-21 19:11:49,581[INFO] script_fn:'/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0000/rj_0000.sh'
> 2016-07-21 19:11:49,581[INFO] jobid=J864db7ee3cf19f8492f4217d6167432659b8468f0b43fd02ad1f15d4cb814bd4
> 2016-07-21 19:11:49,581[INFO] Running task from function task_run_daligner()
> 2016-07-21 19:11:49,581[INFO] script_fn:'/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/rj_0001.sh'
> 2016-07-21 19:11:49,581[INFO] jobid=Jee5d3488f229161429a485b0f941be8840bf4479d8493bc1878a8c8d0923aff3
> 2016-07-21 19:11:49,582[INFO] starting job Job(jobid='Jee5d3488f229161429a485b0f941be8840bf4479d8493bc1878a8c8d0923aff3', cmd='/bin/bash rj_0001.sh', rundir='/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001', options={'sge_option': '-pe smp 8 -q production', 'job_type': None})
> 2016-07-21 19:11:49,586[INFO] Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='Jee5d3488f229161429a485b0f941be8840bf4479d8493bc1878a8c8d0923aff3', cmd='/bin/bash rj_0001.sh', rundir='/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001', options={'sge_option': '-pe smp 8 -q production', 'job_type': None}), lang_exe='/bin/bash'))
> 2016-07-21 19:11:49,586[INFO] starting job Job(jobid='J864db7ee3cf19f8492f4217d6167432659b8468f0b43fd02ad1f15d4cb814bd4', cmd='/bin/bash rj_0000.sh', rundir='/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0000', options={'sge_option': '-pe smp 8 -q production', 'job_type': None})
> 2016-07-21 19:11:49,589[INFO] Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='J864db7ee3cf19f8492f4217d6167432659b8468f0b43fd02ad1f15d4cb814bd4', cmd='/bin/bash rj_0000.sh', rundir='/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0000', options={'sge_option': '-pe smp 8 -q production', 'job_type': None}), lang_exe='/bin/bash'))
> 2016-07-21 19:11:49,693[INFO] Queued 'task://localhost/d_0000_raw_reads' ...
> 2016-07-21 19:11:49,694[INFO] Queued 'task://localhost/d_0001_raw_reads' ...
> 2016-07-21 19:11:49,696[INFO] tick: 4, #updatedTasks: 2, sleep_time=0.100000
> 2016-07-21 19:11:49,800[ERROR] Task Fred{'URL': 'task://localhost/d_0001_raw_reads'} failed with exit-code=256
> 2016-07-21 19:11:49,800[ERROR] Task Fred{'URL': 'task://localhost/d_0000_raw_reads'} failed with exit-code=256
> 2016-07-21 19:11:50,001[INFO] Failure ('fail'). Joining 'task://localhost/d_0001_raw_reads'...
> 2016-07-21 19:11:50,001[INFO] Failure ('fail'). Joining 'task://localhost/d_0000_raw_reads'...
> 2016-07-21 19:11:50,002[CRITICAL] Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
> /usr/local/src/FALCON-integrate/pypeFLOW/pypeflow/controller.py:537: UserWarning: 
>             "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
>             "! Please wait for all threads / processes to terminate !"
>             "! Also, maybe use 'ps' or 'qstat' to check all threads,!"
>             "! processes and/or jobs are terminated cleanly.        !"
>             "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
>             
>   warnings.warn(shutdown_msg)
> 2016-07-21 19:11:50,003[WARNING] #tasks=2, #alive=0
> Traceback (most recent call last):
>   File "/usr/local/src/FALCON-integrate/fc_env/bin/fc_run.py", line 6, in <module>
>     exec(compile(open(__file__).read(), __file__, 'exec'))
>   File "/usr/local/src/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
>     main(sys.argv)
>   File "/usr/local/src/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 561, in main
>     main1(argv[0], args.config, args.logger)
>   File "/usr/local/src/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 327, in main1
>     setNumThreadAllowed=PypeProcWatcherWorkflow.setNumThreadAllowed)
>   File "/usr/local/src/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 404, in run
>     wf.refreshTargets(exitOnFailure=exitOnFailure)
>   File "/usr/local/src/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 548, in refreshTargets
>     raise Exception('Caused by:\n' + tb)
> Exception: Caused by:
> Traceback (most recent call last):
>   File "/usr/local/src/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 523, in refreshTargets
>     rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
>   File "/usr/local/src/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 740, in _refreshTargets
>     raise TaskFailureError("Counted %d failure(s) with 0 successes so far." %failedJobCount)
> TaskFailureError: 'Counted 2 failure(s) with 0 successes so far.'
> 
> make[3]: *** [run-synth0] Ошибка 1
> make[3]: Выход из каталога /usr/local/src/FALCON-integrate/FALCON-examples'
> make[2]: *** [test] Ошибка 2
> make[2]: Выход из каталога /usr/local/src/FALCON-integrate/FALCON-examples'
> make[1]: *** [test] Ошибка 2
> make[1]: Выход из каталога /usr/local/src/FALCON-integrate/FALCON-make'
> make: *** [test] Ошибка 2
```

But in another server all ok on testing.

**Comment by pb-cdunn** [comment]
```
 [ERROR] Task Fred{'URL': 'task://localhost/d_0001_raw_reads'} failed with exit-code=256
```

You have to look into the directory for that task.

```
cd 0-rawreads/job_00001
cat pwatcher.dir/stderr
```

I'll bet you need to set environment variables.

**Comment by qw1mb0** [comment]
I don't see any error, can you explai this output?

```
> [root@falcon job_0001]# cat pwatcher.dir/stderr 
> + python2.7 -m pwatcher.mains.fs_heartbeat --directory=/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001 --heartbeat-file=/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/mypwatcher/heartbeats/heartbeat-Jee5d3488f229161429a485b0f941be8840bf4479d8493bc1878a8c8d0923aff3 --exit-file=/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/mypwatcher/exits/exit-Jee5d3488f229161429a485b0f941be8840bf4479d8493bc1878a8c8d0923aff3 --rate=10.0 /bin/bash rj_0001.sh
> Namespace(command=['/bin/bash', 'rj_0001.sh'], directory='/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001', exit_file='/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/mypwatcher/exits/exit-Jee5d3488f229161429a485b0f941be8840bf4479d8493bc1878a8c8d0923aff3', heartbeat_file='/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/mypwatcher/heartbeats/heartbeat-Jee5d3488f229161429a485b0f941be8840bf4479d8493bc1878a8c8d0923aff3', rate=10.0)
> 
> cwd:'/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001'
> hostname=falcon.c.inside-dna.internal
> heartbeat_fn='/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/mypwatcher/heartbeats/heartbeat-Jee5d3488f229161429a485b0f941be8840bf4479d8493bc1878a8c8d0923aff3'
> exit_fn='/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/mypwatcher/exits/exit-Jee5d3488f229161429a485b0f941be8840bf4479d8493bc1878a8c8d0923aff3'
> sleep_s=10.0
> before setpgid: pid=2812 pgid=2719
>  after setpgid: pid=2812 pgid=2812
> alive? False
> alive? True pid=2812 pgid=2812
> In cwd: /usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001, Blocking call: '/bin/bash rj_0001.sh'
> cd /usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001
> + cd /usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001
> trap 'touch /usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/job_0001_done.exit' EXIT
> + trap 'touch /usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/job_0001_done.exit' EXIT
> ls -il rj_0001.sub.sh
> + ls -il rj_0001.sub.sh
> hostname
> + hostname
> ls -il rj_0001.sub.sh
> + ls -il rj_0001.sub.sh
> time /bin/bash ./rj_0001.sub.sh
> + /bin/bash ./rj_0001.sub.sh
> 
> shopt -s dotglob
> + shopt -s dotglob
> rm -rf /tmp/root/falcontmp//usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/43a04bab737056a70db652e7eff4b82c
> + rm -rf /tmp/root/falcontmp//usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/43a04bab737056a70db652e7eff4b82c
> mkdir -p /tmp/root/falcontmp//usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/43a04bab737056a70db652e7eff4b82c
> + mkdir -p /tmp/root/falcontmp//usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/43a04bab737056a70db652e7eff4b82c
> cd /tmp/root/falcontmp//usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/43a04bab737056a70db652e7eff4b82c
> + cd /tmp/root/falcontmp//usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/43a04bab737056a70db652e7eff4b82c
> for target in /usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/* ; do ln -s $target . ; done
> + for target in '/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/*'
> + ln -s /usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/pwatcher.dir .
> + for target in '/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/*'
> + ln -s /usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/rj_0001.sh .
> + for target in '/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/*'
> + ln -s /usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/rj_0001.sub.sh .
> + for target in '/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/*'
> + ln -s /usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/rj_0001.xsub.sh .
> time /bin/bash ./rj_0001.xsub.sh
> + /bin/bash ./rj_0001.xsub.sh
> 
> db_dir=/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads
> + db_dir=/usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads
> ln -sf ${db_dir}/.raw_reads.bps .
> + ln -sf /usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/.raw_reads.bps .
> ln -sf ${db_dir}/.raw_reads.idx .
> + ln -sf /usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/.raw_reads.idx .
> ln -sf ${db_dir}/raw_reads.db .
> + ln -sf /usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/raw_reads.db .
> ln -sf ${db_dir}/.raw_reads.dust.anno .
> + ln -sf /usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/.raw_reads.dust.anno .
> ln -sf ${db_dir}/.raw_reads.dust.data .
> + ln -sf /usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/.raw_reads.dust.data .
> daligner -v -w1 -h1 -t50 -H2000 -e0.99 -l1 -s1000 raw_reads.2 raw_reads.1 raw_reads.2
> + daligner -v -w1 -h1 -t50 -H2000 -e0.99 -l1 -s1000 raw_reads.2 raw_reads.1 raw_reads.2
> set +e
> + set +e
> LAcheck -v raw_reads *.las
> + LAcheck -v raw_reads raw_reads.1.raw_reads.2.C0.las raw_reads.1.raw_reads.2.C1.las raw_reads.1.raw_reads.2.C2.las raw_reads.1.raw_reads.2.C3.las raw_reads.1.raw_reads.2.N0.las raw_reads.1.raw_reads.2.N1.las raw_reads.1.raw_reads.2.N2.las raw_reads.1.raw_reads.2.N3.las raw_reads.2.raw_reads.1.C0.las raw_reads.2.raw_reads.1.C1.las raw_reads.2.raw_reads.1.C2.las raw_reads.2.raw_reads.1.C3.las raw_reads.2.raw_reads.1.N0.las raw_reads.2.raw_reads.1.N1.las raw_reads.2.raw_reads.1.N2.las raw_reads.2.raw_reads.1.N3.las raw_reads.2.raw_reads.2.C0.las raw_reads.2.raw_reads.2.C1.las raw_reads.2.raw_reads.2.C2.las raw_reads.2.raw_reads.2.C3.las raw_reads.2.raw_reads.2.N0.las raw_reads.2.raw_reads.2.N1.las raw_reads.2.raw_reads.2.N2.las raw_reads.2.raw_reads.2.N3.las
>   raw_reads.1.raw_reads.2.C0: 0 all OK
>   raw_reads.1.raw_reads.2.C1: 0 all OK
>   raw_reads.1.raw_reads.2.C2: 0 all OK
>   raw_reads.1.raw_reads.2.C3: 0 all OK
>   raw_reads.1.raw_reads.2.N0: 128 all OK
>   raw_reads.1.raw_reads.2.N1: 107 all OK
>   raw_reads.1.raw_reads.2.N2: 116 all OK
>   raw_reads.1.raw_reads.2.N3: 105 all OK
>   raw_reads.2.raw_reads.1.C0: 0 all OK
>   raw_reads.2.raw_reads.1.C1: 0 all OK
>   raw_reads.2.raw_reads.1.C2: 0 all OK
>   raw_reads.2.raw_reads.1.C3: 0 all OK
>   raw_reads.2.raw_reads.1.N0: 128 all OK
>   raw_reads.2.raw_reads.1.N1: 107 all OK
>   raw_reads.2.raw_reads.1.N2: 116 all OK
>   raw_reads.2.raw_reads.1.N3: 105 all OK
>   raw_reads.2.raw_reads.2.C0: 0 all OK
>   raw_reads.2.raw_reads.2.C1: 0 all OK
>   raw_reads.2.raw_reads.2.C2: 0 all OK
>   raw_reads.2.raw_reads.2.C3: 0 all OK
>   raw_reads.2.raw_reads.2.N0: 76 all OK
>   raw_reads.2.raw_reads.2.N1: 40 all OK
>   raw_reads.2.raw_reads.2.N2: 60 all OK
>   raw_reads.2.raw_reads.2.N3: 52 all OK
> set -e
> + set -e
> LAsort -v raw_reads.1.raw_reads.2.C0 raw_reads.1.raw_reads.2.N0 raw_reads.1.raw_reads.2.C1 raw_reads.1.raw_reads.2.N1 raw_reads.1.raw_reads.2.C2 raw_reads.1.raw_reads.2.N2 raw_reads.1.raw_reads.2.C3 raw_reads.1.raw_reads.2.N3 && LAmerge -v L1.1.2 raw_reads.1.raw_reads.2.C0.S raw_reads.1.raw_reads.2.N0.S raw_reads.1.raw_reads.2.C1.S raw_reads.1.raw_reads.2.N1.S raw_reads.1.raw_reads.2.C2.S raw_reads.1.raw_reads.2.N2.S raw_reads.1.raw_reads.2.C3.S raw_reads.1.raw_reads.2.N3.S
> + LAsort -v raw_reads.1.raw_reads.2.C0 raw_reads.1.raw_reads.2.N0 raw_reads.1.raw_reads.2.C1 raw_reads.1.raw_reads.2.N1 raw_reads.1.raw_reads.2.C2 raw_reads.1.raw_reads.2.N2 raw_reads.1.raw_reads.2.C3 raw_reads.1.raw_reads.2.N3
> + LAmerge -v L1.1.2 raw_reads.1.raw_reads.2.C0.S raw_reads.1.raw_reads.2.N0.S raw_reads.1.raw_reads.2.C1.S raw_reads.1.raw_reads.2.N1.S raw_reads.1.raw_reads.2.C2.S raw_reads.1.raw_reads.2.N2.S raw_reads.1.raw_reads.2.C3.S raw_reads.1.raw_reads.2.N3.S
> LAmerge: Out of memory (Allocating LAmerge blocks)
> touch /usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/job_0001_done.exit
> + touch /usr/local/src/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/job_0001/job_0001_done.exit
>  returned: 256
```

**Comment by pb-cdunn** [comment]
```
LAmerge: Out of memory (Allocating LAmerge blocks)
```

This is for synth0? That is a very small test-case. Try running locally first (`job_type=local` in your `.cfg`, the main argument to `fc_run`). You can also try providing some sge options with modest memory requirements.

**Comment by qw1mb0** [comment]
Oooh... thanks.
But when I run fc_run.py -h I take another error:

``` python
> Traceback (most recent call last):
>   File "/srv/dna_tools/falcon-0.7.3/fc_env/bin/fc_run.py", line 4, in <module>
>     __import__('pkg_resources').require('falcon-kit==0.7+git.85e41a6ab3bbeaece25f43e47c8f9a2cb9feb31a')
>   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
>     @_call_aside
>   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 635, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 829, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'falcon-kit==0.7+git.85e41a6ab3bbeaece25f43e47c8f9a2cb9feb31a' distribution was not found and is required by the application
```

**Comment by pb-cdunn** [comment]
It's hard to debug installation problems remotely. If you followed the Installation wiki, then you will need:

```
PATH
PYTHONUSERBASE
and you might need to `unset PYTHONPATH` if you have old versions somewhere.
```

See the `.sh` file that you sourced while installing.

**Comment by ggosa** [comment]
hello：
after i typed"make test" i get an error:
![image](https://cloud.githubusercontent.com/assets/20499250/18316705/432a9844-754e-11e6-912b-aeacf6a75168.png)
then i saw pwatcher.dir/stderr

``` sh
Adding 'synth0.fasta' ...
File synth0.fasta, Line 1: First header in fasta file is missing
touch /opt/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/rdb_build_done.exit
+ touch /opt/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/rdb_build_done.exit
 returned: 256
```

what should i do?

**Comment by pb-cdunn** [comment]
@ggosa, it seems that you are missing the contents of the symlink for `synth0.fasta`. You need to run `git-sym update` in the `synth0` directory.
