### ISSUE TITLE
falcon not running after updating

### ISSUE THREAD

**Issue by mahulchak** [PacificBiosciences/FALCON-integrate#85]
Hello,
I have been using a version from earlier this year and updated it today. AFter updating, however, falcon is crashing with the following error message:

```
/falcon/0-rawreads', options={'job_queue': None, 'sge_option': '-q bsg,jje,bio,pub64,pub128i -pe openmp 32', 'job_type': None}), lang_exe='/bin/bash'))
[ERROR]Task Fred{'URL': 'task:///dfs2/temp/bio/mchakrab/pacbio/FALCON-integrate/FALCON/falcon_kit/mains/run1.py/task_build_rdb'} failed with exit-code=99
[INFO]Queued 'task:///dfs2/temp/bio/mchakrab/pacbio/FALCON-integrate/FALCON/falcon_kit/mains/run1.py/task_build_rdb' ...
[INFO]Failure ('fail'). Joining 'task:///dfs2/temp/bio/mchakrab/pacbio/FALCON-integrate/FALCON/falcon_kit/mains/run1.py/task_build_rdb'...
[CRITICAL]Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
/dfs2/temp/bio/mchakrab/pacbio/FALCON-integrate/pypeFLOW/pypeflow/controller.py:537: UserWarning: 
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            "! Please wait for all threads / processes to terminate !"
            "! Also, maybe use 'ps' or 'qstat' to check all threads,!"
            "! processes and/or jobs are terminated cleanly.        !"
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

  warnings.warn(shutdown_msg)
[WARNING]#tasks=1, #alive=0
Traceback (most recent call last):
  File "/dfs1/bio/mchakrab/pacbio/FALCON-integrate/fc_env/bin/fc_run.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/dfs2/temp/bio/mchakrab/pacbio/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/dfs2/temp/bio/mchakrab/pacbio/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 576, in main
    main1(argv[0], args.config, args.logger)
  File "/dfs2/temp/bio/mchakrab/pacbio/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 353, in main1
    setNumThreadAllowed=PypeProcWatcherWorkflow.setNumThreadAllowed)
  File "/dfs2/temp/bio/mchakrab/pacbio/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 410, in run
    wf.refreshTargets([rdb_build_done])
  File "/dfs2/temp/bio/mchakrab/pacbio/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 548, in refreshTargets
    raise Exception('Caused by:\n' + tb)
Exception: Caused by:
Traceback (most recent call last):
  File "/dfs2/temp/bio/mchakrab/pacbio/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 523, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/dfs2/temp/bio/mchakrab/pacbio/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 740, in _refreshTargets
    raise TaskFailureError("Counted %d failure(s) with 0 successes so far." %failedJobCount)
TaskFailureError: 'Counted 1 failure(s) with 0 successes so far.'
```

Do you know what is going wrong? Does that task name "/dfs2/temp/bio/mchakrab/pacbio/FALCON-integrate/FALCON/falcon_kit/mains/run1.py/task_build_rdb" look normal to you?

Thanks.
Mahul

**Comment by pb-cdunn** [comment]
It's failing in task `build_rdb`, which (not obviously, unfortunately) runs in `0-rawreads/`. So look in `0-rawreads/pwatcher.dir/stderr`. You probably have a very simply integration problem.

**Comment by pb-cdunn** [comment]
If you know the fix, please post it for others who may run into the same problem.

**Comment by mahulchak** [comment]
I had to add the executables to the PATH.
