### ISSUE TITLE
Falcon fails during  report_pre_assembly 

### ISSUE THREAD

**Issue by KatarzynaGraczyk** [PacificBiosciences/FALCON-integrate#86]
Hello, 
I have been running FALCON-integrate on a local server. I tested  ecoli data and program works fine, but when I used different dataset I got this bug:

```
[INFO]Setup logging from file "None".
[INFO]fc_run started with configuration fc_input.cfg
[INFO] No target specified, assuming "assembly" as target 
/usr/local/lib/python2.7/dist-packages/falcon_kit-0.7+git.54779b25532a4e1ace230013fe25f5c51a43ddaa-py2.7-linux-x86_64.egg/falcon_kit/run_support.py:330: UserWarning: Unexpected keys in input config: set(['jobqueue', 'genome_length'])
  warnings.warn("Unexpected keys in input config: %s" %repr(unused))
[INFO]# of tasks in complete graph: 1
[INFO]tick: 1, #updatedTasks: 0, sleep_time=0.000000
[INFO]tick: 2, #updatedTasks: 0, sleep_time=0.100000
[INFO]Running task from function task_make_fofn_abs_raw()
[WARNING]Missing taskObj.generated_script_fn for task. Maybe we did not need it? Skipping and continuing.
[INFO]Queued 'task:///usr/local/lib/python2.7/dist-packages/falcon_kit-0.7+git.54779b25532a4e1ace230013fe25f5c51a43ddaa-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py/task_make_fofn_abs_raw' ...
[INFO]Success ('done'). Joining 'task:///usr/local/lib/python2.7/dist-packages/falcon_kit-0.7+git.54779b25532a4e1ace230013fe25f5c51a43ddaa-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py/task_make_fofn_abs_raw'...
[INFO]_refreshTargets() finished with no thread running and no new job to submit
[INFO]# of tasks in complete graph: 2
[INFO]tick: 1, #updatedTasks: 0, sleep_time=0.000000
[INFO]tick: 2, #updatedTasks: 0, sleep_time=0.100000
[INFO]Running task from function task_build_rdb()
[INFO]script_fn:'/data/0-rawreads/prepare_rdb.sh'
[INFO]jobid=Jb636842bb5b122061efc08bc77ead594f3e32454939e081b38b40222e722533d
[INFO]starting job Job(jobid='Jb636842bb5b122061efc08bc77ead594f3e32454939e081b38b40222e722533d', cmd='/bin/bash prepare_rdb.sh', rundir='/data/0-rawreads', options={'job_queue': None, 'sge_option': '', 'job_type': None})
[INFO]Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='Jb636842bb5b122061efc08bc77ead594f3e32454939e081b38b40222e722533d', cmd='/bin/bash prepare_rdb.sh', rundir='/data/0-rawreads', options={'job_queue': None, 'sge_option': '', 'job_type': None}), lang_exe='/bin/bash'))
[INFO]Queued 'task:///usr/local/lib/python2.7/dist-packages/falcon_kit-0.7+git.54779b25532a4e1ace230013fe25f5c51a43ddaa-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py/task_build_rdb' ...
[INFO]tick: 4, #updatedTasks: 1, sleep_time=0.100000
[INFO]tick: 8, #updatedTasks: 1, sleep_time=0.500000
[INFO]Success ('done'). Joining 'task:///usr/local/lib/python2.7/dist-packages/falcon_kit-0.7+git.54779b25532a4e1ace230013fe25f5c51a43ddaa-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py/task_build_rdb'...
[INFO]_refreshTargets() finished with no thread running and no new job to submit
[INFO]Skip LAcheck after daligner? False
[INFO]# of tasks in complete graph: 4
[INFO]tick: 1, #updatedTasks: 0, sleep_time=0.000000
[INFO]tick: 2, #updatedTasks: 0, sleep_time=0.100000
[INFO]Running task from function task_run_daligner()
[INFO]script_fn:'/data/0-rawreads/job_0000/rj_0000.sh'
[INFO]jobid=Jdcce9e904b4b8e784ed34c7a3bdd45525bb1a50b5f8a5d340b087306fd1f3dc2
[INFO]starting job Job(jobid='Jdcce9e904b4b8e784ed34c7a3bdd45525bb1a50b5f8a5d340b087306fd1f3dc2', cmd='/bin/bash rj_0000.sh', rundir='/data/0-rawreads/job_0000', options={'job_queue': None, 'sge_option': '', 'job_type': None})
[INFO]Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='Jdcce9e904b4b8e784ed34c7a3bdd45525bb1a50b5f8a5d340b087306fd1f3dc2', cmd='/bin/bash rj_0000.sh', rundir='/data/0-rawreads/job_0000', options={'job_queue': None, 'sge_option': '', 'job_type': None}), lang_exe='/bin/bash'))
[INFO]Queued 'task://localhost/d_0000_raw_reads' ...
[INFO]tick: 4, #updatedTasks: 1, sleep_time=0.100000
[INFO]tick: 8, #updatedTasks: 1, sleep_time=0.500000
[INFO]tick: 16, #updatedTasks: 1, sleep_time=1.000000
[INFO]tick: 32, #updatedTasks: 1, sleep_time=1.000000
[INFO]tick: 64, #updatedTasks: 1, sleep_time=1.000000
[INFO]Success ('done'). Joining 'task://localhost/d_0000_raw_reads'...
[INFO]Running task from function task_daligner_gather()
[INFO]Symlink .las files for further merging:
{'/data/0-rawreads/m_00001': ['/data/0-rawreads/job_0000/raw_reads.1.las']}
[WARNING]Missing taskObj.generated_script_fn for task. Maybe we did not need it? Skipping and continuing.
[INFO]Queued 'task://localhost/rda_check' ...
[INFO]Success ('done'). Joining 'task://localhost/rda_check'...
[INFO]_refreshTargets() finished with no thread running and no new job to submit
[INFO]# of tasks in complete graph: 5
[INFO]tick: 1, #updatedTasks: 0, sleep_time=0.000000
[INFO]tick: 2, #updatedTasks: 0, sleep_time=0.100000
[INFO]Running task from function task_run_las_merge()
[INFO]script_fn:'/data/0-rawreads/m_00001/rp_00001.sh'
[INFO]jobid=J43dcdc99e7a92c95ac5b10261b0d61a09309e092b438001395334551d39003e4
[INFO]starting job Job(jobid='J43dcdc99e7a92c95ac5b10261b0d61a09309e092b438001395334551d39003e4', cmd='/bin/bash rp_00001.sh', rundir='/data/0-rawreads/m_00001', options={'job_queue': None, 'sge_option': '', 'job_type': None})
[INFO]Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='J43dcdc99e7a92c95ac5b10261b0d61a09309e092b438001395334551d39003e4', cmd='/bin/bash rp_00001.sh', rundir='/data/0-rawreads/m_00001', options={'job_queue': None, 'sge_option': '', 'job_type': None}), lang_exe='/bin/bash'))
[INFO]Queued 'task://localhost/m_00001_raw_reads' ...
[INFO]Success ('done'). Joining 'task://localhost/m_00001_raw_reads'...
[INFO]tick: 4, #updatedTasks: 1, sleep_time=0.000000
[INFO]_refreshTargets() finished with no thread running and no new job to submit
[INFO]# of tasks in complete graph: 8
[INFO]tick: 1, #updatedTasks: 0, sleep_time=0.000000
[INFO]tick: 2, #updatedTasks: 0, sleep_time=0.100000
[INFO]Running task from function task_run_consensus()
[INFO]script_fn:'/data/0-rawreads/preads/cns_00001/c_00001.sh'
[INFO]jobid=J00a86a1aefc2b59f1897a7454967492ff85b98e320861bec9f694a80b21f54d5
[INFO]starting job Job(jobid='J00a86a1aefc2b59f1897a7454967492ff85b98e320861bec9f694a80b21f54d5', cmd='/bin/bash c_00001.sh', rundir='/data/0-rawreads/preads/cns_00001', options={'job_queue': None, 'sge_option': '', 'job_type': None})
[INFO]Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='J00a86a1aefc2b59f1897a7454967492ff85b98e320861bec9f694a80b21f54d5', cmd='/bin/bash c_00001.sh', rundir='/data/0-rawreads/preads/cns_00001', options={'job_queue': None, 'sge_option': '', 'job_type': None}), lang_exe='/bin/bash'))
[INFO]Queued 'task://localhost/cns_00001' ...
[INFO]tick: 4, #updatedTasks: 1, sleep_time=0.100000
[INFO]tick: 8, #updatedTasks: 1, sleep_time=0.500000
[INFO]tick: 16, #updatedTasks: 1, sleep_time=1.000000
[INFO]tick: 32, #updatedTasks: 1, sleep_time=1.000000
[INFO]tick: 64, #updatedTasks: 1, sleep_time=1.000000
[INFO]tick: 128, #updatedTasks: 1, sleep_time=1.000000
[INFO]tick: 256, #updatedTasks: 1, sleep_time=1.000000
[INFO]Success ('done'). Joining 'task://localhost/cns_00001'...
[INFO]Running task from function check_r_cns_task()
[WARNING]Missing taskObj.generated_script_fn for task. Maybe we did not need it? Skipping and continuing.
[INFO]Queued 'task://localhost/cns_check' ...
[INFO]Success ('done'). Joining 'task://localhost/cns_check'...
[INFO]Running task from function task_report_pre_assembly()
[INFO]Report inputs: {'job_done': '/data/0-rawreads/report/report_pa_done', 'length_cutoff': 13500, 'i_preads_fofn_fn': '/data/0-rawreads/preads/input_preads.fofn', 'genome_length': 0, 'script_fn': '/data/0-rawreads/report/run_report_pre_assembly.sh', 'o_json_fn': '/data/0-rawreads/report/pre_assembly_stats.json', 'i_raw_reads_db_fn': '/data/0-rawreads/raw_reads.db'}
[INFO]script_fn:'/data/0-rawreads/report/run_report_pre_assembly.sh'
[INFO]jobid=J6f00ac40e10787d82684b878e089afea35b9b3d163bbcaba80e9d263faa1679e
[INFO]starting job Job(jobid='J6f00ac40e10787d82684b878e089afea35b9b3d163bbcaba80e9d263faa1679e', cmd='/bin/bash run_report_pre_assembly.sh', rundir='/data/0-rawreads/report', options={'sge_option': ''})
[INFO]Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='J6f00ac40e10787d82684b878e089afea35b9b3d163bbcaba80e9d263faa1679e', cmd='/bin/bash run_report_pre_assembly.sh', rundir='/data/0-rawreads/report', options={'sge_option': ''}), lang_exe='/bin/bash'))
[INFO]Queued 'task://localhost/report_pre_assembly' ...
[ERROR]Task Fred{'URL': 'task://localhost/report_pre_assembly'} failed with exit-code=256
[INFO]Failure ('fail'). Joining 'task://localhost/report_pre_assembly'...
[INFO]_refreshTargets() finished with no thread running and no new job to submit
[CRITICAL]Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
/usr/local/lib/python2.7/dist-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py:537: UserWarning: 
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            "! Please wait for all threads / processes to terminate !"
            "! Also, maybe use 'ps' or 'qstat' to check all threads,!"
            "! processes and/or jobs are terminated cleanly.        !"
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

  warnings.warn(shutdown_msg)
[WARNING]#tasks=3, #alive=0
Traceback (most recent call last):
  File "/usr/local/bin/fc_run.py", line 4, in <module>
    __import__('pkg_resources').run_script('falcon-kit==0.7+git.54779b25532a4e1ace230013fe25f5c51a43ddaa', 'fc_run.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.7+git.54779b25532a4e1ace230013fe25f5c51a43ddaa-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.7+git.54779b25532a4e1ace230013fe25f5c51a43ddaa-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 576, in main
    main1(argv[0], args.config, args.logger)
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.7+git.54779b25532a4e1ace230013fe25f5c51a43ddaa-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 353, in main1
    setNumThreadAllowed=PypeProcWatcherWorkflow.setNumThreadAllowed)
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.7+git.54779b25532a4e1ace230013fe25f5c51a43ddaa-py2.7-linux-x86_64.egg/falcon_kit/mains/run1.py", line 459, in run
    wf.refreshTargets(exitOnFailure=exitOnFailure)
  File "/usr/local/lib/python2.7/dist-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 548, in refreshTargets
    raise Exception('Caused by:\n' + tb)
Exception: Caused by:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 523, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/usr/local/lib/python2.7/dist-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 750, in _refreshTargets
    failedJobCount, succeededJobCount))
LateTaskFailureError: 'Counted a total of 1 failure(s) and 2 success(es).'

```

The code from report stderr:

```
+ python2.7 -m pwatcher.mains.fs_heartbeat --directory=/data/0-rawreads/report --heartbeat-file=/data/mypwatcher/heartbeats/heartbeat-J6f00ac40e10787d82684b878e089afea35b9b3d163bbcaba80e9d263faa1679e --exit-file=/data/mypwatcher/exits/exit-J6f00ac40e10787d82684b878e089afea35b9b3d163bbcaba80e9d263faa1679e --rate=10.0 /bin/bash run_report_pre_assembly.sh
Namespace(command=['/bin/bash', 'run_report_pre_assembly.sh'], directory='/data/0-rawreads/report', exit_file='/data/mypwatcher/exits/exit-J6f00ac40e10787d82684b878e089afea35b9b3d163bbcaba80e9d263faa1679e', heartbeat_file='/data/mypwatcher/heartbeats/heartbeat-J6f00ac40e10787d82684b878e089afea35b9b3d163bbcaba80e9d263faa1679e', rate=10.0)

cwd:'/data/0-rawreads/report'
hostname=c77bf5c92fcc
heartbeat_fn='/data/mypwatcher/heartbeats/heartbeat-J6f00ac40e10787d82684b878e089afea35b9b3d163bbcaba80e9d263faa1679e'
exit_fn='/data/mypwatcher/exits/exit-J6f00ac40e10787d82684b878e089afea35b9b3d163bbcaba80e9d263faa1679e'
sleep_s=10.0
before setpgid: pid=725 pgid=521
 after setpgid: pid=725 pgid=725
In cwd: /data/0-rawreads/report, Blocking call: '/bin/bash run_report_pre_assembly.sh'
cd /data/0-rawreads/report
+ cd /data/0-rawreads/report
trap 'touch /data/0-rawreads/report/report_pa_done.exit' EXIT
+ trap 'touch /data/0-rawreads/report/report_pa_done.exit' EXIT
ls -il run_report_pre_assembly.sub.sh
+ ls -il run_report_pre_assembly.sub.sh
hostname
+ hostname
ls -il run_report_pre_assembly.sub.sh
+ ls -il run_report_pre_assembly.sub.sh
time /bin/bash ./run_report_pre_assembly.sub.sh
+ /bin/bash ./run_report_pre_assembly.sub.sh
python -m falcon_kit.mains.report_pre_assembly --genome-length 0 --length-cutoff 13500 --db /data/0-rawreads/raw_reads.db --preads-fofn /data/0-rawreads/preads/input_preads.fofn --out /data/0-rawreads/report/pre_assembly_stats.json
+ python -m falcon_kit.mains.report_pre_assembly --genome-length 0 --length-cutoff 13500 --db /data/0-rawreads/raw_reads.db --preads-fofn /data/0-rawreads/preads/input_preads.fofn --out /data/0-rawreads/report/pre_assembly_stats.json
[732]$ perl -e 'while (<>) { if ( m{>[^/]+/(\d+)\d/} ) { $id{$1}++; } }; while (my ($k, $v) = each %id) { $counts{$v}++; }; while (my ($k, $v) = each %counts) { print "$v $k
"; };' /data/0-rawreads/preads/cns_00001/cns_00001.fasta >
[732]$ perl -e 'while (<>) { if ( m{>[^/]+/0*(\d+)\d/(\d+)_(\d+)} ) { $lengths{$1} += ($3 - $2); } }; while (my ($k, $v) = each %lengths) { print "$k $v
"; };' /data/0-rawreads/preads/cns_00001/cns_00001.fasta >
[732]$ DBdump -h /data/0-rawreads/raw_reads.db >
ERROR:falcon_kit.stats_preassembly:Using arbitrary truncation metric: -1.0
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.7+git.54779b25532a4e1ace230013fe25f5c51a43ddaa-py2.7-linux-x86_64.egg/falcon_kit/stats_preassembly.py", line 210, in calc_dict
    trunc = metric_truncation(i_raw_reads_db_fn, i_preads_fofn_fn)
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.7+git.54779b25532a4e1ace230013fe25f5c51a43ddaa-py2.7-linux-x86_64.egg/falcon_kit/stats_preassembly.py", line 132, in metric_truncation
    dbdump_output = syscall(call)
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.7+git.54779b25532a4e1ace230013fe25f5c51a43ddaa-py2.7-linux-x86_64.egg/falcon_kit/util/io.py", line 77, in syscall
    output = sp.check_output(shlex.split(cmd))
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[732]$ DBdump -h /data/0-rawreads/raw_reads.db >
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.7+git.54779b25532a4e1ace230013fe25f5c51a43ddaa-py2.7-linux-x86_64.egg/falcon_kit/mains/report_pre_assembly.py", line 46, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.7+git.54779b25532a4e1ace230013fe25f5c51a43ddaa-py2.7-linux-x86_64.egg/falcon_kit/mains/report_pre_assembly.py", line 40, in main
    do_report(**vars(ARGS))
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.7+git.54779b25532a4e1ace230013fe25f5c51a43ddaa-py2.7-linux-x86_64.egg/falcon_kit/mains/report_pre_assembly.py", line 16, in do_report
    report_dict = stats_preassembly.calc_dict(**kwds)
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.7+git.54779b25532a4e1ace230013fe25f5c51a43ddaa-py2.7-linux-x86_64.egg/falcon_kit/stats_preassembly.py", line 215, in calc_dict
    raw_reads = read_lens_from_db(i_raw_reads_db_fn)
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.7+git.54779b25532a4e1ace230013fe25f5c51a43ddaa-py2.7-linux-x86_64.egg/falcon_kit/stats_preassembly.py", line 107, in read_lens_from_db
    return list(sorted(get_db_readlengths(db_fn)))
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.7+git.54779b25532a4e1ace230013fe25f5c51a43ddaa-py2.7-linux-x86_64.egg/falcon_kit/stats_preassembly.py", line 45, in get_db_readlengths
    return list(functional.parsed_readlengths_from_dbdump_output(syscall(call)))
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.7+git.54779b25532a4e1ace230013fe25f5c51a43ddaa-py2.7-linux-x86_64.egg/falcon_kit/util/io.py", line 77, in syscall
    output = sp.check_output(shlex.split(cmd))
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
touch /data/0-rawreads/report/report_pa_done.exit
+ touch /data/0-rawreads/report/report_pa_done.exit
 returned: 256
```

data derived from:  http://datasets.pacb.com.s3.amazonaws.com/2014/c_elegans/list.html
Exactly:
m140928_184123_42139_c100719602550000001823155305141590_s1_p0.1.subreads.fasta
m140928_184123_42139_c100719602550000001823155305141590_s1_p0.2.subreads.fasta
m140928_184123_42139_c100719602550000001823155305141590_s1_p0.3.subreads.fasta

How can I know because of what the error occurs? And what is the reason for this bug?

**Comment by pb-cdunn** [comment]
It seems that `DBdump` is not in your PATH. It should built in the `DAZZ_DB` module directory, and it should be installed into the `bin` (which could be virtualenv, PYTHONUSERBASE, or whatever you are using). Possibly you need to update all your submodules to the latest FALCON-integrate and re-install.

**Comment by KatarzynaGraczyk** [comment]
Thank you
