### ISSUE TITLE
Falcon install problem

### ISSUE THREAD

**Issue by Timothy-WANG** [PacificBiosciences/FALCON-integrate#87]
I have install the falcon from the easy way. However, when put:
$ make -j all
It come out the below problem. It shows that there is no pypeflow.common. what's wrong with it ? 

```
### Installed /exeh/exe5/software/Falcon01/FALCON-integrate/FALCON
Successfully installed falcon-kit-0.7-git.b-54779b25532a4e1ace230013fe25f5c51a43ddaa-n-
Cleaning up...
make[2]: Leaving directory '/exeh/exe5/software/Falcon01/FALCON-integrate/FALCON-make'
make check
make[2]: Entering directory '/exeh/exe5/software/Falcon01/FALCON-integrate/FALCON-make'
python -c 'import pypeflow.common; print pypeflow.common'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pypeflow.common
makefile:53: recipe for target 'check' failed
make[2]: *** [check] Error 1
make[2]: Leaving directory '/exeh/exe5/software/Falcon01/FALCON-integrate/FALCON-make'
makefile:16: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/exeh/exe5/software/Falcon01/FALCON-integrate/FALCON-make'
makefile:19: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by pb-cdunn** [comment]
```
git clone git://github.com/PacificBiosciences/FALCON-integrate.git
cd FALCON-integrate
git checkout master  # or whatever version you want
make init
source env.sh
make config-edit-user
make -j all
make test  # to run a simple one
```

Cat `env.sh`. And check your current environment. What are your current values for these?

```
PYTHONUSERBASE
FALCON_WORKSPACE
FALCON_PREFIX
PATH
```

Also, try this:

```
cd FALCON-integrate
git rev-parse HEAD
```

You should see `78e1569...`, which corresponds to the `1.7.5` tag. We test with TravisCI, so we know the whole thing works at least on that machine.

**Comment by samyeaman** [comment]
I faced a similar problem with the install at the same command but had a different error message:
```sh
make -j all
make -C ./FALCON-make/ all
make[1]: Entering directory `/data/programs/FALCON-integrate/FALCON-make'
make show
make[2]: Entering directory `/data/programs/FALCON-integrate/FALCON-make'
mkdir -p /data/programs/FALCON-integrate/fc_env/bin
which python
/usr/local/bin/python
echo "PYTHONUSERBASE=/data/programs/FALCON-integrate/fc_env"
PYTHONUSERBASE=/data/programs/FALCON-integrate/fc_env
python -c 'import site; print site.USER_BASE'
/data/programs/FALCON-integrate/fc_env
echo "FALCON_PIP_EDIT=--edit"
FALCON_PIP_EDIT=--edit
echo "FALCON_PIP_USER=--user"
FALCON_PIP_USER=--user
make[2]: Leaving directory `/data/programs/FALCON-integrate/FALCON-make'
make install-pip
make[2]: Entering directory `/data/programs/FALCON-integrate/FALCON-make'
python -c 'import pip; print pip' || python get-pip.py --user
<module 'pip' from '/usr/local/lib/python2.7/site-packages/pip/__init__.pyc'>
pip install --user --upgrade pip
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip import main
ImportError: No module named pip
make[2]: *** [install-pip] Error 1
make[2]: Leaving directory `/data/programs/FALCON-integrate/FALCON-make'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/data/programs/FALCON-integrate/FALCON-make'
make: *** [all] Error 2
```

when I type cat env.sh:
```sh
FALCON_WORKSPACE=$(pwd)
PYTHONUSERBASE=$(pwd)/fc_env
FALCON_PREFIX=${PYTHONUSERBASE}
PATH=${PYTHONUSERBASE}/bin:${FALCON_PREFIX}/bin:${PATH}
export PYTHONUSERBASE
export FALCON_WORKSPACE
export FALCON_PREFIX
export PATH
mkdir -p ${FALCON_PREFIX}/include
mkdir -p ${FALCON_PREFIX}/bin
mkdir -p ${FALCON_PREFIX}/lib
```

and when I run git rev-parse HEAD

`a72f47c4600fb31c993151c1d03c1787ba42b161`

I tried running these commands but it didn't fix it:
```sh
$ sudo python -m pip install --upgrade --force setuptools
$ sudo python -m pip install --upgrade --force pip
```
Sorry if I'm doing something obviously dumb here. Any suggestions?

**Comment by pb-cdunn** [comment]
What is the path to your Python? And what is the version of Python?

I think I have seen this error with a virtualenv Python. A "user-install" (`PYTHONUSERBASE` + `pip install --user`) does not work with virtualenv. The solution would be to stop using virtualenv (which causes endless problems), or to use a system install (`make config-edit` instead of `make config-edit-user`). You might also need to "activate" your virtualenv, since the root problem for you is that `/usr/local/bin/pip` is not finding a Python which actually has the `pip` module.
